## ETL

### Acknowledgments

##### Data provided by Open Source Mental Health (OSMH) https://osmhhelp.org/research.html
##### The following ETL script is primarily provided by Mariam Raafat Mohamed in 'Mental Health Tech: 9 Years of Insights & Prediction' https://www.kaggle.com/code/mariamraafatbrownies/mental-health-tech-9-years-of-insights-prediction/notebook
##### I've modified and changed methodology where relevant, including:
> ##### Keeping variables that were dropped for further analysis in EDA
> ##### Different method for encoding responses
#####
##### All code in subsequent notebooks is my own work

### Load relevant libraries

In [1]:
from pathlib import Path
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import numpy as np

### Read in the Data

In [2]:
# Resolve repository root whether notebook is launched
# from the repository root or notebooks/ directory.
REPO_ROOT = Path.cwd()
if REPO_ROOT.name == "notebooks":
    REPO_ROOT = REPO_ROOT.parent

RAW_DATA = REPO_ROOT / "data" / "raw"
PROCESSED_DATA = REPO_ROOT / "data" / "processed"

In [3]:
df_2014 = pd.read_csv(RAW_DATA / 'survey.csv')
df_2016 = pd.read_csv(RAW_DATA / 'mental-heath-in-tech-2016_20161114.csv')
df_2017 = pd.read_csv(RAW_DATA / 'OSMI Mental Health in Tech Survey 2017.csv')
df_2018 = pd.read_csv(RAW_DATA / 'OSMI Mental Health in Tech Survey 2018.csv')
df_2019 = pd.read_csv(RAW_DATA / 'OSMI 2019 Mental Health in Tech Survey Results - OSMI Mental Health in Tech Survey 2019.csv')
df_2020 = pd.read_csv(RAW_DATA / 'OSMI 2020 Mental Health in Tech Survey Results .csv')
df_2021 = pd.read_csv(RAW_DATA / 'OSMI 2021 Mental Health in Tech Survey Results .csv')
df_2022 = pd.read_csv(RAW_DATA / 'responses_2022.csv')
df_2023 = pd.read_csv(RAW_DATA / 'responses_2023.csv')

<h3 style="color:#1b1d1f">Understanding the Columns:</h3>

| Column Name               | Question                                                                                   |
|--------------------------|--------------------------------------------------------------------------------------------|
| Timestamp                | Timestamp                                                                                 |
| Age                      | Age                                                                                        |
| Gender                   | Gender                                                                                     |
| Country                  | Country                                                                                    |
| state                    | If you live in the United States, which state or territory do you live in?                |
| self_employed            | Are you self-employed?                                                                     |
| family_history           | Do you have a family history of mental illness?                                            |
| treatment                | Have you sought treatment for a mental health condition?                                   |
| work_interfere           | If you have a mental health condition, do you feel that it interferes with your work?      |
| no_employees             | How many employees does your company or organization have?                                 |
| remote_work              | Do you work remotely (outside of an office) at least 50% of the time?                      |
| tech_company             | Is your employer primarily a tech company/organization?                                    |
| benefits                 | Does your employer provide mental health benefits?                                         |
| care_options             | Do you know the options for mental health care your employer provides?                     |
| wellness_program         | Has your employer ever discussed mental health as part of an employee wellness program?    |
| seek_help                | Does your employer provide resources to learn more about mental health issues and how to seek help? |
| anonymity                | Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources? |
| leave                    | How easy is it for you to take medical leave for a mental health condition?                |
| mental_health_consequence| Do you think that discussing a mental health issue with your employer would have negative consequences? |
| phys_health_consequence  | Do you think that discussing a physical health issue with your employer would have negative consequences? |
| coworkers                | Would you be willing to discuss a mental health issue with your coworkers?                 |
| supervisor               | Would you be willing to discuss a mental health issue with your direct supervisor(s)?      |
| mental_health_interview  | Would you bring up a mental health issue with a potential employer in an interview?        |
| phys_health_interview    | Would you bring up a physical health issue with a potential employer in an interview?      |
| mental_vs_physical       | Do you feel that your employer takes mental health as seriously as physical health?        |
| obs_consequence          | Have you heard of or observed negative consequences for coworkers with mental health conditions in your workplace? |
| comments                 | Any additional notes or comments                                                           |

### Summarize data

In [4]:
df_2014.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,No,Yes,Yes,Not sure,No,Yes,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,No,No,Don't know,No,Don't know,Don't know,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,No,Yes,No,No,No,No,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,No,Yes,No,Yes,No,No,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,Yes,Yes,Yes,No,Don't know,Don't know,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [5]:
df_2016.head()

,Are you self-employed?,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health concerns and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:",Do you think that discussing a mental health disorder with your employer would have negative consequences?,Do you think that discussing a physical health issue with your employer would have negative consequences?,Would you feel comfortable discussing a mental health disorder with your coworkers?,Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?,Do you feel that your employer takes mental health as seriously as physical health?,Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?,Do you have medical coverage (private insurance or state-provided) which includes treatment of mental health issues?,Do you know local or online resources to seek help for a mental health disorder?,"If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?","If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?","If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?","If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?",Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",Do you have previous employers?,Have your previous employers provided mental health benefits?,Were you aware of the options for mental health care provided by your previous employers?,Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?,Did your previous employers provide resources to learn more about mental health issues and how to seek help?,Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?,Do you think that discussing a mental health disorder with previous employers would have negative consequences?,Do you think that discussing a physical health issue with previous employers would have negative consequences?,Would you have been willing to discuss a mental health issue with your previous co-workers?,Would you have been willing to discuss a mental health issue with your direct supervisor(s)?,Did you feel that your previous employers took mental health as seriously as physical health?,Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Why or why not?,Would you bring up a mental health issue with a potential employer in an interview?,Why or why not?.1,Do you feel that being identified as a person with a mental health issue would hurt your career?,Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?,How willing would you be to share with friends and family that you have a mental illness?,Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?,Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?,Do you have a family history of mental illness?,Have you had a mental health disorder in the past?,Do you currently have a mental health disorder?,"If yes, what condition(s) have you been diagnosed with?","If maybe, what condition(s) do you believe you have?",Have you been diagnosed with a mental health condition by a medical professional?,"If so, what condition(s) were you diagnosed with?",Have you ever sought treatment for a mental health issue from a mental health professional?,"If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?","If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?",What is your age?,What is your gender?,What country do you live in?,What US state or territory do you live in?,What country do you work in?,What US state or territory do you work in?,Which of the following best describes your work position?,Do you work remotely?
0,0,26-100,1.0,NaN,Not eligible for coverage / N/A,NaN,No,No,I don't know,Very easy,No,No,Maybe,Yes,I don't know,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"No, none did",N/A (not currently aware),I don't know,None did,I don't know,Some of them,None of them,Some of my previous employers,Some of my previous employers,I don't know,None of them,Maybe,NaN,Maybe,NaN,Maybe,"No, I don't think they would",Somewhat open,No,NaN,No,Yes,No,NaN,NaN,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",0,Not applicable to me,Not applicable to me,39,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Sometimes
1,0,6-25,1.0,NaN,No,Yes,Yes,Yes,Yes,Somewhat easy,No,No,Maybe,Yes,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"Yes, they all did",I was aware of some,None did,Some did,"Yes, always",None of them,None of them,"No, at none of my previous employers",Some of my previous employers,Some did,None of them,Maybe,It would depend on the health issue. If there ...,No,While mental health has become a more prominen...,"No, I don't think it would","No, I don't think they would",Somewhat open,No,NaN,Yes,Yes,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",NaN,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",1,Rarely,Sometimes,29,male,United States of America,Illinois,United States of America,Illinois,Back-end Developer|Front-end Developer,Never
2,0,6-25,1.0,NaN,No,NaN,No,No,I don't know,Neither easy nor difficult,Maybe,No,Maybe,Maybe,I don't know,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,"No, none did",N/A (not currently aware),None did,Some did,I don't know,I don't know,Some of them,Some of my previous employers,I don't know,I don't know,Some of them,Yes,"They would provable need to know, to Judge if ...",Yes,"Stigma, mainly.",Maybe,Maybe,Somewhat open,Maybe/Not sure,Yes,No,Maybe,No,NaN,NaN,No,NaN,1,Not applicable to me,Not applicable to me,38,Male,United Kingdom,NaN,United Kingdom,NaN,Back-end Developer,Always
3,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"Yes, I know several","Sometimes, if it comes up",I'm not sure,"Sometimes, if it comes up",I'm not sure,Yes,1-25%,1,Some did,N/A (not currently aware),None did,None did,I don't know,Some of them,Some of them,Some of my previous employers,Some of my previous employers,I don't know,Some of them,Yes,"old back injury, doesn't cause me many issues ...",Maybe,would not if I was not 100% sure that the disc...,"Yes, I think it would",Maybe,Neutral,No,NaN,No,Yes,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",NaN,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",1,Sometimes,Sometimes,43,male,United Kingdom,NaN,United Kingdom,NaN,Supervisor/Team Lead,Sometimes
4,0,6-25,0.0,1.0,Yes,Yes,No,No,No,Neither easy nor difficult,Yes,Maybe,Maybe,No,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,I don't know,N/A (not currently aware),Some did,None did,I don't know,Some of them,Some of them,"No, at none of my previous employers",Some of my previous employers,Some did,Some of them,Maybe,Depending on the interview stage and whether I...,No,I don't know,"Yes, I think it would",Maybe,Somewhat open,"Yes, I experienced",Yes,Yes,Yes,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",NaN,Yes,"Anxiety Disorder (Generalized, Social, Phobia,...",1,Sometimes,Sometimes,43,Female,United States of America,Illinois,United States of America,Illinois,Executive Leadership|Supervisor/Team Lead|Dev ...,Sometimes

In [6]:
df_2017.head()

,#,<strong>Are you self-employed?</strong>,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",Would you feel more comfortable talking to your coworkers about your physical health or your mental health?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Have you ever discussed your mental health with your employer?,"Describe the conversation you had with your employer about your mental health, including their reactions and what actions were taken to address your mental health issue/questions.",Would you feel comfortable discussing a mental health issue with your coworkers?,Have you ever discussed your mental health with coworkers?,Describe the conversation with coworkers you had about your mental health including their reactions.,Have you ever had a coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names).,"Overall, how much importance does your employer place on physical health?","Overall, how much importance does your employer place on mental health?",Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?,Do you know local or online resources to seek help for a mental health issue?,"<strong>If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?</strong>","If you have revealed a mental health disorder to a client or business contact, how has this affected you or the relationship?","<strong>If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?</strong>","If you have revealed a mental health disorder to a coworker or employee, how has this impacted you or the relationship?",Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",<strong>Do you have previous employers?</strong>,Was your employer primarily a tech company/organization?,<strong>Have your previous employers provided mental health benefits?</strong>,<strong>Were you aware of the options for mental health care provided by your previous employers?</strong>,Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?,Did your previous employers provide resources to learn more about mental health disorders and how to seek help?,Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?,Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?,Would you have been willing to discuss your mental health with your direct supervisor(s)?,Did you ever discuss your mental health with your previous employer?,"Describe the conversation you had with your previous employer about your mental health, including their reactions and actions taken to address your mental health issue/questions.",<strong>Would you have been willing to discuss your mental health with your coworkers at previous employers?</strong>,Did you ever discuss your mental health with a previous coworker(s)?,Describe the conversation you had with your previous coworkers about your mental health including their reactions.,Did you ever have a previous coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names)..1,"Overall, how much importance did your previous employer place on physical health?","Overall, how much importance did your previous employer place on mental health?",Do you currently have a mental health disorder?,Have you ever been diagnosed with a mental health disorder?,"Anxiety Disorder (Generalized, Social, Phobia, etc)","Mood Disorder (Depression, Bipolar Disorder, etc)","Psychotic Disorder (Schizophrenia, Schizoaffective, etc)","Eating Disorder (Anorexia, Bulimia, etc)",Attention Deficit Hyperactivity Disorder,"Personality Disorder (Borderline, Antisocial, Paranoid, etc)",Obsessive-Compulsive Disorder,Post-Traumatic Stress Disorder,Stress Response Syndromes,Dissociative Disorder,Substance Use Disorder,Addictive Disorder,Other,"Anxiety Disorder (Generalized, Social, Phobia, etc).1","Mood Disorder (Depression, Bipolar Disorder, etc).1","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).1","Eating Disorder (Anorexia, Bulimia, etc).1",Attention Deficit Hyperactivity Disorder.1,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).1",Obsessive-Compulsive Disorder.1,Post-traumatic Stress Disorder,Stress Response Syndromes.1,Dissociative Disorder.1,Substance Use Disorder.1,Addictive Disorder.1,Other.1,"Anxiety Disorder (Generalized, Social, Phobia, etc).2","Mood Disorder (Depression, Bipolar Disorder, etc).2","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).2","Eating Disorder (Anorexia, Bulimia, etc).2",Attention Deficit Hyperactivity Disorder.2,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).2",Obsessive-Compulsive Disorder.2,Post-traumatic Stress Disorder.1,Stress Response Syndromes.2,Dissociative Disorder.2,Substance Use Disorder.2,Addictive Disorder.2,Other.2,Have you had a mental health disorder in the past?,Have you ever sought treatment for a mental health disorder from a mental health professional?,Do you have a family history of mental illness?,"If you have a mental health disorder, how often do you feel that it interferes with your work <strong>when being treated effectively?</strong>","If you have a mental health disorder, how often do you feel that it interferes with your work <strong>when <em>NOT</em> being treated effectively (i.e., when you are experiencing symptoms)?</strong>",Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Why or why not?,Would you bring up your mental health with a potential employer in an interview?,Why or why not?.1,Are you openly identified at work as a person with a mental health issue?,Has being identified as a person with a mental health issue affected your career?,How has it affected your career?,"If they knew you suffered from a mental health disorder, how do you think that team members/co-workers would react?",<strong>Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?</strong>,Describe the circumstances of the badly handled or unsupportive response.,<strong>Have you observed or experienced supportive or well handled response to a mental health issue in your current or previous workplace?</strong>,Describe the circumstances of the supportive or well handled response.,"Overall, how well do you think the tech industry supports employees with mental health issues?",Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.,"If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.",Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used <em>anonymously</em> and only with your permission.),What is your age?,What is your gender?,What country do you <strong>live</strong> in?,What US state or territory do you <strong>live</strong> in?,What is your race?,Other.3,What country do you <strong>work</strong> in?,What US state or territory do you <strong>work</strong> in?,Start Date (UTC),Submit Date (UTC),Network ID
0,e49fe87572831232dcfa51b376b22039,0,100-500,1.0,1.0,No,Yes,No,I don't know,I don't know,I don't know,Same level of comfort for each,Yes,0.0,NaN,Yes,1.0,Spoke about my anxiety they were very supportive,1.0,"they spoke about their depression, i offered m...",6.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0,I don't know,N/A (was not aware),Some did,Some did,"Yes, always",Physical health,"Yes, all of my previous supervisors",0.0,NaN,"No, at none of my previous employers",0.0,NaN,0.0,NaN,3.0,3.0,Possibly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possibly,1,No,Sometimes,Sometimes,No,5,Yes,NaN,No,I'd be worried they wouldn't hire me,0.0,NaN,NaN,10.0,"Yes, I experienced",NaN,"Yes, I experienced",NaN,1.0,They don't take it seriously,NaN,0.0,27.0,Female,United Kingdom,NaN,NaN,NaN,United Kingdom,NaN,2018-05-16 12:32:04,2018-05-16 12:42:40,464b7a12f1
1,a1eede444ac024928d247a8372d54931,0,100-500,1.0,1.0,Yes,Yes,No,No,I don't know,I don't know,Same level of comfort for each,Maybe,0.0,NaN,Yes,1.0,"the coworker was comprehensive, empathetic and...",1.0,"a discussion about symptoms of depression, and...",7.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,Some did,I was aware of some,None did,None did,I don't know,Physical health,"No, none of my previous supervisors",0.0,NaN,At some of my previous employers,1.0,understanding and supportive,0.0,NaN,5.0,2.0,Possibly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possibly,0,No,Not applicable to me,Sometimes,No,4,Yes,it may require specific measures to accomodate...,No,mental health issues are stigmatised and misun...,0.0,NaN,NaN,6.0,"Yes, I observed","During a discussion about ""mental health first...",Maybe/Not sure,NaN,2.0,"raise awareness, talk about it to lessen the s...",NaN,0.0,31.0,male,United Kingdom,NaN,NaN,NaN,United Kingdom,NaN,2018-05-16 12:31:13,2018-05-16 12:40:40,464b7a12f1
2,37d3fd67f62bd1e0a2dea4f9cd440d98,0,6-25,1.0,1.0,I don't know,No,I don't know,No,Yes,Difficult,Same level of comfort for each,Yes,1.0,"The conversation went well, he too suffers men...",Maybe,1.0,They all seemed understanding and some even ad...,0.0,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,Some did,N/A (was not aware),None did,None did,I don't know,Physical health,"No, none of my previous supervisors",0.0,NaN,At some of my previous employers,1.0,The ones that I discussed it with were actuall...,0.0,NaN,8.0,0.0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Substance Use Disorder,NaN,NaN,Yes,1,Yes,Sometimes,Sometimes,Yes,5,Maybe,I will sometimes bring up my psoriasis just as...,No,stigma,1.0,1.0,3.0,5.0,"Yes, I experienced",I was suffering depression and I was open abou...,"Yes, I experienced",NaN,1.0,"Education and awareness, statistics, add suppo...",NaN,1.0,36.0,male,United States of America,Missouri,White,NaN,United States of America,Missouri,2018-05-09 05:34:05,2018-05-09 05:46:04,1eb7e0cb94
3,519b759442c1cab0e9b5a8a1acb1b216,0,More than 1000,1.0,1.0,Yes,Yes,I don't know,I don't know,Yes,Difficult,Same level of comfort for each,Yes,1.0,Direct Manager and HR know because of medicati...,Yes,1.0,Coworkers that have become friends with me are...,0.0,NaN,7.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Attention Deficit Hyperactivity Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,1,I don't know,Sometimes,Often,No,10,No,Anything that may hurt my chances to be hired ...,No,Might hurt my chances,0.0,NaN,NaN,5.0,Maybe/Not sure,NaN,Maybe/Not sure,NaN,2.0,"More support, less burnout and death marches",NaN,0.0,22.0,Male,United States of America,Washington,White,NaN,United States of America,Washington,2018-05-04 23:19:14,2018-05-04 23:23:23,63852edbc4
4,ef0af4927b575b1a3e607c11ca37870e,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"Yes, I know several","Sometimes, if it comes up",No change,"No, because it doesn't matter",No change,Yes,1-25%,1,0.0,"No, none did",N/A (none offered),None did,None did,"Yes, always",Same level of comfort for each,"No, none of my previous supervisors",0.0,NaN,"No, at none of my previous employers",1.0,I'm in mental heatlh so I talk about it often.,1.0,They talked about as caregivers of family member.,8.0,8.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Often,Sometimes,No,10,Maybe,It depends. it's not something you start with ...,No,Don't think it's connected to the job. You do ...,0.0,NaN,NaN,4.0,No,NaN,"Yes, I observed",NaN,1.0,I think tech is more internal and they don't r...,nope,1.0,52.0,female,United States of America,Illinois,More than one of the above,NaN,United States of America,Illinois,2018-05-03 00:40:24,2018-05-03 00:53:20,43237889f1

In [7]:
df_2018.head()

,#,<strong>Are you self-employed?</strong>,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",Would you feel more comfortable talking to your coworkers about your physical health or your mental health?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Have you ever discussed your mental health with your employer?,"Describe the conversation you had with your employer about your mental health, including their reactions and what actions were taken to address your mental health issue/questions.",Would you feel comfortable discussing a mental health issue with your coworkers?,Have you ever discussed your mental health with coworkers?,Describe the conversation with coworkers you had about your mental health including their reactions.,Have you ever had a coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names).,"Overall, how much importance does your employer place on physical health?","Overall, how much importance does your employer place on mental health?",Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?,Do you know local or online resources to seek help for a mental health issue?,"<strong>If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?</strong>","If you have revealed a mental health disorder to a client or business contact, how has this affected you or the relationship?","<strong>If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?</strong>","If you have revealed a mental health disorder to a coworker or employee, how has this impacted you or the relationship?",Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",<strong>Do you have previous employers?</strong>,Was your employer primarily a tech company/organization?,<strong>Have your previous employers provided mental health benefits?</strong>,<strong>Were you aware of the options for mental health care provided by your previous employers?</strong>,Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?,Did your previous employers provide resources to learn more about mental health disorders and how to seek help?,Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?,Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?,Would you have been willing to discuss your mental health with your direct supervisor(s)?,Did you ever discuss your mental health with your previous employer?,"Describe the conversation you had with your previous employer about your mental health, including their reactions and actions taken to address your mental health issue/questions.",<strong>Would you have been willing to discuss your mental health with your coworkers at previous employers?</strong>,Did you ever discuss your mental health with a previous coworker(s)?,Describe the conversation you had with your previous coworkers about your mental health including their reactions.,Did you ever have a previous coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names)..1,"Overall, how much importance did your previous employer place on physical health?","Overall, how much importance did your previous employer place on mental health?",Do you currently have a mental health disorder?,Have you ever been diagnosed with a mental health disorder?,"Anxiety Disorder (Generalized, Social, Phobia, etc)","Mood Disorder (Depression, Bipolar Disorder, etc)","Psychotic Disorder (Schizophrenia, Schizoaffective, etc)","Eating Disorder (Anorexia, Bulimia, etc)",Attention Deficit Hyperactivity Disorder,"Personality Disorder (Borderline, Antisocial, Paranoid, etc)",Obsessive-Compulsive Disorder,Post-Traumatic Stress Disorder,Stress Response Syndromes,Dissociative Disorder,Substance Use Disorder,Addictive Disorder,Other,"Anxiety Disorder (Generalized, Social, Phobia, etc).1","Mood Disorder (Depression, Bipolar Disorder, etc).1","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).1","Eating Disorder (Anorexia, Bulimia, etc).1",Attention Deficit Hyperactivity Disorder.1,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).1",Obsessive-Compulsive Disorder.1,Post-traumatic Stress Disorder,Stress Response Syndromes.1,Dissociative Disorder.1,Substance Use Disorder.1,Addictive Disorder.1,Other.1,"Anxiety Disorder (Generalized, Social, Phobia, etc).2","Mood Disorder (Depression, Bipolar Disorder, etc).2","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).2","Eating Disorder (Anorexia, Bulimia, etc).2",Attention Deficit Hyperactivity Disorder.2,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).2",Obsessive-Compulsive Disorder.2,Post-traumatic Stress Disorder.1,Stress Response Syndromes.2,Dissociative Disorder.2,Substance Use Disorder.2,Addictive Disorder.2,Other.2,Have you had a mental health disorder in the past?,Have you ever sought treatment for a mental health disorder from a mental health professional?,Do you have a family history of mental illness?,"If you have a mental health disorder, how often do you feel that it interferes with your work <strong>when being treated effectively?</strong>","If you have a mental health disorder, how often do you feel that it interferes with your work <strong>when</strong> <em><strong>NOT</strong></em><strong> being treated effectively (i.e., when you are experiencing symptoms)?</strong>",Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Why or why not?,Would you bring up your mental health with a potential employer in an interview?,Why or why not?.1,Are you openly identified at work as a person with a mental health issue?,Has being identified as a person with a mental health issue affected your career?,How has it affected your career?,"If they knew you suffered from a mental health disorder, how do you think that team members/co-workers would react?",<strong>Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?</strong>,Describe the circumstances of the badly handled or unsupportive response.,<strong>Have you observed or experienced supportive or well handled response to a mental health issue in your current or previous workplace?</strong>,Describe the circumstances of the supportive or well handled response.,"Overall, how well do you think the tech industry supports employees with mental health issues?",Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.,"If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.",Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used <em>anonymously</em> and only with your permission.),What is your age?,What is your gender?,What country do you <strong>live</strong> in?,What US state or territory do you <strong>live</strong> in?,What is your race?,Other.3,What country do you <strong>work</strong> in?,What US state or territory do you <strong>work</strong> in?,Start Date (UTC),Submit Date (UTC),Network ID
0,e44a0a34f2465940beda2a1537e9b99e,0,More than 1000,1.0,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,Physical health,No,1.0,I informed my employer that I was very sick du...,No,1.0,I do have a supportive group of coworkers to t...,1.0,I have a coworker who lives with bipolar disea...,8.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,"No, none did","No, I only became aware later",None did,None did,I don't know,Physical health,"No, none of my previous supervisors",0.0,NaN,"No, at none of my previous employers",0.0,NaN,0.0,NaN,8.0,2.0,Possibly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Rarely,Sometimes,Yes,3,No,I don’t see it as relevant,No,Not relevant,0,NaN,NaN,5,"Yes, I observed",I saw people who were on “stress” leave ridicu...,"Yes, I observed",NaN,2,"Since the industry is male dominated, there sh...",NaN,1,57,Female,Canada,NaN,NaN,NaN,Canada,NaN,2018-12-29 23:46:38,2018-12-30 00:00:03,4bbb884ccc
1,0d698e3beca20fb75f19b9d528e36d73,0,More than 1000,1.0,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat difficult,Physical health,No,0.0,NaN,No,0.0,NaN,0.0,NaN,8.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,NaN,NaN,NaN,Post-traumatic Stress Disorder,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Sometimes,Often,NaN,3,Yes,because why not,No,because i am at least 51% sure it would affect...,0,NaN,NaN,3,No,NaN,No,NaN,3,"it's a comfort thing at this point imo, needs ...",NaN,1,29,male,United States of America,Massachusetts,White,NaN,United States of America,Massachusetts,2018-12-27 21:40:40,2018-12-27 21:45:45,275e7543bd
2,61a40c9071eb36fa9caa254d31500c41,0,6-25,0.0,1.0,Yes,Yes,No,No,I don't know,Somewhat easy,Physical health,No,0.0,NaN,No,0.0,NaN,1.0,We had a coworker have a drastic turn in behav...,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,"Yes, they all did","Yes, I was aware of all of them",Some did,Some did,I don't know,Physical health,"No, none of my previous supervisors",0.0,NaN,"No, at none of my previous employers",0.0,NaN,0.0,NaN,4.0,1.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,Yes,Not applicable to me,Not applicable to me,NaN,2,No,I wouldn't bring it up unless it would potenti...,No,Mainly because I don't suffer from a mental he...,0,NaN,NaN,9,No,NaN,Maybe/Not sure,NaN,3,"If it is mentioned at all, it's during a meeti...","I thinka lot of people ""grin and bear it"". I'v...",0,46,Male,United States of America,Florida,White,NaN,United States of America,Florida,2018-12-21 17:37:43,2018-12-21 18:08:01,43994c3dba
3,f8624340bead7deb08abb766704ddf6b,0,6-25,1.0,1.0,No,No,No,No,I don't know,Neither easy nor difficult,Physical health,No,0.0,NaN,Maybe,0.0,NaN,1.0,NaN,8.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,"No, none did",N/A (was not aware),None did,None did,I don't know,Physical health,"No, none of my previous supervisors",0.0,NaN,At some of my previous employers,0.0,NaN,1.0,NaN,8.0,8.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,No,Not applicable to me,Not applicable to me,Maybe,9,No,NaN,No,NaN,0,NaN,NaN,5,No,NaN,Maybe/Not sure,NaN,1,NaN,NaN,0,34,male,Norway,NaN,NaN,NaN,Norway,NaN,2018-12-21 16:37:56,2018-12-21 16:44:44,907b3a3faa
4,31d3ae93b68d79e504a0a643601b6b1e,0,26-100,1.0,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,Yes,1.0,"""Hey, I have a lot of anxiety sometimes."" ""Oh...",Yes,1.0,NaN,1.0,NaN,7.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,"No, none did",N/A (none offered),None did,None did,No,Same level of comfort for each,Some of my previous supervisors,1.0,"""Hey, this is a lot of pressure you're putting...",At some of my previous employers,1.0,NaN,1.0,NaN,3.0,0.0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,Attention Deficit Hyperactivity Disorder,"Personality Disorder (Borderline, Antisocial, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Rarely,Sometimes,No,7,Yes,NaN,Yes,They should know what I need and expect. If t...,1,0.0,NaN,5,"Yes, I observed",NaN,"Yes, I observed",NaN,4,NaN,NaN,1,29,Ostensibly Male,United States of America,Tennessee,White,NaN,United States of America,Tennessee,2018-12-20 19:39:02,2018-12-20 20:58:34,26df20fea3

In [8]:
df_2019.head()

,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",Would you feel more comfortable talking to your coworkers about your physical health or your mental health?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Have you ever discussed your mental health with your employer?,"Describe the conversation you had with your employer about your mental health, including their reactions and what actions were taken to address your mental health issue/questions.",Would you feel comfortable discussing a mental health issue with your coworkers?,Have you ever discussed your mental health with coworkers?,Describe the conversation with coworkers you had about your mental health including their reactions.,Have you ever had a coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names).,"Overall, how much importance does your employer place on physical health?","Overall, how much importance does your employer place on mental health?",Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?,Do you know local or online resources to seek help for a mental health issue?,"If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?","If you have revealed a mental health disorder to a client or business contact, how has this affected you or the relationship?","If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?","If you have revealed a mental health disorder to a coworker or employee, how has this impacted you or the relationship?",Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",*Do you have previous employers?*,Was your employer primarily a tech company/organization?,Have your previous employers provided mental health benefits?,Were you aware of the options for mental health care provided by your previous employers?,Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?,Did your previous employers provide resources to learn more about mental health disorders and how to seek help?,Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?,Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?,Would you have been willing to discuss your mental health with your direct supervisor(s)?,Did you ever discuss your mental health with your previous employer?,"Describe the conversation you had with your previous employer about your mental health, including their reactions and actions taken to address your mental health issue/questions.",Would you have been willing to discuss your mental health with your coworkers at previous employers?,Did you ever discuss your mental health with a previous coworker(s)?,Describe the conversation you had with your previous coworkers about your mental health including their reactions.,Did you ever have a previous coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names)..1,"Overall, how much importance did your previous employer place on physical health?","Overall, how much importance did your previous employer place on mental health?",Do you *currently* have a mental health disorder?,Have you ever been *diagnosed* with a mental health disorder?,*What disorder(s) have you been diagnosed with?*,"*If possibly, what disorder(s) do you believe you have?*","*If so, what disorder(s) were you diagnosed with?*",Have you had a mental health disorder in the past?,Have you ever sought treatment for a mental health disorder from a mental health professional?,Do you have a family history of mental illness?,"If you have a mental health disorder, how often do you feel that it interferes with your work *when being treated effectively?*","If you have a mental health disorder, how often do you feel that it interferes with your work *when* _*NOT*_* being treated effectively (i.e., when you are experiencing symptoms)?*",Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Why or why not?,Would you bring up your *mental* health with a potential employer in an interview?,Why or why not?.1,Are you openly identified at work as a person with a mental health issue?,Has being identified as a person with a mental health issue affected your career?,How has it affected your career?,"If they knew you suffered from a mental health disorder, how do you think that your team members/co-workers would react?",Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the badly handled or unsupportive response.,Have you observed or experienced a *supportive or well handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the supportive or well handled response.,"Overall, how well do you think the tech industry supports employees with mental health issues?",Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.,"If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.",Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used _anonymously_ and only with your permission.),What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What is your race?,What country do you *work* in?,What US state or territory do you *work* in?
0,False,26-100,True,True,I don't know,No,Yes,Yes,I don't know,Very easy,Physical health,Yes,False,NaN,Yes,True,Mainly was a general 'maybe I should go see so...,True,They talked about how they are active in the m...,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,I don't know,N/A (was not aware),Some did,"Yes, they all did",I don't know,Physical health,Some of my previous supervisors,False,NaN,At some of my previous employers,False,NaN,True,NaN,8.0,5.0,Don't Know,NaN,NaN,NaN,NaN,No,False,No,Not applicable to me,Not applicable to me,No,8,Yes,If it impacts work I would bring it up,Maybe,If I feel it's under control I likely wouldn't...,False,NaN,NaN,8,No,NaN,Maybe/Not sure,NaN,4,NaN,NaN,False,25,Male,United States of America,Nebraska,White,United States of America,Nebraska
1,False,26-100,True,True,Yes,No,No,Yes,Yes,I don't know,Physical health,Maybe,False,NaN,Maybe,True,I prefer only to say that a recent coworker ha...,True,I prefer only to say that a recent coworker ha...,5.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,False,"Yes, they all did",I was aware of some,Some did,Some did,"Yes, always",Physical health,Some of my previous supervisors,False,NaN,At some of my previous employers,True,I prefer only to say that those previous cowor...,True,NaN,8.0,5.0,Possibly,NaN,NaN,"Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,Possibly,False,Yes,Sometimes,Often,No,7,No,I do not trust that the potential employer wou...,No,I do not trust that the potential employer wou...,False,NaN,NaN,7,"Yes, I observed","As I recall, a direct supervisor was identifie...","Yes, I experienced",NaN,1,NaN,NaN,False,51,male,United States of America,Nebraska,White,United States of America,Nebraska
2,False,26-100,True,True,I don't know,No,No,I don't know,I don't know,Somewhat difficult,Same level of comfort for each,No,False,NaN,Maybe,True,"It doesn't truly count as a coworker, as he is...",True,"It doesn't truly count as a coworker, as he is...",5.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,I don't know,N/A (was not aware),None did,None did,I don't know,Physical health,"No, none of my previous supervisors",False,NaN,"No, at none of my previous employers",False,NaN,False,NaN,10.0,2.0,No,NaN,NaN,NaN,NaN,No,False,I don't know,Not applicable to me,Not applicable to me,No,4,Maybe,It depends on its applicability to my job and ...,No,The stigma attached to mental health and not k...,False,NaN,NaN,4,Maybe/Not sure,NaN,"Yes, I observed",NaN,2,I think opening up more conversation around th...,Thank you,True,27,Male,United States of America,Illinois,White,United States of America,Illinois
3,False,100-500,True,True,I don't know,No,Yes,Yes,Yes,Very easy,Physical health,Yes,False,NaN,Maybe,False,NaN,True,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,I don't know,N/A (was not aware),Some did,Some did,"Yes, always",Physical health,Some of my previous supervisors,False,NaN,At some of my previous employers,False,NaN,True,NaN,3.0,1.0,No,NaN,NaN,NaN,NaN,No,False,Yes,Not applicable to me,Not applicable to me,No,3,No,discrimination/bias,No,discrimination/bias,False,NaN,NaN,8,No,NaN,"Yes, I observed",NaN,3,NaN,NaN,False,37,male,United States of America,Nebraska,White,United States of America,Nebraska
4,False,26-100,True,True,I don't know,No,I don't know,I don't know,I don't know,I don't know,Physical health,No,False,NaN,No,False,NaN,False,NaN,4.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,True,I don't know,N/A (was not aware),None did,None did,I don't know,Physical health,"No, none of my previous supervisors",False,NaN,"No, at none of my previous employers",False,NaN,False,NaN,4.0,4.0,No,NaN,NaN,NaN,NaN,No,False,No,Not applicable to me,Not applicable to me,NaN,1,No,NaN,No,NaN,False,NaN,NaN,5,No,NaN,No,NaN,3,NaN,NaN,False,46,m,United States of America,Nebraska,White,United States of America,Nebraska

In [9]:
df_2020.head()

,#,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",Would you feel more comfortable talking to your coworkers about your physical health or your mental health?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Have you ever discussed your mental health with your employer?,"Describe the conversation you had with your employer about your mental health, including their reactions and what actions were taken to address your mental health issue/questions.",Would you feel comfortable discussing a mental health issue with your coworkers?,Have you ever discussed your mental health with coworkers?,Describe the conversation with coworkers you had about your mental health including their reactions.,Have you ever had a coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names).,"Overall, how much importance does your employer place on physical health?","Overall, how much importance does your employer place on mental health?",Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?,Do you know local or online resources to seek help for a mental health issue?,"If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?","If you have revealed a mental health disorder to a client or business contact, how has this affected you or the relationship?","If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?","If you have revealed a mental health disorder to a coworker or employee, how has this impacted you or the relationship?",Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",*Do you have previous employers?*,Was your employer primarily a tech company/organization?,Have your previous employers provided mental health benefits?,Were you aware of the options for mental health care provided by your previous employers?,Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?,Did your previous employers provide resources to learn more about mental health disorders and how to seek help?,Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?,Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?,Would you have been willing to discuss your mental health with your direct supervisor(s)?,Did you ever discuss your mental health with your previous employer?,"Describe the conversation you had with your previous employer about your mental health, including their reactions and actions taken to address your mental health issue/questions.",Would you have been willing to discuss your mental health with your coworkers at previous employers?,Did you ever discuss your mental health with a previous coworker(s)?,Describe the conversation you had with your previous coworkers about your mental health including their reactions.,Did you ever have a previous coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names)..1,"Overall, how much importance did your previous employer place on physical health?","Overall, how much importance did your previous employer place on mental health?",Do you *currently* have a mental health disorder?,Have you ever been *diagnosed* with a mental health disorder?,"Anxiety Disorder (Generalized, Social, Phobia, etc)","Mood Disorder (Depression, Bipolar Disorder, etc)","Psychotic Disorder (Schizophrenia, Schizoaffective, etc)","Eating Disorder (Anorexia, Bulimia, etc)",Attention Deficit Hyperactivity Disorder,"Personality Disorder (Borderline, Antisocial, Paranoid, etc)",Obsessive-Compulsive Disorder,Post-Traumatic Stress Disorder,Stress Response Syndromes,Dissociative Disorder,Substance Use Disorder,Addictive Disorder,Other,"Anxiety Disorder (Generalized, Social, Phobia, etc).1","Mood Disorder (Depression, Bipolar Disorder, etc).1","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).1","Eating Disorder (Anorexia, Bulimia, etc).1",Attention Deficit Hyperactivity Disorder.1,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).1",Obsessive-Compulsive Disorder.1,Post-traumatic Stress Disorder,Stress Response Syndromes.1,Dissociative Disorder.1,Substance Use Disorder.1,Addictive Disorder.1,Other.1,"Anxiety Disorder (Generalized, Social, Phobia, etc).2","Mood Disorder (Depression, Bipolar Disorder, etc).2","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).2","Eating Disorder (Anorexia, Bulimia, etc).2",Attention Deficit Hyperactivity Disorder.2,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).2",Obsessive-Compulsive Disorder.2,Post-traumatic Stress Disorder.1,Stress Response Syndromes.2,Dissociative Disorder.2,Substance Use Disorder.2,Addictive Disorder.2,Other.2,Have you had a mental health disorder in the past?,Have you ever sought treatment for a mental health disorder from a mental health professional?,Do you have a family history of mental illness?,"If you have a mental health disorder, how often do you feel that it interferes with your work *when being treated effectively?*","If you have a mental health disorder, how often do you feel that it interferes with your work *when* _*NOT*_* being treated effectively (i.e., when you are experiencing symptoms)?*",Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Why or why not?,Would you bring up your *mental* health with a potential employer in an interview?,Why or why not?.1,Are you openly identified at work as a person with a mental health issue?,Has being identified as a person with a mental health issue affected your career?,How has it affected your career?,"If they knew you suffered from a mental health disorder, how do you think that your team members/co-workers would react?",Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the badly handled or unsupportive response.,Have you observed or experienced a *supportive or well handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the supportive or well handled response.,"Overall, how well do you think the tech industry supports employees with mental health issues?",Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.,"If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.",Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used _anonymously_ and only with your permission.),What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What is your race?,Other.3,What country do you *work* in?,What US state or territory do you *work* in?
0,zwrffw6ykfo82ft1twvzwrffw6c6wsfv,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"No, I don't know any","No, because it doesn't matter",NaN,"No, because it doesn't matter",I'm not sure,Yes,1-25%,1,1.0,I don't know,N/A (none offered),None did,None did,I don't know,Physical health,"No, none of my previous supervisors",0.0,NaN,At some of my previous employers,0.0,NaN,0.0,NaN,6.0,0.0,Don't Know,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Don't Know,0,Yes,Not applicable to me,Sometimes,NaN,5,Maybe,It depend on if the discussion would have an i...,Maybe,Same reason. But I believe this would have a g...,0,NaN,NaN,5,Maybe/Not sure,NaN,"Yes, I experienced",NaN,2,NaN,NaN,0,45,Male,United States of America,Connecticut,White,NaN,United States of America,Connecticut
1,zhdmhaa8r0125c4zmoi7qzhdmtjrakhm,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"Yes, I know several","Yes, always",Positively,"Yes, always",Positively,Yes,1-25%,1,1.0,"Yes, they all did","Yes, I was aware of all of them","Yes, they all did","Yes, they all did","Yes, always",Physical health,"Yes, all of my previous supervisors",1.0,NaN,"Yes, at all of my previous employers",1.0,NaN,1.0,NaN,10.0,10.0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Never,Never,Yes,10,Yes,NaN,Yes,NaN,1,1.0,10.0,10,"Yes, I observed",NaN,"Yes, I observed",NaN,5,NaN,NaN,1,24,female,Russia,NaN,NaN,NaN,Russia,NaN
2,x4itwa9hnlw7qke4y5xibx4itwa9yzl5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"No, I don't know any","No, because it would impact me negatively",Negatively,"No, because it would impact me negatively",Negatively,Yes,76-100%,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Yes,Often,Often,No,5,Maybe,It affects my employment or job,No,It affects my job,0,NaN,NaN,0,"Yes, I experienced","Some times with my boss, he will response prop...","Yes, I experienced",NaN,1,They should understand and we should talk openely,mental health should be a law by government.,1,46,Male,India,NaN,NaN,NaN,India,NaN
3,x3v3oimu5pn0043n8x3v3oizaybhwwto,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"No, I don't know any","No, because it doesn't matter",Negatively,"No, because it would impact me negatively",Negatively,Yes,1-25%,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Yes,Often,Sometimes,Yes,1,Yes,NaN,No,NaN,0,NaN,NaN,6,No,NaN,Maybe/Not sure,NaN,1,NaN,NaN,1,25,Female,Canada,NaN,NaN,NaN,Canada,NaN
4,uyp6re7bhnyx6gez09uyp6re72z0e4e4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"Yes, I know several","No, because it would impact me negatively",Negatively,"Yes, always",I'm not sure,Yes,26-50%,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Don't Know,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,I don't know,Rarely,Often,Yes,5,Yes,it will affect another person,No,it will affect my personality to the other person,0,NaN,NaN,3,"Yes, I observed",taking less to that person or ignorance,Maybe/Not sure,NaN,3,behaving well with them and give them a good t...,no,1,25,F,Canada,NaN,NaN,NaN,Canada,NaN

In [10]:
df_2021.head()

,#,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",Would you feel more comfortable talking to your coworkers about your physical health or your mental health?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Have you ever discussed your mental health with your employer?,"Describe the conversation you had with your employer about your mental health, including their reactions and what actions were taken to address your mental health issue/questions.",Would you feel comfortable discussing a mental health issue with your coworkers?,Have you ever discussed your mental health with coworkers?,Describe the conversation with coworkers you had about your mental health including their reactions.,Have you ever had a coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names).,"Overall, how much importance does your employer place on physical health?","Overall, how much importance does your employer place on mental health?",Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?,Do you know local or online resources to seek help for a mental health issue?,"If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?","If you have revealed a mental health disorder to a client or business contact, how has this affected you or the relationship?","If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?","If you have revealed a mental health disorder to a coworker or employee, how has this impacted you or the relationship?",Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",*Do you have previous employers?*,Was your employer primarily a tech company/organization?,Have your previous employers provided mental health benefits?,Were you aware of the options for mental health care provided by your previous employers?,Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?,Did your previous employers provide resources to learn more about mental health disorders and how to seek help?,Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?,Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?,Would you have been willing to discuss your mental health with your direct supervisor(s)?,Did you ever discuss your mental health with your previous employer?,"Describe the conversation you had with your previous employer about your mental health, including their reactions and actions taken to address your mental health issue/questions.",Would you have been willing to discuss your mental health with your coworkers at previous employers?,Did you ever discuss your mental health with a previous coworker(s)?,Describe the conversation you had with your previous coworkers about your mental health including their reactions.,Did you ever have a previous coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names)..1,"Overall, how much importance did your previous employer place on physical health?","Overall, how much importance did your previous employer place on mental health?",Do you *currently* have a mental health disorder?,Have you ever been *diagnosed* with a mental health disorder?,"Anxiety Disorder (Generalized, Social, Phobia, etc)","Mood Disorder (Depression, Bipolar Disorder, etc)","Psychotic Disorder (Schizophrenia, Schizoaffective, etc)","Eating Disorder (Anorexia, Bulimia, etc)",Attention Deficit Hyperactivity Disorder,"Personality Disorder (Borderline, Antisocial, Paranoid, etc)",Obsessive-Compulsive Disorder,Post-Traumatic Stress Disorder,Stress Response Syndromes,Dissociative Disorder,Substance Use Disorder,Addictive Disorder,Other,"Anxiety Disorder (Generalized, Social, Phobia, etc).1","Mood Disorder (Depression, Bipolar Disorder, etc).1","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).1","Eating Disorder (Anorexia, Bulimia, etc).1",Attention Deficit Hyperactivity Disorder.1,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).1",Obsessive-Compulsive Disorder.1,Post-traumatic Stress Disorder,Stress Response Syndromes.1,Dissociative Disorder.1,Substance Use Disorder.1,Addictive Disorder.1,Other.1,"Anxiety Disorder (Generalized, Social, Phobia, etc).2","Mood Disorder (Depression, Bipolar Disorder, etc).2","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).2","Eating Disorder (Anorexia, Bulimia, etc).2",Attention Deficit Hyperactivity Disorder.2,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).2",Obsessive-Compulsive Disorder.2,Post-traumatic Stress Disorder.1,Stress Response Syndromes.2,Dissociative Disorder.2,Substance Use Disorder.2,Addictive Disorder.2,Other.2,Have you had a mental health disorder in the past?,Have you ever sought treatment for a mental health disorder from a mental health professional?,Do you have a family history of mental illness?,"If you have a mental health disorder, how often do you feel that it interferes with your work *when being treated effectively?*","If you have a mental health disorder, how often do you feel that it interferes with your work *when* _*NOT*_* being treated effectively (i.e., when you are experiencing symptoms)?*",Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Why or why not?,Would you bring up your *mental* health with a potential employer in an interview?,Why or why not?.1,Are you openly identified at work as a person with a mental health issue?,Has being identified as a person with a mental health issue affected your career?,How has it affected your career?,"If they knew you suffered from a mental health disorder, how do you think that your team members/co-workers would react?",Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the badly handled or unsupportive response.,Have you observed or experienced a *supportive or well handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the supportive or well handled response.,"Overall, how well do you think the tech industry supports employees with mental health issues?",Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.,"If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.",Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used _anonymously_ and only with your permission.),What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What is your race?,Other.3,What country do you *work* in?,What US state or territory do you *work* in?,Have you been diagnosed with COVID-19?,Start Date (UTC),Submit Date (UTC),Network ID
0,eu6sxt9r6pyxxykpxcqs6r2qeu6sxt9r,0,26-100,1.0,1.0,I don't know,No,No,I don't know,I don't know,Very easy,Physical health,Maybe,0.0,NaN,No,0.0,NaN,0.0,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0,Some did,"Yes, I was aware of all of them",Some did,Some did,"Yes, always",Mental health,Some of my previous supervisors,0.0,NaN,"Yes, at all of my previous employers",1.0,NaN,1.0,NaN,8.0,10.0,Possibly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Possibly,0,I don't know,Not applicable to me,Not applicable to me,No,2,Yes,physical health issues often are not stigmatiz...,No,mental health issues are stigmatized and seen ...,0,NaN,NaN,4,No,NaN,No,NaN,2,NaN,NaN,1,28,Female,United States of America,Alaska,White,NaN,United States of America,Alaska,NaN,2021-12-16 20:28:29,2021-12-16 20:36:02,f3adc1b78a
1,mqgsjpmc31k0fuymqgv96vapalozx3q0,0,500-1000,1.0,1.0,Yes,No,Yes,Yes,Yes,I don't know,Physical health,No,0.0,NaN,Maybe,0.0,NaN,1.0,NaN,9.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,Some did,I was aware of some,None did,Some did,I don't know,Physical health,"No, none of my previous supervisors",1.0,NaN,"No, at none of my previous employers",0.0,NaN,0.0,NaN,7.0,8.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,No,Not applicable to me,Not applicable to me,Yes,10,Maybe,NaN,No,NaN,0,NaN,NaN,8,"Yes, I observed",NaN,"Yes, I observed",NaN,3,NaN,NaN,1,41,male,Brazil,NaN,NaN,NaN,Brazil,NaN,NaN,2021-12-16 13:42:51,2021-12-16 18:44:40,49a51b7ac1
2,fkuijv5hpifz4fusbn1fkuib4ipqt19s,0,100-500,1.0,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,Maybe,0.0,NaN,Yes,1.0,Something about been stressed about deadlines,1.0,Same as my answer,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,"Yes, they all did","Yes, I was aware of all of them",None did,None did,I don't know,Same level of comfort for each,"No, none of my previous supervisors",0.0,NaN,At some of my previous employers,0.0,NaN,0.0,NaN,5.0,3.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,0,No,Not applicable to me,Not applicable to me,NaN,5,Maybe,if it doesn't affect my ability to do the job,Maybe,if it doesn't affect my chance of getting the job,0,NaN,NaN,8,No,NaN,Maybe/Not sure,NaN,3,discuss the topic openly,NaN,0,35,Male,Brazil,NaN,NaN,NaN,Brazil,NaN,NaN,2021-12-16 13:01:19,2021-12-16 13:14:49,f9e26fd31a
3,eb7i5ye61yizgs5veb7i5yyttqp5zwp2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"No, I don't know any","No, because it doesn't matter",I'm not sure,"No, because it doesn't matter",Not applicable to me,No,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Don't Know,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Don't Know,0,Yes,Sometimes,Sometimes,NaN,1,No,uikjgiu,Maybe,kjhn,0,NaN,NaN,1,Maybe/Not sure,NaN,"Yes, I observed",NaN,2,lk,j,0,20,male,Italy,NaN,NaN,NaN,Italy,NaN,NaN,2021-12-16 08:57:11,2021-12-16 08:59:00,73a0e1b4c5
4,0qoaw3bb3kzbb2oet0qoa3xc3yzdrvva,0,More than 1000,0.0,1.0,Yes,No,Yes,Yes,I don't know,Difficult,Physical health,No,0.0,NaN,Maybe,0.0,NaN,0.0,NaN,10.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.0,"Yes, they all did","Yes, I was aware of all of them","Yes, they all did","Yes, they all did","Yes, always",Physical health,Some of my previous supervisors,0.0,NaN,At some of my previous employers,1.0,understandable,1.0,NaN,8.0,8.0,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,No,Rarely,Often,Maybe,8,No,NaN,No,NaN,0,NaN,NaN,5,No,NaN,Maybe/Not sure,NaN,3,NaN,NaN,1,35,female,Canada,NaN,NaN,NaN,Canada,NaN,NaN,2021-12-08 14:35:27,2021-12-08 14:44:10,bade27e84d

In [11]:
df_2022.head()

,#,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",Would you feel more comfortable talking to your coworkers about your physical health or your mental health?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Have you ever discussed your mental health with your employer?,"Describe the conversation you had with your employer about your mental health, including their reactions and what actions were taken to address your mental health issue/questions.",Would you feel comfortable discussing a mental health issue with your coworkers?,Have you ever discussed your mental health with coworkers?,Describe the conversation with coworkers you had about your mental health including their reactions.,Have you ever had a coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names).,"Overall, how much importance does your employer place on physical health?","Overall, how much importance does your employer place on mental health?",Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?,Do you know local or online resources to seek help for a mental health issue?,"If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?","If you have revealed a mental health disorder to a client or business contact, how has this affected you or the relationship?","If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?","If you have revealed a mental health disorder to a coworker or employee, how has this impacted you or the relationship?",Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",*Do you have previous employers?*,Was your employer primarily a tech company/organization?,Have your previous employers provided mental health benefits?,Were you aware of the options for mental health care provided by your previous employers?,Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?,Did your previous employers provide resources to learn more about mental health disorders and how to seek help?,Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?,Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?,Would you have been willing to discuss your mental health with your direct supervisor(s)?,Did you ever discuss your mental health with your previous employer?,"Describe the conversation you had with your previous employer about your mental health, including their reactions and actions taken to address your mental health issue/questions.",Would you have been willing to discuss your mental health with your coworkers at previous employers?,Did you ever discuss your mental health with a previous coworker(s)?,Describe the conversation you had with your previous coworkers about your mental health including their reactions.,Did you ever have a previous coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names)..1,"Overall, how much importance did your previous employer place on physical health?","Overall, how much importance did your previous employer place on mental health?",Do you *currently* have a mental health disorder?,Have you ever been *diagnosed* with a mental health disorder?,"Anxiety Disorder (Generalized, Social, Phobia, etc)","Mood Disorder (Depression, Bipolar Disorder, etc)","Psychotic Disorder (Schizophrenia, Schizoaffective, etc)","Eating Disorder (Anorexia, Bulimia, etc)",Attention Deficit Hyperactivity Disorder,"Personality Disorder (Borderline, Antisocial, Paranoid, etc)",Obsessive-Compulsive Disorder,Post-Traumatic Stress Disorder,Stress Response Syndromes,Dissociative Disorder,Substance Use Disorder,Addictive Disorder,Other,"Anxiety Disorder (Generalized, Social, Phobia, etc).1","Mood Disorder (Depression, Bipolar Disorder, etc).1","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).1","Eating Disorder (Anorexia, Bulimia, etc).1",Attention Deficit Hyperactivity Disorder.1,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).1",Obsessive-Compulsive Disorder.1,Post-traumatic Stress Disorder,Stress Response Syndromes.1,Dissociative Disorder.1,Substance Use Disorder.1,Addictive Disorder.1,Other.1,"Anxiety Disorder (Generalized, Social, Phobia, etc).2","Mood Disorder (Depression, Bipolar Disorder, etc).2","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).2","Eating Disorder (Anorexia, Bulimia, etc).2",Attention Deficit Hyperactivity Disorder.2,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).2",Obsessive-Compulsive Disorder.2,Post-traumatic Stress Disorder.1,Stress Response Syndromes.2,Dissociative Disorder.2,Substance Use Disorder.2,Addictive Disorder.2,Other.2,Have you had a mental health disorder in the past?,Have you ever sought treatment for a mental health disorder from a mental health professional?,Do you have a family history of mental illness?,"If you have a mental health disorder, how often do you feel that it interferes with your work *when being treated effectively?*","If you have a mental health disorder, how often do you feel that it interferes with your work *when* _*NOT*_* being treated effectively (i.e., when you are experiencing symptoms)?*",Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Why or why not?,Would you bring up your *mental* health with a potential employer in an interview?,Why or why not?.1,Are you openly identified at work as a person with a mental health issue?,Has being identified as a person with a mental health issue affected your career?,How has it affected your career?,"If they knew you suffered from a mental health disorder, how do you think that your team members/co-workers would react?",Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the badly handled or unsupportive response.,Have you observed or experienced a *supportive or well handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the supportive or well handled response.,"Overall, how well do you think the tech industry supports employees with mental health issues?",Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.,"If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.",Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used _anonymously_ and only with your permission.),What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What is your race?,Other.3,What country do you *work* in?,What US state or territory do you *work* in?,Have you been diagnosed with COVID-19?,Response Type,Start Date (UTC),Submit Date (UTC),Network ID,Tags
0,454yabpvj5ekod27qm454yabpu6ww4fa,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"Yes, I know several","No, because it would impact me negatively",I'm not sure,"No, because it would impact me negatively",I'm not sure,Yes,26-50%,1,1.0,"No, none did",N/A (none offered),None did,None did,I don't know,Physical health,"No, none of my previous supervisors",0.0,NaN,"No, at none of my previous employers",1.0,"It felt awkward, so I tried to make it sound l...",1.0,NaN,8.0,2.0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,NaN,NaN,Obsessive-Compulsive Disorder,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,I don't know,Sometimes,Often,Yes,4,No,NaN,No,NaN,0,NaN,NaN,2,"Yes, I observed",I had a panic attack and was blamed for it,Maybe/Not sure,NaN,2,I've only seen MH benefits offers in large com...,NaN,0,23,female,Russia,NaN,NaN,NaN,Russia,NaN,NaN,completed,2022-12-25 13:04:39,2022-12-25 13:12:15,16f9edd3e7,NaN
1,turfs5uwaygy96omjyvmxturfaq4tqpm,0,26-100,1.0,1.0,I don't know,No,No,No,I don't know,Very easy,Physical health,Yes,1.0,I had a burnout (another after 10 years) due t...,Yes,1.0,I told my colleague about my adhd and depressi...,0.0,NaN,8.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,Some did,N/A (was not aware),Some did,Some did,I don't know,Physical health,Some of my previous supervisors,1.0,Same as my current employer.,At some of my previous employers,0.0,NaN,0.0,NaN,8.0,5.0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Attention Deficit Hyperactivity Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Sometimes,Often,NaN,8,Yes,I (know) believe you should be honest about it...,Yes,I (know) believe you should be honest about it...,0,NaN,NaN,9,"Yes, I experienced",A couple of weeks before my burnout and callin...,"Yes, I observed",NaN,3,"Talk about it, show employees what you can do ...",NaN,1,43,Male,Netherlands,NaN,NaN,NaN,Netherlands,NaN,NaN,completed,2022-12-21 17:47:17,2022-12-21 18:09:51,af98dee606,NaN
2,1hb89b2fyz03jg1hdvv3unu46hmug4lb,0,26-100,1.0,1.0,No,Yes,I don't know,I don't know,Yes,Somewhat easy,Physical health,Yes,0.0,NaN,Maybe,0.0,NaN,1.0,NaN,6.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,Some did,I was aware of some,Some did,Some did,"Yes, always",Physical health,Some of my previous supervisors,0.0,NaN,At some of my previous employers,0.0,NaN,1.0,NaN,6.0,4.0,Possibly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Sometimes,Sometimes,Maybe,4,No,NaN,No,NaN,0,NaN,NaN,5,Maybe/Not sure,NaN,Maybe/Not sure,NaN,3,NaN,NaN,0,38,male,Sweden,NaN,NaN,NaN,Sweden,NaN,NaN,completed,2022-12-14 12:40:16,2022-12-14 12:48:02,e223d877cb,NaN
3,88shtlfnzinq2nrbw1ib88shju9q7xxh,0,More than 1000,1.0,1.0,Yes,Yes,Yes,Yes,I don't know,I don't know,Physical health,Maybe,1.0,I mentioned that I have social anxiety and tha...,No,0.0,NaN,0.0,NaN,6.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,"Yes, they all did",I was aware of some,None did,None did,I don't know,Physical health,Some of my previous supervisors,0.0,NaN,At some of my previous employers,1.0,I had a coworker who was a close friend when I...,1.0,NaN,4.0,1.0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Sometimes,Often,Yes,9,Maybe,Concern that the employer will think about how...,No,I don't want to be seen as difficult before I'...,0,NaN,NaN,4,"Yes, I experienced",NaN,"Yes, I experienced",NaN,2,Assume good intentions from employees. Assume ...,NaN,0,35,Female,United States of America,Oregon,White,NaN,United States of America,Oregon,NaN,completed,2022-12-07 15:46:30,2022-12-07 16:25:24,b2e27a741e,NaN
4,8y9n53igp152mvon6woisdiq8y9n53ig,0,26-100,1.0,1.0,Yes,No,Yes,Yes,Yes,Very easy,Same level of comfort for each,Yes,1.0,"I told them I was struggling, that was it, the...",Yes,1.0,Happened too many times for me to remember jus...,1.0,Happened too many times to recall,5.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1.0,Some did,I was aware of some,Some did,Some did,Sometimes,Same level of comfort for each,Some of my previous supervisors,0.0,NaN,"Yes, at all of my previous employers",1.0,Just general chit chat,1.0,General chat,5.0,5.0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,Attention Deficit Hyperactivity Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Rarely,Often,No,10,No,Don't want to be discriminated against,No,Don't want to be discriminated against,1,0.0,NaN,10,No,NaN,Maybe/Not sure,NaN,1,Capitalism damages mental health and all compa...,NaN,0,33,Female,United Kingdom,NaN,NaN,NaN,United Kingdom,NaN,NaN,completed,2022-12-01 12:23:51,2022-12-01 12:33:14,1d324732b0,NaN

In [12]:
df_2023.head()

,#,*Are you self-employed?*,How many employees does your company or organization have?,Is your employer primarily a tech company/organization?,Is your primary role within your company related to tech/IT?,Does your employer provide mental health benefits as part of healthcare coverage?,Do you know the options for mental health care available under your employer-provided health coverage?,"Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?",Does your employer offer resources to learn more about mental health disorders and options for seeking help?,Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?,"If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?",Would you feel more comfortable talking to your coworkers about your physical health or your mental health?,Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?,Have you ever discussed your mental health with your employer?,"Describe the conversation you had with your employer about your mental health, including their reactions and what actions were taken to address your mental health issue/questions.",Would you feel comfortable discussing a mental health issue with your coworkers?,Have you ever discussed your mental health with coworkers?,Describe the conversation with coworkers you had about your mental health including their reactions.,Have you ever had a coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names).,"Overall, how much importance does your employer place on physical health?","Overall, how much importance does your employer place on mental health?",Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?,Do you know local or online resources to seek help for a mental health issue?,"If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?","If you have revealed a mental health disorder to a client or business contact, how has this affected you or the relationship?","If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?","If you have revealed a mental health disorder to a coworker or employee, how has this impacted you or the relationship?",Do you believe your productivity is ever affected by a mental health issue?,"If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?",*Do you have previous employers?*,Was your employer primarily a tech company/organization?,Have your previous employers provided mental health benefits?,Were you aware of the options for mental health care provided by your previous employers?,Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?,Did your previous employers provide resources to learn more about mental health disorders and how to seek help?,Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?,Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?,Would you have been willing to discuss your mental health with your direct supervisor(s)?,Did you ever discuss your mental health with your previous employer?,"Describe the conversation you had with your previous employer about your mental health, including their reactions and actions taken to address your mental health issue/questions.",Would you have been willing to discuss your mental health with your coworkers at previous employers?,Did you ever discuss your mental health with a previous coworker(s)?,Describe the conversation you had with your previous coworkers about your mental health including their reactions.,Did you ever have a previous coworker discuss their or another coworker's mental health with you?,Describe the conversation your coworker had with you about their mental health (please do not use names)..1,"Overall, how much importance did your previous employer place on physical health?","Overall, how much importance did your previous employer place on mental health?",Do you *currently* have a mental health disorder?,Have you ever been *diagnosed* with a mental health disorder?,"Anxiety Disorder (Generalized, Social, Phobia, etc)","Mood Disorder (Depression, Bipolar Disorder, etc)","Psychotic Disorder (Schizophrenia, Schizoaffective, etc)","Eating Disorder (Anorexia, Bulimia, etc)",Attention Deficit Hyperactivity Disorder,"Personality Disorder (Borderline, Antisocial, Paranoid, etc)",Obsessive-Compulsive Disorder,Post-Traumatic Stress Disorder,Stress Response Syndromes,Dissociative Disorder,Substance Use Disorder,Addictive Disorder,Other,"Anxiety Disorder (Generalized, Social, Phobia, etc).1","Mood Disorder (Depression, Bipolar Disorder, etc).1","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).1","Eating Disorder (Anorexia, Bulimia, etc).1",Attention Deficit Hyperactivity Disorder.1,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).1",Obsessive-Compulsive Disorder.1,Post-traumatic Stress Disorder,Stress Response Syndromes.1,Dissociative Disorder.1,Substance Use Disorder.1,Addictive Disorder.1,Other.1,"Anxiety Disorder (Generalized, Social, Phobia, etc).2","Mood Disorder (Depression, Bipolar Disorder, etc).2","Psychotic Disorder (Schizophrenia, Schizoaffective, etc).2","Eating Disorder (Anorexia, Bulimia, etc).2",Attention Deficit Hyperactivity Disorder.2,"Personality Disorder (Borderline, Antisocial, Paranoid, etc).2",Obsessive-Compulsive Disorder.2,Post-traumatic Stress Disorder.1,Stress Response Syndromes.2,Dissociative Disorder.2,Substance Use Disorder.2,Addictive Disorder.2,Other.2,Have you had a mental health disorder in the past?,Have you ever sought treatment for a mental health disorder from a mental health professional?,Do you have a family history of mental illness?,"If you have a mental health disorder, how often do you feel that it interferes with your work *when being treated effectively?*","If you have a mental health disorder, how often do you feel that it interferes with your work *when* _*NOT*_* being treated effectively (i.e., when you are experiencing symptoms)?*",Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?,How willing would you be to share with friends and family that you have a mental illness?,Would you be willing to bring up a physical health issue with a potential employer in an interview?,Why or why not?,Would you bring up your *mental* health with a potential employer in an interview?,Why or why not?.1,Are you openly identified at work as a person with a mental health issue?,Has being identified as a person with a mental health issue affected your career?,How has it affected your career?,"If they knew you suffered from a mental health disorder, how do you think that your team members/co-workers would react?",Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the badly handled or unsupportive response.,Have you observed or experienced a *supportive or well handled response* to a mental health issue in your current or previous workplace?,Describe the circumstances of the supportive or well handled response.,"Overall, how well do you think the tech industry supports employees with mental health issues?",Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.,"If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.",Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used _anonymously_ and only with your permission.),What is your age?,What is your gender?,What country do you *live* in?,What US state or territory do you *live* in?,What is your race?,Other.3,What country do you *work* in?,What US state or territory do you *work* in?,Have you been diagnosed with COVID-19?,Response Type,Start Date (UTC),Submit Date (UTC),Network ID,Tags
0,an587p4oi8h7gtq9an5874mxwixvx5p6,0,26-100,1.0,0.0,No,No,No,No,Yes,Somewhat easy,Mental health,Maybe,1.0,They appeared to be ok with my weekly therapy ...,Yes,1.0,Indifference,0.0,NaN,4.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,Some did,"No, I only became aware later",None did,None did,Sometimes,Same level of comfort for each,Some of my previous supervisors,1,I had weekly in-person sessions pre-COVID and ...,At some of my previous employers,1,"My teammates also lived with a mental illness,...",1,Understanding. Active listening. Empathy.,0,0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,Attention Deficit Hyperactivity Disorder,NaN,NaN,Post-traumatic Stress Disorder,NaN,NaN,NaN,NaN,NaN,Yes,1,I don't know,Sometimes,Often,No,4,Maybe,Although employers say they don't have biases ...,No,"Since I was ""quiet fired"" from my previous emp...",1,1.0,3.0,3,"Yes, I experienced","When I put in my request for STD, I experience...","Yes, I experienced",NaN,2,Add additional mental health resources to heal...,NaN,1,40,Female,United States of America,Colorado,More than one of the above,NaN,United States of America,Colorado,NaN,completed,2023-03-03 22:04:39,2023-03-05 23:50:09,6dde6a8348,NaN
1,2pivyqqnhwt0b7lp2pivythv3eonu6me,0,6-25,1.0,1.0,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,No,0.0,NaN,No,0.0,NaN,0.0,NaN,5.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,Some did,I was aware of some,Some did,Some did,Sometimes,Physical health,Some of my previous supervisors,0,NaN,At some of my previous employers,0,NaN,0,NaN,5,5,Possibly,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Addictive Disorder,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,1,No,Sometimes,Sometimes,Yes,8,No,I would only bring up if I need some sort of a...,No,I'm nervous they wouldn't hire me,0,NaN,NaN,1,Maybe/Not sure,NaN,"Yes, I observed",NaN,2,It's hard. I'm not sure how we can strike a ba...,"No, I thought this survey was interesting, and...",1,36,Male,United States of America,Indiana,White,NaN,United States of America,Indiana,NaN,completed,2023-03-02 22:20:33,2023-03-02 22:31:00,90e5ba7a6a,NaN
2,06ra2i3glzxtm8m2s06ra2z5vmep483a,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,I know some,"Sometimes, if it comes up",Negatively,"Sometimes, if it comes up",Negatively,Yes,76-100%,1,1,Some did,"No, I only became aware later",None did,Some did,No,Same level of comfort for each,Some of my previous supervisors,1,i was fired from my last full-time role at Boo...,At some of my previous employers,1,"some supportive, some went behind my back and ...",1,i had an employee who abused trust and support...,2,0,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,Attention Deficit Hyperactivity Disorder,NaN,NaN,Post-traumatic Stress Disorder,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Often,Often,NaN,10,Maybe,it depends if it may be applicable or if i con...,Maybe,i’ve been discriminated against. been fired. b...,1,1.0,0.0,3,"Yes, I experienced",see previous responses. i would have sued if I...,Maybe/Not sure,NaN,1,there is a lot of rhetoric around mental healt...,i’d like to see a scorecard or metric that rat...,1,44,male,United States of America,Maryland,White,NaN,United States of America,Maryland,NaN,completed,2023-03-02 20:45:20,2023-03-02 21:06:03,1a0014e801,NaN
3,4ojrsw9n2x8gr9wabb24ojrswr9znb1o,0,500-1000,0.0,0.0,Yes,Yes,Yes,No,I don't know,Neither easy nor difficult,Same level of comfort for each,Maybe,1.0,Explained I was struggling with anxiety and de...,Maybe,1.0,The co-worker I work with the most and I talk ...,1.0,Same as previous. My closest coworker talks to...,7.0,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0,Some did,I was aware of some,None did,Some did,I don't know,Same level of comfort for each,Some of my previous supervisors,1,Explained that I was struggling with anxiety. ...,At some of my previous employers,1,On a regular basis talking about what’s going ...,1,Same as previous answers,4,4,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Anxiety Disorder (Generalized, Social, Phobia,...","Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,1,Yes,Sometimes,Often,No,10,Maybe,Depending on what the job is and how the physi...,No,Mental health still has a stigma with a lot of...,0,NaN,NaN,7,Maybe/Not sure,NaN,Maybe/Not sure,NaN,3,Being open and upfront about mental health all...,Na,0,53,Female,United States of America,Indiana,White,NaN,United States of America,Indiana,NaN,completed,2023-03-02 17:52:57,2023-03-02 18:06:01,92ea1836e3,NaN
4,wuks4mzrqdbuqkwm8hwuks5yvhjd6p58,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,"Yes, I know several","Sometimes, if it comes up",No change,Not applicable to me,Not applicable to me,Yes,1-25%,1,0,I don't know,N/A (was not aware),Some did,Some did,"Yes, always",Same level of comfort for each,"Yes, all of my previous supervisors",1,They actually brought the subject up based on ...,At some of my previous employers,1,Just that I was struggling and wanted them to ...,0,NaN,10,8,Yes,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Mood Disorder (Depression, Bipolar Disorder, etc)",NaN,NaN,Attention Deficit Hyperactivity Disorder,NaN,Obsessive-Compulsive Disorder,NaN,NaN,NaN,NaN,Addictive Disorder,NaN,Possibly,1,No,Sometimes,Often,NaN,10,Maybe,"If they are interested in hiring me, I want th...",Maybe,See the answer for physical,0,NaN,NaN,5,No,NaN,"Yes, I experienced",NaN,5,"There is alot of media ""noise"" about it and, i...",NaN,1,62,male,United States of America,Ohio,White,NaN,United States of America,Ohio,NaN,completed,2023-03-02 13:53:59,2023-03-02 14:11:32,94b54112a3,NaN

In [13]:
print(df_2014.shape)
print(df_2016.shape)
print(df_2017.shape)
print(df_2018.shape)
print(df_2019.shape)
print(df_2020.shape)
print(df_2021.shape)
print(df_2022.shape)
print(df_2023.shape)

(1259, 27)
(1433, 63)
(756, 123)
(417, 123)
(352, 82)
(180, 120)
(131, 124)
(164, 126)
(6, 126)

In [14]:
print(df_2014.columns)
print(df_2016.columns)
print(df_2017.columns)
print(df_2018.columns)
print(df_2019.columns)
print(df_2020.columns)
print(df_2021.columns)
print(df_2022.columns)
print(df_2023.columns)

Index(['Timestamp', 'Age', 'Gender', 'Country', 'state', 'self_employed',
       'family_history', 'treatment', 'work_interfere', 'no_employees',
       'remote_work', 'tech_company', 'benefits', 'care_options',
       'wellness_program', 'seek_help', 'anonymity', 'leave',
       'mental_health_consequence', 'phys_health_consequence', 'coworkers',
       'supervisor', 'mental_health_interview', 'phys_health_interview',
       'mental_vs_physical', 'obs_consequence', 'comments'],
      dtype='object')
Index(['Are you self-employed?',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Is your primary role within your company related to tech/IT?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Do you know the options for mental health care available under your employer-provided coverage?',
       'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
       'Does your employer offer resources to learn more about mental health concerns and options for seeking help?',
       'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
       'If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:',
       'Do you think that discussing a mental health disorder with your employer would have negative consequences?',
       'Do you think that discussing a physical health issue with your employer would have negative consequences?',
       'Would you feel comfortable discussing a mental health disorder with your coworkers?',
       'Would you feel comfortable discussing a mental health disorder with your direct supervisor(s)?',
       'Do you feel that your employer takes mental health as seriously as physical health?',
       'Have you heard of or observed negative consequences for co-workers who have been open about mental health issues in your workplace?',
       'Do you have medical coverage (private insurance or state-provided) which includes treatment of  mental health issues?',
       'Do you know local or online resources to seek help for a mental health disorder?',
       'If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?',
       'If you have revealed a mental health issue to a client or business contact, do you believe this has impacted you negatively?',
       'If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?',
       'If you have revealed a mental health issue to a coworker or employee, do you believe this has impacted you negatively?',
       'Do you believe your productivity is ever affected by a mental health issue?',
       'If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?',
       'Do you have previous employers?',
       'Have your previous employers provided mental health benefits?',
       'Were you aware of the options for mental health care provided by your previous employers?',
       'Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?',
       'Did your previous employers provide resources to learn more about mental health issues and how to seek help?',
       'Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?',
       'Do you think that discussing a mental health disorder with previous employers would have negative consequences?',
       'Do you think that discussing a physical health issue with previous employers would have negative consequences?',
       'Would you have been willing to discuss a mental health issue with your previous co-workers?',
       'Would you have been willing to discuss a mental health issue with your direct supervisor(s)?',
       'Did you feel that your previous employers took mental health as seriously as physical health?',
       'Did you hear of or observe negative consequences for co-workers with mental health issues in your previous workplaces?',
       'Would you be willing to bring up a physical health issue with a potential employer in an interview?',
       'Why or why not?',
       'Would you bring up a mental health issue with a potential employer in an interview?',
       'Why or why not?.1',
       'Do you feel that being identified as a person with a mental health issue would hurt your career?',
       'Do you think that team members/co-workers would view you more negatively if they knew you suffered from a mental health issue?',
       'How willing would you be to share with friends and family that you have a mental illness?',
       'Have you observed or experienced an unsupportive or badly handled response to a mental health issue in your current or previous workplace?',
       'Have your observations of how another individual who discussed a mental health disorder made you less likely to reveal a mental health issue yourself in your current workplace?',
       'Do you have a family history of mental illness?',
       'Have you had a mental health disorder in the past?',
       'Do you currently have a mental health disorder?',
       'If yes, what condition(s) have you been diagnosed with?',
       'If maybe, what condition(s) do you believe you have?',
       'Have you been diagnosed with a mental health condition by a medical professional?',
       'If so, what condition(s) were you diagnosed with?',
       'Have you ever sought treatment for a mental health issue from a mental health professional?',
       'If you have a mental health issue, do you feel that it interferes with your work when being treated effectively?',
       'If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?',
       'What is your age?', 'What is your gender?',
       'What country do you live in?',
       'What US state or territory do you live in?',
       'What country do you work in?',
       'What US state or territory do you work in?',
       'Which of the following best describes your work position?',
       'Do you work remotely?'],
      dtype='object')
Index(['#', '<strong>Are you self-employed?</strong>',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Is your primary role within your company related to tech/IT?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Do you know the options for mental health care available under your employer-provided health coverage?',
       'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
       'Does your employer offer resources to learn more about mental health disorders and options for seeking help?',
       'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
       ...
       'What is your gender?', 'What country do you <strong>live</strong> in?',
       'What US state or territory do you <strong>live</strong> in?',
       'What is your race?', 'Other.3',
       'What country do you <strong>work</strong> in?',
       'What US state or territory do you <strong>work</strong> in?',
       'Start Date (UTC)', 'Submit Date (UTC)', 'Network ID'],
      dtype='object', length=123)
Index(['#', '<strong>Are you self-employed?</strong>',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Is your primary role within your company related to tech/IT?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Do you know the options for mental health care available under your employer-provided health coverage?',
       'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
       'Does your employer offer resources to learn more about mental health disorders and options for seeking help?',
       'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
       ...
       'What is your gender?', 'What country do you <strong>live</strong> in?',
       'What US state or territory do you <strong>live</strong> in?',
       'What is your race?', 'Other.3',
       'What country do you <strong>work</strong> in?',
       'What US state or territory do you <strong>work</strong> in?',
       'Start Date (UTC)', 'Submit Date (UTC)', 'Network ID'],
      dtype='object', length=123)
Index(['*Are you self-employed?*',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Is your primary role within your company related to tech/IT?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Do you know the options for mental health care available under your employer-provided health coverage?',
       'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
       'Does your employer offer resources to learn more about mental health disorders and options for seeking help?',
       'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
       'If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?',
       'Would you feel more comfortable talking to your coworkers about your physical health or your mental health?',
       'Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?',
       'Have you ever discussed your mental health with your employer?',
       'Describe the conversation you had with your employer about your mental health, including their reactions and what actions were taken to address your mental health issue/questions.',
       'Would you feel comfortable discussing a mental health issue with your coworkers?',
       'Have you ever discussed your mental health with coworkers?',
       'Describe the conversation with coworkers you had about your mental health including their reactions.',
       'Have you ever had a coworker discuss their or another coworker's mental health with you?',
       'Describe the conversation your coworker had with you about their mental health (please do not use names).',
       'Overall, how much importance does your employer place on physical health?',
       'Overall, how much importance does your employer place on mental health?',
       'Do you have medical coverage (private insurance or state-provided) that includes treatment of mental health disorders?',
       'Do you know local or online resources to seek help for a mental health issue?',
       'If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to clients or business contacts?',
       'If you have revealed a mental health disorder to a client or business contact, how has this affected you or the relationship?',
       'If you have been diagnosed or treated for a mental health disorder, do you ever reveal this to coworkers or employees?',
       'If you have revealed a mental health disorder to a coworker or employee, how has this impacted you or the relationship?',
       'Do you believe your productivity is ever affected by a mental health issue?',
       'If yes, what percentage of your work time (time performing primary or secondary job functions) is affected by a mental health issue?',
       '*Do you have previous employers?*',
       'Was your employer primarily a tech company/organization?',
       'Have your previous employers provided mental health benefits?',
       'Were you aware of the options for mental health care provided by your previous employers?',
       'Did your previous employers ever formally discuss mental health (as part of a wellness campaign or other official communication)?',
       'Did your previous employers provide resources to learn more about mental health disorders and how to seek help?',
       'Was your anonymity protected if you chose to take advantage of mental health or substance abuse treatment resources with previous employers?',
       'Would you have felt more comfortable talking to your previous employer about your physical health or your mental health?',
       'Would you have been willing to discuss your mental health with your direct supervisor(s)?',
       'Did you ever discuss your mental health with your previous employer?',
       'Describe the conversation you had with your previous employer about your mental health, including their reactions and actions taken to address your mental health issue/questions.',
       'Would you have been willing to discuss your mental health with your coworkers at previous employers?',
       'Did you ever discuss your mental health with a previous coworker(s)?',
       'Describe the conversation you had with your previous coworkers about your mental health including their reactions.',
       'Did you ever have a previous coworker discuss their or another coworker's mental health with you?',
       'Describe the conversation your coworker had with you about their mental health (please do not use names)..1',
       'Overall, how much importance did your previous employer place on physical health?',
       'Overall, how much importance did your previous employer place on mental health?',
       'Do you *currently* have a mental health disorder?',
       'Have you ever been *diagnosed* with a mental health disorder?',
       '*What disorder(s) have you been diagnosed with?*',
       '*If possibly, what disorder(s) do you believe you have?*',
       '*If so, what disorder(s) were you diagnosed with?*',
       'Have you had a mental health disorder in the past?',
       'Have you ever sought treatment for a mental health disorder from a mental health professional?',
       'Do you have a family history of mental illness?',
       'If you have a mental health disorder, how often do you feel that it interferes with your work *when being treated effectively?*',
       'If you have a mental health disorder, how often do you feel that it interferes with your work *when* _*NOT*_* being treated effectively (i.e., when you are experiencing symptoms)?*',
       'Have your observations of how another individual who discussed a mental health issue made you less likely to reveal a mental health issue yourself in your current workplace?',
       'How willing would you be to share with friends and family that you have a mental illness?',
       'Would you be willing to bring up a physical health issue with a potential employer in an interview?',
       'Why or why not?',
       'Would you bring up your *mental* health with a potential employer in an interview?',
       'Why or why not?.1',
       'Are you openly identified at work as a person with a mental health issue?',
       'Has being identified as a person with a mental health issue affected your career?',
       'How has it affected your career?',
       'If they knew you suffered from a mental health disorder, how do you think that your team members/co-workers would react?',
       'Have you observed or experienced an *unsupportive or badly handled response* to a mental health issue in your current or previous workplace?',
       'Describe the circumstances of the badly handled or unsupportive response.',
       'Have you observed or experienced a *supportive or well handled response* to a mental health issue in your current or previous workplace?',
       'Describe the circumstances of the supportive or well handled response.',
       'Overall, how well do you think the tech industry supports employees with mental health issues?',
       'Briefly describe what you think the industry as a whole and/or employers could do to improve mental health support for employees.',
       'If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.',
       'Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used _anonymously_ and only with your permission.)',
       'What is your age?', 'What is your gender?',
       'What country do you *live* in?',
       'What US state or territory do you *live* in?', 'What is your race?',
       'What country do you *work* in?',
       'What US state or territory do you *work* in?'],
      dtype='object')
Index(['#', '*Are you self-employed?*',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Is your primary role within your company related to tech/IT?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Do you know the options for mental health care available under your employer-provided health coverage?',
       'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
       'Does your employer offer resources to learn more about mental health disorders and options for seeking help?',
       'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
       ...
       'If there is anything else you would like to tell us that has not been covered by the survey questions, please use this space to do so.',
       'Would you be willing to talk to one of us more extensively about your experiences with mental health issues in the tech industry? (Note that all interview responses would be used _anonymously_ and only with your permission.)',
       'What is your age?', 'What is your gender?',
       'What country do you *live* in?',
       'What US state or territory do you *live* in?', 'What is your race?',
       'Other.3', 'What country do you *work* in?',
       'What US state or territory do you *work* in?'],
      dtype='object', length=120)
Index(['#', '*Are you self-employed?*',
       'How many employees does your company or organization have?',
       'Is your employer primarily a tech company/organization?',
       'Is your primary role within your company related to tech/IT?',
       'Does your employer provide mental health benefits as part of healthcare coverage?',
       'Do you know the options for mental health care available under your employer-provided health coverage?',
       'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?',
       'Does your employer offer resources to learn more about mental health disorders and options for seeking help?',
       'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?',
       ...
       'What country do you *live* in?',
       'What US state or territory do you *live* in?', 'What is your race?',
       'Other.3', 'What country do you *work* in?',
       'What US state or territory do you *work* in?',

### Data Cleaning & Preprocessing

##### Merged datasets from multiple years into a single dataframe and standardized column names. 
##### This step also included:
> ##### Handling missing values
> ##### Standardizing responses for key columns (e.g., gender, country)
> ##### Removing invalid ages
> ##### Creating consistent categorical features across years

In [15]:
column_mapping = {
    # -------- 2014 --------
    'Age': 'age',
    'Gender': 'gender',
    'Country': 'country',
    'self_employed': 'self_employed',
    'family_history': 'family_history',
    'treatment': 'treatment',
    'work_interfere': 'work_interfere',
    'no_employees': 'no_employees',
    'tech_company': 'tech_company',
    'benefits': 'benefits',
    'care_options': 'care_options',
    'wellness_program': 'wellness_program',
    'seek_help': 'seek_help',
    'anonymity': 'anonymity',
    'leave': 'leave',
    
    # -------- 2016 --------
    'Do you work remotely?':'remote_work',
    'What US state or territory do you live in?':'state',
    'What is your age?': 'age',
    'What is your gender?': 'gender',
    'What country do you live in?': 'country',
    'Are you self-employed?': 'self_employed',
    'Do you have a family history of mental illness?': 'family_history',
    'Have you ever sought treatment for a mental health issue from a mental health professional?': 'treatment',
    'How many employees does your company or organization have?': 'no_employees',
    'Is your employer primarily a tech company/organization?': 'tech_company',
    'Does your employer provide mental health benefits as part of healthcare coverage?': 'benefits',
    'Do you know the options for mental health care available under your employer-provided coverage?': 'care_options',
    'Has your employer ever formally discussed mental health (for example, as part of a wellness campaign or other official communication)?': 'wellness_program',
    'Does your employer offer resources to learn more about mental health concerns and options for seeking help?': 'seek_help',
    'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?': 'anonymity',
    'If a mental health issue prompted you to request a medical leave from work, asking for that leave would be:': 'leave',
    'If you have a mental health issue, do you feel that it interferes with your work when NOT being treated effectively?': 'work_interfere',

    # -------- 2017+ --------
    'Does your employer provide mental health benefits as part of healthcare coverage?': 'benefits',
    'What US state or territory do you <strong>live</strong> in?':'state',
    '<strong>Are you self-employed?</strong>': 'self_employed',
    'Is your anonymity protected if you choose to take advantage of mental health or substance abuse treatment resources provided by your employer?':'anonymity',
    'Have you ever sought treatment for a mental health disorder from a mental health professional?': 'treatment',
    'Do you know the options for mental health care available under your employer-provided health coverage?': 'care_options',
    'Does your employer offer resources to learn more about mental health disorders and options for seeking help?': 'seek_help',
    'If a mental health issue prompted you to request a medical leave from work, how easy or difficult would it be to ask for that leave?': 'leave',
    'Would you feel comfortable discussing a mental health issue with your direct supervisor(s)?': 'work_interfere',

    # -------- 2018+ --------
    'What country do you <strong>work</strong> in?': 'country',

    # -------- 2019 - 2023 variations --------
    'What US state or territory do you *live* in?':'state',
    'What country do you *live* in?':'country',
    '*Are you self-employed?*': 'self_employed',
    'Do you have a family history of mental illness?': 'family_history',
    'Have you ever been diagnosed with a mental health condition by a medical professional?': 'treatment',
    'How many people are employed at your company?': 'no_employees',
    'Is your company primarily a tech company?': 'tech_company',
    'Does your employer provide mental health benefits?': 'benefits',
    'Are you aware of the mental health options your employer provides?': 'care_options',
    'Does your employer discuss mental health in the workplace?': 'wellness_program',
    'Does your employer offer mental health resources?': 'seek_help',
    'Is your anonymity protected when using mental health resources?': 'anonymity',
    'How easy is it to take medical leave for mental health?': 'leave',
    'How does your mental health interfere with your work?': 'work_interfere',
    'Would you be willing to discuss a mental health issue with your coworkers?':'coworkers',
    'how much importance does your employer place on mental health?':'mental_health_consequence',
    'how much importance does your employer place on physical health?':'phys_health_consequence',
    'Would you feel comfortable discussing a mental health issue with your direct supervisor?':'supervisor',
    'Would you bring up your mental health with a potential employer in an interview?':'mental_health_interview',
    'Would you feel more comfortable talking to your coworkers about your physical health or your mental health?':'mental_vs_physical'
}

In [16]:
def clean_and_standardize(df, year, mapping, target_columns):
    df = df.rename(columns={k: v for k, v in mapping.items() if k in df.columns})
    df['survey_year'] = year
    available_cols = [col for col in target_columns if col in df.columns]
    return df[available_cols + ['survey_year']]

In [17]:
target_columns = [    
    'age', 'gender', 'country', 'state', 'self_employed', 'family_history',
     'treatment', 'work_interfere', 'no_employees', 'remote_work','tech_company', 'benefits', 'care_options', 'wellness_program',
     'seek_help', 'anonymity', 'leave', 'mental_health_consequence',
     'phys_health_consequence', 'coworkers', 'supervisor',
     'mental_vs_physical', 'obs_consequence', 'comments'
]

In [18]:
df_2014_cleaned = clean_and_standardize(df_2014, 2014, column_mapping, target_columns)
df_2016_cleaned = clean_and_standardize(df_2016, 2016, column_mapping, target_columns)
df_2017_cleaned = clean_and_standardize(df_2017, 2017, column_mapping, target_columns)
df_2018_cleaned = clean_and_standardize(df_2018, 2018, column_mapping, target_columns)
df_2019_cleaned = clean_and_standardize(df_2019, 2019, column_mapping, target_columns)
df_2020_cleaned = clean_and_standardize(df_2020, 2020, column_mapping, target_columns)
df_2021_cleaned = clean_and_standardize(df_2021, 2021, column_mapping, target_columns)
df_2022_cleaned = clean_and_standardize(df_2022, 2022, column_mapping, target_columns)
df_2023_cleaned = clean_and_standardize(df_2023, 2023, column_mapping, target_columns)

In [19]:
df_2014_cleaned

              age                                          gender  \
0              37                                          Female
1              44                                               M
2              32                                            Male
3              31                                            Male
4              31                                            Male
5              33                                            Male
6              35                                          Female
7              39                                               M
8              42                                          Female
9              23                                            Male
10             31                                            Male
11             29                                            male
12             42                                          female
13             36                                            Male
14             27                                            Male
15             29                                          female
16             23                                            Male
17             32                                            Male
18             46                                            male
19             36                                            Male
20             29                                            Male
21             31                                            male
22             46                                            Male
23             41                                            Male
24             33                                            male
25             35                                            male
26             33                                            male
27             35                                          Female
28             34                                            male
29             37                                            Male
30             32                                            Male
31             31                                            Male
32             30                                            male
33             42                                            Male
34             40                                          female
35             27                                            Male
36             29                                            Male
37             38                                            Male
38             50                                               M
39             35                                               M
40             24                                            Male
41             35                                            Male
42             27                                            Male
43             18                                            Male
44             30                                            Male
45             38                                          Female
46             28                                            Male
47             34                                            Male
48             26                                               m
49             30                                            male
50             22                                               M
51             33                                            Male
52             31                                               M
53             32                                            Male
54             28                                               M
55             27                                        Male-ish
56             32                                           maile
57             24                                            Male
58             26                                            Male
59             33                                            male
60             44                                            Male
61             26                                          Female
62             27                                            Male
63             26                                            Male
64             35                                            male
65             40                                            Male
66             23                                          Female
67             36                                               M
68             31                                          Female
69             34                                            Male
70             28                                               m
71             34                                            male
72             23                                    Trans-female
73             38                                            Male
74             33                                            Male
75             19                                            Male
76             25                                            Male
77             31                                            Male
78             32                                            Male
79             28                                               m
80             38                                            Male
81             23                                            Male
82             30                                            male
83             27                                      Cis Female
84             33                                            Male
85             31                                            Male
86             39                                            Male
87             34                                          female
88             29                                               F
89             32                                               M
90             31                                            Male
91             40                                            male
92             34                                            Male
93             18                           something kinda male?
94             25                                               F
95             29                                            male
96             24                                            Male
97             31                                            male
98             33                                        Cis Male
99             30                                               M
100            26                                          female
101            44                                          Female
102            25                                            Male
103            33                                            Male
104            29                                            Male
105            35                                            Male
106            35                                               M
107            28                                            Male
108            34                                               m
109            32                                            Male
110            22                                            Male
111            28                                            Male
112            45                                            male
113            32                                            Male
114            28                                            male
115            26                                            Male
116            21                                            Male
117            27                                            Male
118            18                                            Male
119            35                                            Male
120            29                                            Male
121            25                                            Male
122            33                                            Male
123            36                                            Male
124            27                                            Male
125            27                                            Male
126            27                                            Male
127            32                                               M
128            31                                            Male
129            19                                            male
130            33                                            Male
131            32                                            male
132            27                                            Male
133            38                                            Male
134            24                                            Male
135            39                                               M
136            28                                            Male
137            39                                            Male
138            29                                          Female
139            22                                               m
140            38                                            Male
141            37                                            Male
142            35                                               M
143           -29                                            Male
144            30                                          Female
145            37                                            Male
146            24                                               M
147            23                                            Male
148            30                                            male
149            29                                          Female
150            19                                            Male
151            32                                            male
152            28                                            male
153            36                                            Male
154            37                                            Male
155            25                                            Male
156            27                                            Male
157            26                                            male
158            27                                            male
159            25                                            Male
160            36                                            Male
161            25                                               F
162            31                                               M
163            26                                            male
164            33                                               F
165            27                                           Woman
166            34                                            Male
167            42                                            male
168            23                                            male
169            24                                            Male
170            26                                            Male
171            31                                            Male
172            22                                               M
173            23                                          Female
174            34                                          Female
175            31                                            male
176            28                                            Male
177            32                                          Female
178            45                                               F
179            33                                            Male
180            29                                            male
181            26                                               f
182            28                                          Female
183            45                                               M
184            43                                            Male
185            37                                            male
186            24                                            Male
187            26                                            Male
188            23                                            male
189            35                                          Female
190            38                                          Female
191            28                                            Male
192            28                                            Male
193            35                                            Male
194            32                                          female
195            31                                             Mal
196            35                                          Female
197            26                                            Male
198            27                                            Male
199            28                                            Male
200            27                                          Female
201            34                                          female
202            41                                            male
203            37                                            Male
204            34                                            male
205            32                                            Male
206            21                                            Male
207            30                                               M
208            24                                            male
209            26                                            male
210            40                                          Female
211            37                                            Male
212            26                                            Male
213            32                                               F
214            32                                               f
215            27                                          female
216            30                                            Male
217            31                                               M
218            29                                               F
219            41                                      Male (CIS)
220            34                                          female
221            33                                            Male
222            28                                            male
223            28                                            Male
224            23                                            Male
225            24                                               M
226            32                                            male
227            34                                            Male
228            24                                            Male
229            26                                            male
230            36                                            Male
231            41                                            Male
232            38                                            Male
233            38                                            Male
234            30                                            male
235            25                                            Male
236            37                                            Male
237            34                                            Male
238            37                                               F
239            28                                          Female
240            22                                            Male
241            34                                            male
242            33                                               M
243            25                                            Male
244            27                                            Male
245            40                                               M
246            21                                            Male
247            29                                            Male
248            32                                               M
249            29                                               f
250            23                                            Male
251            28                                            Male
252            31                                            male
253            27                                            Male
254            24                                            Male
255            29                                            Male
256            23                                          Female
257            42                                            Male
258            24                                            Male
259            25                                            Male
260            27                                          Female
261            27                                            Male
262            30                                            Male
263            29                                            male
264            43                                            Male
265            32                                            male
266            41                                            Male
267            32                                            Male
268            37                                          Female
269            32                                            Male
270            30                                            Male
271            23                                          female
272            30                                            Male
273            34                                            male
274            38                                            Male
275            33                                            Male
276            34                                            male
277            28                                            male
278            28                                            male
279            23                                            Male
280            22                                            Male
281            27                                            male
282            18                                            male
283            35                                            male
284            25                                            Male
285            27                                            Male
286            26                                          Female
287            18                                            Male
288            38                                          Female
289            26                                          Female
290            30                                            Male
291            35                                            male
292            45                                            male
293            32                                            Male
294            56                                            Male
295            24                                          Female
296            30                                               F
297            60                                            male
298            33                                            Male
299            37                                               M
300            23                                          Female

In [20]:
df_2016_cleaned

      age                                             gender  \
0      39                                               Male
1      29                                               male
2      38                                              Male
3      43                                               male
4      43                                             Female
5      42                                               Male
6      30                                                  M
7      37                                             female
8      44                                             Female
9      30                                               Male
10     28                                               Male
11     34                                               Male
12     30                                             Female
13     44                                               Male
14     35                                               Male
15     52                                                  m
16     32                              I identify as female.
17     34                                               Male
18     25                                            female
19     31                                                  M
20     26                                               Male
21     35                                               male
22     25                                               male
23     33                                               Male
24     38                                               Male
25     42                                               male
26     27                                               Male
27     35                                               male
28     34                                             female
29     32                                           Bigender
30     32                                         non-binary
31     30                                               Male
32     31                                               Male
33     37                                              Male
34     36                                               Male
35     33                                               Male
36     44                                               Male
37     29                                               male
38     29                                               male
39     44                                               Male
40     34                                               Male
41     40                                               male
42     46                          Female assigned at birth
43     28                                                  M
44     41                                               Male
45     33                                               male
46     32                                               Male
47     45                                               Male
48     43                                               male
49     37                                                  F
50     37                                                  M
51     27                                               Male
52     31                                               Male
53     36                                               Male
54     34                                               Male
55     31                                              Woman
56     30                                               Male
57     32                                               Male
58     40                                             female
59     40                                               Male
60     41                                                man
61     27                                               Male
62     30                                               Male
63     29                                               Male
64     38                                               Male
65     35                                               male
66     35                                             female
67     29                                                  M
68     28                                               Male
69     27                                               Male
70     39                                               Male
71     28                                               male
72     46                                               Male
73     40                                               male
74     37                                               Male
75     41                                               Male
76     19                                                  M
77     38                                                  F
78     33                                              Male
79     33                                               Male
80     21                                               male
81     36                                               Male
82     39                                               Male
83     35                                               Male
84     36                                               male
85     45                                               Male
86     41                                               Male
87     35                                               Male
88     30                                               Male
89     24                                             Female
90     33                                               Male
91     35                                               male
92     26                                               Male
93     17                                               male
94     29                                             Female
95     26                                               Male
96     36                                             female
97     46                                                  M
98     39                                               Male
99     28                                             Female
100    40                                               Male
101    23                                               Male
102    30                                               Male
103    28                                                 fm
104    27                                               Male
105    31                                                  m
106    39                                                  f
107    34                                             Female
108    30                                               Male
109    30                                               male
110    31                                               Male
111    30                                                  M
112    32                                               Male
113    22                                               Male
114    37                                             Female
115    51                                               Male
116    26                                               Male
117    41                                                  f
118    39                                                  F
119    43                                                  M
120    30                                                  M
121    24                                             Female
122    30                                                  m
123    28                                        Cis female
124    48                                             Female
125    55                                             Female
126    36                                                  F
127    38                                               Male
128    34                                               Male
129    44                                             Female
130    45                                               Male
131    45                                                  M
132    30                                               male
133    34                                               Male
134    37                                               Male
135    38                                               Male
136    31                                               Male
137    33                                               Male
138    29                                             female
139    35                                                  M
140    42                                  Transitioned, M2F
141    26                                             Female
142    36                                                  f
143    21                                               male
144    34                                                  F
145    40                                                  M
146    35                                               Male
147    44                                               Male
148    35                          Genderfluid (born female)
149    45                                                  m
150    42                                                  m
151    40                                               Male
152    50                                                  F
153    36                                               Male
154    31                                             female
155    29                                               Male
156    37                                               Male
157    31                                                  m
158    42                                               Male
159    25                                               Male
160    27                                               Male
161    41                                             Female
162    41                                             Female
163    55                                                  F
164    21                                               Male
165    37                                               male
166    34                                             female
167    40                                               Male
168    25                                               male
169    36                                               male
170    25                                               Male
171    35                                               male
172    37                                               male
173    45                                               Male
174    26                                               Male
175    23                                               Male
176    22                                             Female
177    46                                             Female
178    31                                               Male
179    27                                               Male
180    37                                               male
181    37                                               Male
182    26                                Other/Transfeminine
183    23                                                  M
184    40                                               Male
185    29                                                  M
186    37                                               Male
187    34                                             female
188    40                                               male
189    39                                               Male
190    28                                               Male
191    28                                               male
192    27                                               Male
193    48                                               Male
194    49                                             Female
195    35                                               Male
196    35                                               Male
197    38                                               Male
198    32                                               Male
199    42                                               Male
200    33                                             female
201    35                                               Male
202    24                                                  M
203    29                       Female or Multi-Gender Femme
204    29                                               Male
205    24                                               Male
206    30                                               Male
207    30                                               male
208    44                                               male
209    37                                               Male
210    28                                               Male
211    42                                               Male
212    30                                             female
213    36                                                  m
214    30                                               male
215    29                                               Male
216    25                                               male
217    25                                               Male
218    24                                               Male
219    25                                                  m
220    31                                              Male
221    37                                                  M
222    35                                               Male
223    26                                             female
224    31                                               Male
225    29                                             female
226    33                                                  M
227    30                                                  M
228    30                                                  M
229    29                                             female
230    25                                             Female
231    27                                               Male
232    26                                               Male
233    38                                             Female
234    49                                               Male
235    30                                               Male
236    34                                               male
237    31                                               male
238    29                                               Male
239    31                                                  m
240    34                                               male
241    28                                               Male
242    35                                            Female
243    27                                              Male
244    33                                                  m
245    37                                             Female
246    45                                               Male
247    31                                              woman
248    36                                                  M
249    30                                                  M
250    33                                             female
251    45                                             female
252    30                                             Female
253    30                                               male
254    29                                               Male
255    36                                               Male
256    28                                               Male
257    36                                               Male
258    37                                             female
259    29                                               Male
260    25                                               Male
261    34                                                  f
262    37                                                  M
263    40                                             Female
264    32                                               Male
265    38                                               Male
266    31                                             Female
267    28                                             female
268    27                                             female
269    28                                             female
270    26                                               Male
271    40                                               Male
272    42                                               Male
273    36                                               Male
274    44                                               male
275    24                                               Male
276    44                                               Male
277    31                                               Male
278    49                                                  m
279    27                                       female/woman
280    27                                           Cis male
281    28                                               Male
282    20                                             Female
283    41                                              Male
284    38                                               Male
285    29                                               male
286    44                                                  f
287    31                                              Male.
288    54                                                  m
289    33                                                  m
290    29                                               male
291    26                                        Androgynous
292    26                                               male
293    34                                               Male
294    38                                             Female
295    30                                               Male
296    34                                               Male
297    47                                                  F
298    33                                             Female
299    22                                               Male
300    28                           male 9:1 female, roughly
301    31                                                  m
302    24                                                NaN
303    56                                                  m
304    57                                                  F
305    39                                                  M
306    21                                               Male
307    31                                             female
308    63                                               Male
309    46                                               male
310    32                                             Female
311    35                                                  m
312    34                                               Male
313    35                                               male
314    31                                               Male
315    35                                                  F
316    36                                               Male
317    50                                               Male
318    31                                               Male
319    47                                               male
320    32                                             Female
321    23                                             Female
322    43                                             Female
323    26                                             Female
324    26                                             female
325    55                                             Female

In [21]:
df_2017_cleaned

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,tech_company,care_options,wellness_program,seek_help,anonymity,leave,mental_vs_physical,survey_year
0,27.0,Female,United Kingdom,NaN,0,No,1,Yes,100-500,1.0,Yes,No,I don't know,I don't know,I don't know,Same level of comfort for each,2017
1,31.0,male,United Kingdom,NaN,0,No,0,Maybe,100-500,1.0,Yes,No,No,I don't know,I don't know,Same level of comfort for each,2017
2,36.0,male,United States of America,Missouri,0,Yes,1,Yes,6-25,1.0,No,I don't know,No,Yes,Difficult,Same level of comfort for each,2017
3,22.0,Male,United States of America,Washington,0,I don't know,1,Yes,More than 1000,1.0,Yes,I don't know,I don't know,Yes,Difficult,Same level of comfort for each,2017
4,52.0,female,United States of America,Illinois,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
5,30.0,male,United States of America,California,0,Yes,0,Maybe,100-500,1.0,No,No,I don't know,Yes,Somewhat easy,Physical health,2017
6,36.0,F,United States of America,Washington,0,Yes,1,Yes,6-25,1.0,Yes,No,No,Yes,Very easy,Same level of comfort for each,2017
7,38.0,Female,United States of America,Georgia,0,Yes,1,Yes,26-100,1.0,No,No,No,I don't know,Somewhat easy,Physical health,2017
8,35.0,Male,Switzerland,NaN,0,I don't know,0,Maybe,100-500,0.0,No,No,No,Yes,Very easy,Same level of comfort for each,2017
9,36.0,male,India,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
10,40.0,M,United States of America,Pennsylvania,0,Yes,1,No,100-500,0.0,Yes,No,No,I don't know,I don't know,Physical health,2017
11,35.0,Male,United States of America,Tennessee,0,Yes,0,Maybe,100-500,1.0,No,No,I don't know,I don't know,Difficult,Physical health,2017
12,23.0,Male,Russia,NaN,0,No,0,Maybe,More than 1000,1.0,No,No,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2017
13,22.0,Female,United States of America,Louisiana,0,I don't know,1,Maybe,More than 1000,1.0,No,No,I don't know,I don't know,Neither easy nor difficult,Physical health,2017
14,34.0,female,United States of America,California,0,Yes,1,Maybe,26-100,1.0,NaN,I don't know,I don't know,Yes,Very easy,Same level of comfort for each,2017
15,28.0,Male,United States of America,Ohio,0,No,1,Yes,100-500,0.0,No,No,I don't know,I don't know,Somewhat easy,Physical health,2017
16,38.0,male,Bangladesh,NaN,0,No,0,Yes,26-100,0.0,No,No,No,Yes,Neither easy nor difficult,Same level of comfort for each,2017
17,53.0,Male,United States of America,Illinois,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
18,21.0,Male,Germany,NaN,0,No,0,Maybe,6-25,1.0,No,No,No,I don't know,Somewhat easy,Physical health,2017
19,35.0,F,United Kingdom,NaN,0,Yes,0,Maybe,More than 1000,0.0,No,No,I don't know,I don't know,Neither easy nor difficult,Physical health,2017
20,22.0,Male,United Kingdom,NaN,0,Yes,0,No,6-25,1.0,No,No,No,I don't know,Neither easy nor difficult,Physical health,2017
21,18.0,Male,United Kingdom,NaN,0,Yes,1,Yes,100-500,0.0,NaN,Yes,Yes,Yes,Somewhat difficult,Physical health,2017
22,37.0,female,United States of America,Ohio,0,Yes,1,Yes,26-100,0.0,No,No,No,I don't know,Difficult,Physical health,2017
23,25.0,Male,United Kingdom,NaN,0,I don't know,1,Maybe,1-5,1.0,NaN,No,No,I don't know,Difficult,Mental health,2017
24,40.0,male,Canada,NaN,0,I don't know,1,No,100-500,1.0,No,Yes,No,I don't know,I don't know,Physical health,2017
25,33.0,Male,Israel,NaN,0,Yes,0,Yes,6-25,1.0,No,No,No,Yes,Very easy,Same level of comfort for each,2017
26,66.0,F,United States of America,Oregon,0,Yes,1,No,More than 1000,0.0,No,No,I don't know,I don't know,Somewhat difficult,Physical health,2017
27,31.0,female,United States of America,Ohio,0,Yes,1,Maybe,100-500,0.0,Yes,No,No,I don't know,Somewhat easy,Physical health,2017
28,32.0,Male,Canada,NaN,0,Yes,1,Maybe,100-500,0.0,Yes,Yes,Yes,Yes,Neither easy nor difficult,Physical health,2017
29,46.0,M,United States of America,New York,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
30,30.0,female,United States of America,California,0,Yes,1,No,100-500,1.0,Yes,I don't know,No,I don't know,Somewhat difficult,Physical health,2017
31,31.0,Man,United States of America,Pennsylvania,0,I don't know,1,Maybe,100-500,1.0,Yes,No,No,Yes,Very easy,Physical health,2017
32,46.0,Male,Iceland,NaN,0,Yes,1,Maybe,100-500,1.0,NaN,No,No,I don't know,Somewhat easy,Physical health,2017
33,29.0,NaN,Canada,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
34,28.0,f,United States of America,Tennessee,0,Yes,1,Maybe,More than 1000,0.0,No,No,I don't know,I don't know,I don't know,Same level of comfort for each,2017
35,34.0,Female,Japan,NaN,0,I don't know,1,No,6-25,0.0,No,No,No,I don't know,Difficult,Physical health,2017
36,25.0,Male,United States of America,Minnesota,0,I don't know,1,Yes,26-100,1.0,Yes,No,No,No,Difficult,Physical health,2017
37,35.0,Male,United States of America,Kansas,0,I don't know,1,Maybe,100-500,0.0,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2017
38,25.0,NaN,Indonesia,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
39,40.0,male,United States of America,Colorado,0,No,0,Yes,100-500,1.0,Yes,No,I don't know,I don't know,Somewhat easy,Physical health,2017
40,32.0,M,United States of America,Virginia,0,I don't know,0,Yes,100-500,0.0,No,No,I don't know,I don't know,Very easy,Physical health,2017
41,39.0,Male,United States of America,Virginia,0,Yes,1,No,100-500,0.0,No,No,I don't know,I don't know,Neither easy nor difficult,Physical health,2017
42,33.0,male,United States of America,Colorado,0,Yes,1,Maybe,500-1000,1.0,Yes,I don't know,I don't know,I don't know,I don't know,Physical health,2017
43,40.0,Male,United States of America,Virginia,0,I don't know,1,No,100-500,1.0,Yes,Yes,Yes,Yes,Very easy,Physical health,2017
44,42.0,male,United States of America,Minnesota,0,I don't know,1,Yes,500-1000,1.0,No,No,I don't know,Yes,Very easy,Same level of comfort for each,2017
45,32.0,Male,United States of America,Tennessee,0,Yes,1,No,More than 1000,0.0,No,I don't know,I don't know,I don't know,Difficult,Physical health,2017
46,27.0,Female,United States of America,Illinois,0,I don't know,1,No,More than 1000,0.0,Yes,No,Yes,No,Somewhat difficult,Physical health,2017
47,43.0,Female,United Kingdom,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
48,30.0,female,Indonesia,NaN,0,I don't know,1,No,6-25,0.0,NaN,No,No,No,Difficult,Mental health,2017
49,39.0,male,United States of America,Minnesota,0,Yes,1,Maybe,26-100,0.0,No,No,No,I don't know,Difficult,Physical health,2017
50,42.0,Female,United States of America,Illinois,0,Yes,1,No,6-25,1.0,No,No,I don't know,I don't know,I don't know,Same level of comfort for each,2017
51,37.0,Genderfluid,Canada,NaN,0,Yes,1,Yes,6-25,1.0,Yes,Yes,No,Yes,Somewhat easy,Physical health,2017
52,38.0,Female,United States of America,Wisconsin,0,Yes,1,No,500-1000,0.0,Yes,No,I don't know,I don't know,Difficult,Physical health,2017
53,47.0,Male,United Kingdom,NaN,0,No,0,Maybe,More than 1000,1.0,No,I don't know,I don't know,I don't know,Very easy,Physical health,2017
54,64.0,male,United Kingdom,NaN,0,No,1,No,500-1000,1.0,No,Yes,Yes,I don't know,Somewhat difficult,Physical health,2017
55,28.0,Male,Canada,NaN,0,Yes,1,No,100-500,0.0,Yes,No,No,I don't know,Somewhat difficult,Physical health,2017
56,45.0,Male,United States of America,California,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
57,37.0,M,United Kingdom,NaN,0,No,0,Maybe,100-500,1.0,Yes,Yes,I don't know,Yes,Very easy,Physical health,2017
58,30.0,Female,United Kingdom,NaN,0,Yes,1,Yes,26-100,1.0,Yes,Yes,Yes,I don't know,Very easy,Mental health,2017
59,25.0,Male,United Kingdom,NaN,0,No,0,Yes,100-500,0.0,No,No,No,I don't know,Somewhat easy,Physical health,2017
60,25.0,Female,United Kingdom,NaN,0,Yes,0,Maybe,26-100,1.0,NaN,No,Yes,Yes,Very easy,Physical health,2017
61,54.0,Female,United States of America,Minnesota,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
62,61.0,Male,United Kingdom,NaN,0,I don't know,1,Yes,500-1000,1.0,Yes,Yes,Yes,I don't know,Neither easy nor difficult,Same level of comfort for each,2017
63,26.0,male,India,NaN,0,No,0,Maybe,More than 1000,1.0,No,No,No,I don't know,I don't know,Mental health,2017
64,44.0,Female,United States of America,Ohio,0,Yes,1,No,More than 1000,0.0,Yes,Yes,Yes,I don't know,Neither easy nor difficult,Physical health,2017
65,26.0,male,Portugal,NaN,0,I don't know,1,Yes,6-25,1.0,No,No,No,I don't know,I don't know,Physical health,2017
66,26.0,Female,Portugal,NaN,0,Yes,1,Yes,26-100,1.0,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2017
67,35.0,female,United States of America,Washington,0,I don't know,1,Yes,6-25,1.0,No,No,I don't know,Yes,Neither easy nor difficult,Same level of comfort for each,2017
68,45.0,Male,United States of America,Maryland,0,No,0,Maybe,26-100,1.0,Yes,No,No,I don't know,Very easy,Physical health,2017
69,23.0,Male,United States of America,Minnesota,0,I don't know,0,Yes,26-100,1.0,No,No,No,I don't know,Somewhat easy,Physical health,2017
70,44.0,Male,United States of America,Ohio,0,No,0,Yes,More than 1000,0.0,Yes,I don't know,I don't know,I don't know,Somewhat easy,Physical health,2017
71,38.0,male,United States of America,Ohio,0,I don't know,1,Yes,More than 1000,0.0,No,Yes,Yes,Yes,Neither easy nor difficult,Same level of comfort for each,2017
72,46.0,Male,United States of America,Ohio,0,Yes,1,Yes,500-1000,0.0,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2017
73,27.0,Nonbinary,United States of America,Ohio,0,I don't know,1,Maybe,500-1000,0.0,No,Yes,I don't know,I don't know,Somewhat difficult,Physical health,2017
74,39.0,female,United States of America,Ohio,0,Yes,1,Maybe,100-500,0.0,Yes,I don't know,Yes,Yes,Difficult,Physical health,2017
75,33.0,Female,United States of America,Montana,0,Yes,1,No,26-100,1.0,No,No,No,I don't know,I don't know,Physical health,2017
76,38.0,female,United States of America,Colorado,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
77,35.0,Male,United Kingdom,NaN,0,No,0,No,26-100,0.0,NaN,No,No,I don't know,Difficult,Physical health,2017
78,32.0,male,Germany,NaN,0,No,1,No,More than 1000,1.0,No,No,No,I don't know,Neither easy nor difficult,Physical health,2017
79,26.0,Female,United States of America,California,0,I don't know,0,No,More than 1000,1.0,Yes,I don't know,No,I don't know,Somewhat easy,Physical health,2017
80,50.0,cis-male,United States of America,Pennsylvania,0,Yes,1,Maybe,100-500,1.0,Yes,No,I don't know,I don't know,Somewhat difficult,Physical health,2017
81,31.0,Male,United States of America,Utah,0,Yes,1,Yes,100-500,1.0,Yes,I don't know,I don't know,I don't know,Somewhat easy,Physical health,2017
82,46.0,Male,Romania,NaN,0,Yes,0,Maybe,More than 1000,1.0,No,Yes,I don't know,I don't know,Somewhat difficult,Physical health,2017
83,30.0,Male,United States of America,California,0,Yes,1,No,26-100,1.0,No,No,No,Yes,Somewhat easy,Physical health,2017
84,30.0,Mail,United States of America,Minnesota,0,I don't know,1,Maybe,More than 1000,1.0,No,No,I don't know,I don't know,Somewhat difficult,Physical health,2017
85,34.0,male,Germany,NaN,0,No,1,Yes,100-500,1.0,No,No,No,I don't know,Neither easy nor difficult,Physical health,2017
86,42.0,Male,United Kingdom,NaN,0,No,0,No,More than 1000,0.0,Yes,Yes,Yes,Yes,Difficult,Same level of comfort for each,2017
87,24.0,Female,United States of America,Washington,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,No,Somewhat difficult,Physical health,2017
88,30.0,Male,United States of America,Texas,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
89,23.0,Male,Canada,NaN,0,I don't know,0,Maybe,26-100,1.0,Yes,Yes,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2017
90,31.0,female,United States of America,California,0,Yes,1,No,100-500,1.0,Yes,No,No,I don't know,Somewhat easy,Physical health,2017
91,31.0,male,Finland,NaN,0,I don't know,0,No,26-100,1.0,No,No,No,I don't know,I don't know,Physical health,2017
92,27.0,Woman,United States of America,Illinois,0,Yes,1,Maybe,100-500,1.0,Yes,No,I don't know,I don't know,Somewhat easy,Physical health,2017
93,26.0,Male,Pakistan,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
94,52.0,Female,United States of America,Washington,0,Yes,0,Maybe,500-1000,0.0,Yes,No,Yes,I don't know,Somewhat difficult,Physical health,2017
95,28.0,Male,Portugal,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
96,37.0,male,United States of America,Oregon,0,I don't know,0,No,1-5,1.0,No,No,I don't know,I don't know,I don't know,Physical health,2017
97,37.0,male,Canada,NaN,0,No,0,Maybe,500-1000,0.0,NaN,Yes,Yes,No,Somewhat easy,Physical health,2017
98,38.0,Male,United States of America,Oregon,0,Yes,1,Yes,More than 1000,0.0,Yes,No,No,Yes,Very easy,Same level of comfort for each,2017
99,57.0,Female,United States of America,Maryland,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
100,34.0,Male,United States of America,New York,0,Yes,1,Yes,More than 1000,1.0,Yes,I don't know,I don't know,I don't know,Somewhat easy,Physical health,2017
101,38.0,female,Germany,NaN,0,Yes,1,No,More than 1000,1.0,Yes,No,Yes,I don't know,Difficult,Same level of comfort for each,2017
102,30.0,Male,United States of America,Oregon,0,I don't know,1,Maybe,26-100,1.0,No,No,I don't know,Yes,Neither easy nor difficult,Physical health,2017
103,52.0,Male,United States of America,Georgia,0,No,0,No,More than 1000,0.0,Yes,Yes,I don't know,Yes,Somewhat easy,Physical health,2017
104,31.0,Female,United States of America,California,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
105,29.0,Male,Germany,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
106,26.0,Female,United Kingdom,NaN,0,Yes,0,No,6-25,1.0,No,No,No,I don't know,Difficult,Physical health,2017
107,29.0,female,United States of America,Ohio,0,I don't know,1,Yes,26-100,0.0,No,No,No,Yes,Somewhat difficult,Physical health,2017
108,44.0,Male,United States of America,Washington,0,Yes,1,Yes,More than 1000,1.0,Yes,No,No,Yes,I don't know,Physical health,2017
109,18.0,male/androgynous,Canada,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
110,42.0,Male,Australia,NaN,0,Yes,1,Yes,More than 1000,1.0,NaN,Yes,I don't know,Yes,Very easy,Same level of comfort for each,2017
111,30.0,Male,United States of America,Tennessee,0,Yes,1,No,6-25,0.0,Yes,No,No,Yes,Somewhat easy,Physical health,2017
112,29.0,M,United States of America,New York,0,I don't know,1,Yes,100-500,1.0,No,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2017
113,27.0,Female,United States of America,Texas,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,I don't know,Neither easy nor difficult,Same level of comfort for each,2017
114,39.0,Male,United States of America,Washington,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2017
115,40.0,female,United States of America,California,0,Yes,1,Yes,100-500,1.0,Yes,Yes,No,Yes,Very easy,Physical health,2017
116,36.0,female,United States of America,Pennsylvania,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Physical health,2017
117,48.0,female,United States of America,California,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
118,43.0,male,United States of America,Colorado,0,No,0,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2017
119,38.0,Man,United States of America,New Mexico,0,Yes,1,Maybe,100-500,1.0,Yes,I don't know,Yes,Yes,Neither easy nor difficult,Physical health,2017
120,42.0,Male,United States of America,California,0,I don't know,1,Yes,26-100,1.0,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2017
121,46.0,Male,United Kingdom,NaN,0,I don't know,1,Maybe,500-1000,1.0,NaN,Yes,Yes,Yes,Neither easy nor difficult,Physical health,2017
122,30.0,male,United States of America,Virginia,0,Yes,1,No,More than 1000,0.0,Yes,No,Yes,Yes,Difficult,Physical health,2017
123,25.0,Male,United Kingdom,NaN,0,Yes,1,No,6-25,0.0,Yes,No,No,No,Difficult,Physical health,2017
124,28.0,NaN,Canada,NaN,0,Yes,0,Maybe,500-1000,1.0,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2017
125,24.0,Female,Germany,NaN,0,Yes,1,Maybe,100-500,1.0,Yes,No,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2017
126,26.0,male,United Kingdom,NaN,0,Yes,0,Yes,1-5,1.0,No,No,No,I don't know,Difficult,Physical health,2017
127,43.0,cis hetero male,United States of America,North Carolina,0,Yes,1,Maybe,More than 1000,1.0,Yes,No,Yes,I don't know,Somewhat easy,Physical health,2017
128,25.0,Female,United States of America,New York,0,I don't know,1,No,More than 1000,0.0,Yes,No,Yes,I don't know,I don't know,Physical health,2017
129,34.0,male,United States of America,Arizona,0,Yes,0,No,More than 1000,0.0,No,Yes,I don't know,I don't know,I don't know,Physical health,2017
130,28.0,female,United States of America,District of Columbia,0,No,0,No,26-100,1.0,Yes,Yes,I don't know,Yes,Very easy,Physical health,2017
131,27.0,Male,South Africa,NaN,0,I don't know,1,Yes,26-100,1.0,NaN,No,No,Yes,Somewhat difficult,Physical health,2017
132,22.0,Male,India,NaN,0,No,0,Maybe,26-100,1.0,No,Yes,Yes,Yes,Somewhat easy,Physical health,2017
133,24.0,female,Romania,NaN,0,Yes,0,No,26-100,1.0,No,No,Yes,Yes,Very easy,Physical health,2017
134,33.0,female,Pakistan,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
135,41.0,m,Germany,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
136,26.0,Female,United Kingdom,NaN,0,I don't know,0,No,26-100,1.0,NaN,No,I don't know,I don't know,I don't know,Physical health,2017
137,39.0,Male,United States of America,California,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
138,24.0,male,United States of America,Tennessee,0,No,0,Maybe,1-5,1.0,No,No,No,I don't know,Somewhat easy,Physical health,2017
139,54.0,Male,United States of America,Washington,0,I don't know,1,No,More than 1000,1.0,No,No,No,I don't know,I don't know,Physical health,2017
140,47.0,m,United States of America,Ohio,0,Yes,1,Yes,More than 1000,0.0,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2017
141,33.0,Male,Sweden,NaN,0,No,0,Yes,More than 1000,1.0,NaN,No,No,I don't know,Very easy,Same level of comfort for each,2017
142,30.0,NaN,United States of America,Utah,0,Yes,1,Yes,100-500,1.0,Yes,No,No,Yes,Somewhat easy,Same level of comfort for each,2017
143,48.0,Male,United States of America,Massachusetts,0,I don't know,1,No,More than 1000,0.0,Yes,No,I don't know,I don't know,I don't know,Physical health,2017
144,35.0,male,United States of America,Idaho,0,Yes,1,Yes,More than 1000,1.0,No,I don't know,Yes,Yes,Somewhat easy,Physical health,2017
145,34.0,Male,United States of America,Tennessee,0,I don't know,0,Yes,26-100,0.0,No,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2017
146,31.0,Male,Serbia,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017
147,25.0,male,United States of America,Tennessee,0,Yes,0,Maybe,500-1000,1.0,Yes,No,No,Yes,Somewhat easy,Physical health,2017
148,48.0,male,Spain,NaN,0,Yes,1,No,More than 1000,1.0,No,No,No,I don't know,Somewhat easy,Physical health,2017
149,34.0,Male,United States of America,California,0,I don't know,1,Maybe,100-500,0.0,No,Yes,I don't know,I don't know,I don't know,Physical health,2017
150,42.0,M,United States of America,California,0,Yes,1,No,100-500,1.0,Yes,No,No,I don't know,Difficult,Physical health,2017
151,27.0,Male,United States of America,Illinois,0,Yes,1,Maybe,100-500,1.0,No,No,No,I don't know,Very easy,Physical health,2017
152,33.0,Female,United States of America,California,0,Yes,1,Yes,More than 1000,1.0,Yes,No,No,Yes,Somewhat difficult,Same level of comfort for each,2017
153,27.0,Female,United States of America,Maryland,0,I don't know,1,Maybe,26-100,1.0,Yes,No,I don't know,I don't know,Very easy,Physical health,2017
154,48.0,m,United States of America,Minnesota,0,I don't know,0,No,500-1000,1.0,No,No,No,I don't know,I don't know,Same level of comfort for each,2017
155,32.0,f,United States of America,Virginia,0,I don't know,1,Maybe,More than 1000,1.0,Yes,No,No,Yes,Somewhat easy,Same level of comfort for each,2017

In [22]:
df_2018_cleaned

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_vs_physical,survey_year
0,57,Female,Canada,NaN,0,Yes,1,No,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,Physical health,2018
1,29,male,United States of America,Massachusetts,0,Yes,1,No,More than 1000,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat difficult,Physical health,2018
2,46,Male,United States of America,Florida,0,Yes,0,No,6-25,0.0,Yes,Yes,No,No,I don't know,Somewhat easy,Physical health,2018
3,34,male,Norway,NaN,0,No,0,No,6-25,1.0,No,No,No,No,I don't know,Neither easy nor difficult,Physical health,2018
4,29,Ostensibly Male,United States of America,Tennessee,0,Yes,1,Yes,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2018
5,55,male,United States of America,South Carolina,0,No,0,Yes,100-500,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2018
6,29,Agender,Finland,NaN,0,No,1,No,More than 1000,1.0,Yes,Yes,No,No,I don't know,I don't know,Physical health,2018
7,35,male,Poland,NaN,0,I don't know,1,No,26-100,1.0,Not eligible for coverage / NA,NaN,No,No,I don't know,I don't know,Physical health,2018
8,33,"male, born with xy chromosoms",Russia,NaN,0,Yes,0,No,More than 1000,1.0,I don't know,No,No,No,No,I don't know,Physical health,2018
9,37,Male,United States of America,Iowa,0,No,0,No,More than 1000,0.0,Yes,No,No,Yes,I don't know,Somewhat difficult,Physical health,2018
10,45,Male,United States of America,Washington,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2018
11,31,Male,Germany,NaN,0,I don't know,1,Maybe,500-1000,0.0,No,No,No,No,I don't know,Very easy,Physical health,2018
12,38,Female,Canada,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
13,26,Male,Germany,NaN,0,Yes,0,Maybe,More than 1000,0.0,I don't know,No,No,I don't know,I don't know,Somewhat easy,Physical health,2018
14,27,female,Serbia,NaN,0,No,1,No,100-500,1.0,No,No,No,No,I don't know,Neither easy nor difficult,Physical health,2018
15,35,Male,Canada,NaN,0,Yes,1,Maybe,6-25,0.0,Yes,No,No,No,I don't know,Somewhat difficult,Same level of comfort for each,2018
16,47,Male,United States of America,Florida,0,Yes,0,No,26-100,0.0,Yes,No,No,Yes,I don't know,Neither easy nor difficult,Physical health,2018
17,37,Male,United States of America,Florida,0,I don't know,1,Maybe,More than 1000,1.0,Yes,Yes,I don't know,I don't know,I don't know,I don't know,Physical health,2018
18,32,Male,Colombia,NaN,0,Yes,0,No,500-1000,0.0,No,No,No,No,No,Difficult,Physical health,2018
19,46,Male,United Kingdom,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
20,37,Male,United States of America,Tennessee,0,Yes,1,No,26-100,1.0,Yes,No,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2018
21,36,male,United States of America,New Hampshire,0,Yes,1,Yes,100-500,1.0,Yes,Yes,I don't know,Yes,Yes,Somewhat easy,Physical health,2018
22,29,Malel,Poland,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
23,45,Male,United States of America,Wisconsin,0,I don't know,1,No,100-500,1.0,Yes,No,No,No,I don't know,Very easy,Physical health,2018
24,30,Male,United States of America,Massachusetts,0,No,0,Maybe,6-25,0.0,I don't know,No,No,I don't know,I don't know,Somewhat difficult,Physical health,2018
25,46,male,Germany,NaN,0,I don't know,1,Maybe,6-25,1.0,No,No,Yes,No,I don't know,Very easy,Physical health,2018
26,29,male,India,NaN,0,No,0,No,26-100,1.0,No,NaN,No,No,I don't know,Difficult,Physical health,2018
27,26,male,Ukraine,NaN,0,I don't know,0,No,More than 1000,1.0,I don't know,NaN,No,No,Yes,Somewhat easy,Same level of comfort for each,2018
28,26,Male,United States of America,Connecticut,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
29,44,Male,Canada,NaN,0,Yes,1,No,6-25,1.0,I don't know,No,No,I don't know,I don't know,Difficult,Physical health,2018
30,32,Male,United States of America,Rhode Island,0,I don't know,0,No,26-100,1.0,Yes,No,No,I don't know,I don't know,Neither easy nor difficult,Physical health,2018
31,34,male,Poland,NaN,0,No,0,Maybe,100-500,1.0,I don't know,No,No,No,I don't know,I don't know,Physical health,2018
32,19,male,Australia,NaN,0,I don't know,0,Maybe,500-1000,1.0,Yes,NaN,Yes,Yes,Yes,Very easy,Physical health,2018
33,38,M,United Kingdom,NaN,0,Yes,1,No,More than 1000,0.0,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,2018
34,61,Male,United States of America,Minnesota,0,No,1,No,6-25,1.0,Not eligible for coverage / NA,NaN,No,No,No,Difficult,Physical health,2018
35,44,Male,United States of America,Pennsylvania,0,I don't know,0,No,6-25,1.0,Yes,Yes,No,I don't know,I don't know,I don't know,Physical health,2018
36,32,Female,United States of America,Oregon,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
37,31,Male,Ireland,NaN,0,No,0,Yes,100-500,0.0,Yes,No,Yes,Yes,Yes,Somewhat easy,Physical health,2018
38,30,Female,United States of America,Rhode Island,0,No,1,Yes,26-100,1.0,Yes,No,Yes,Yes,I don't know,Neither easy nor difficult,Physical health,2018
39,52,male,Italy,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
40,44,male,United States of America,Washington,0,Yes,1,No,26-100,1.0,I don't know,No,No,No,I don't know,I don't know,Physical health,2018
41,39,Male,United States of America,Washington,0,Yes,1,Yes,More than 1000,0.0,I don't know,Yes,No,No,I don't know,Very easy,Mental health,2018
42,36,Male,Spain,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
43,30,NaN,Netherlands,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
44,39,male,United States of America,Pennsylvania,0,I don't know,0,No,26-100,0.0,I don't know,No,No,No,Yes,Somewhat difficult,Same level of comfort for each,2018
45,33,male,United States of America,Georgia,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2018
46,37,Male,United States of America,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
47,34,male,Estonia,NaN,0,No,0,No,26-100,0.0,No,No,No,No,I don't know,Difficult,Physical health,2018
48,28,Male,India,NaN,0,No,0,Maybe,26-100,1.0,No,No,Yes,Yes,I don't know,Very easy,Physical health,2018
49,43,Female,Italy,NaN,0,No,1,No,26-100,1.0,No,NaN,No,No,I don't know,Difficult,Same level of comfort for each,2018
50,42,male,United States of America,Texas,0,Yes,0,No,More than 1000,1.0,I don't know,No,No,No,I don't know,Somewhat easy,Physical health,2018
51,35,male,United States of America,New York,0,Yes,1,Yes,100-500,0.0,Yes,Yes,I don't know,Yes,I don't know,I don't know,Physical health,2018
52,28,female,United States of America,New York,0,Yes,0,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2018
53,37,male,United States of America,Georgia,0,Yes,1,Yes,100-500,1.0,Yes,Yes,I don't know,I don't know,I don't know,Somewhat difficult,Physical health,2018
54,35,female,United States of America,Florida,0,Yes,1,No,500-1000,1.0,I don't know,Yes,No,No,I don't know,Somewhat easy,Physical health,2018
55,31,male,United States of America,New York,0,No,0,No,6-25,1.0,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,2018
56,24,Male,United States of America,Pennsylvania,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
57,27,Female,United States of America,Texas,0,No,0,Maybe,500-1000,1.0,Yes,No,No,No,I don't know,Somewhat difficult,Physical health,2018
58,36,Male,United States of America,New York,0,Yes,1,Yes,More than 1000,1.0,Yes,No,Yes,Yes,I don't know,Very easy,Physical health,2018
59,33,male,United States of America,California,0,No,1,Yes,6-25,1.0,I don't know,No,No,I don't know,Yes,Somewhat easy,Physical health,2018
60,26,M,United States of America,New York,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
61,26,Male,United States of America,New York,0,No,0,No,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2018
62,24,Male,United States of America,New York,0,No,1,No,More than 1000,0.0,I don't know,NaN,No,No,I don't know,I don't know,Physical health,2018
63,34,Male,United States of America,Washington,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2018
64,25,Male,United States of America,New York,0,I don't know,0,No,26-100,1.0,Yes,Yes,No,No,I don't know,I don't know,Physical health,2018
65,19,female,United States of America,New York,0,Yes,1,No,6-25,1.0,I don't know,No,No,No,Yes,I don't know,Same level of comfort for each,2018
66,28,M,United States of America,Massachusetts,0,No,0,No,26-100,1.0,Yes,No,No,I don't know,Yes,Somewhat difficult,Physical health,2018
67,26,male,United States of America,Washington,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,No,No,Yes,Somewhat easy,Physical health,2018
68,32,male,South Africa,NaN,0,Yes,1,Maybe,1-5,1.0,No,NaN,No,No,No,Somewhat easy,Physical health,2018
69,23,male,United States of America,New Hampshire,0,I don't know,1,Maybe,500-1000,0.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2018
70,46,M,United States of America,Alabama,0,Yes,0,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2018
71,28,Male,United States of America,Missouri,0,No,0,Yes,6-25,1.0,I don't know,No,No,No,I don't know,Difficult,Same level of comfort for each,2018
72,38,MALE,Norway,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
73,30,Female,United States of America,Indiana,0,I don't know,1,Maybe,6-25,1.0,I don't know,No,No,No,I don't know,Somewhat easy,Physical health,2018
74,26,Male,Brazil,NaN,0,No,0,Yes,6-25,1.0,I don't know,No,No,No,I don't know,Somewhat difficult,Same level of comfort for each,2018
75,37,Woman,Mauritius,NaN,0,No,0,Maybe,6-25,1.0,Yes,Yes,No,No,Yes,Very easy,Physical health,2018
76,35,Male,United States of America,Ohio,0,I don't know,1,Maybe,100-500,1.0,Yes,Yes,Yes,Yes,I don't know,Neither easy nor difficult,Same level of comfort for each,2018
77,26,Female,United States of America,California,0,Yes,1,Maybe,100-500,0.0,Yes,Yes,Yes,Yes,Yes,I don't know,Physical health,2018
78,29,Female,United Kingdom,NaN,0,No,0,Maybe,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2018
79,57,Male,United States of America,Illinois,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,I don't know,Yes,Yes,I don't know,Same level of comfort for each,2018
80,38,Male,United States of America,North Carolina,0,No,0,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2018
81,20,Female,United Kingdom,NaN,0,No,1,Yes,More than 1000,1.0,Yes,No,Yes,Yes,Yes,Somewhat easy,Physical health,2018
82,41,M,United States of America,Florida,0,Yes,0,No,6-25,1.0,I don't know,No,No,No,I don't know,Difficult,Physical health,2018
83,43,male,United States of America,Florida,0,Yes,0,Maybe,6-25,0.0,Yes,No,No,No,No,Somewhat difficult,Physical health,2018
84,35,Male,United States of America,Pennsylvania,0,I don't know,1,Yes,More than 1000,1.0,Yes,Yes,No,Yes,Yes,I don't know,Physical health,2018
85,40,female,United States of America,Pennsylvania,0,Yes,1,Yes,6-25,1.0,I don't know,No,No,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2018
86,28,male,Brazil,NaN,0,No,0,Maybe,26-100,0.0,I don't know,NaN,I don't know,I don't know,No,Neither easy nor difficult,Same level of comfort for each,2018
87,42,Male,United States of America,Michigan,0,Yes,1,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2018
88,39,male,United States of America,Kansas,0,No,0,Maybe,More than 1000,0.0,Yes,No,No,Yes,Yes,Somewhat easy,Physical health,2018
89,28,M,United States of America,Iowa,0,Yes,1,Yes,More than 1000,0.0,Yes,Yes,I don't know,Yes,Yes,Neither easy nor difficult,Physical health,2018
90,22,m,India,NaN,0,No,0,Yes,6-25,1.0,No,No,No,I don't know,I don't know,Somewhat easy,Mental health,2018
91,29,woman,United States of America,California,0,Yes,1,No,100-500,1.0,Yes,Yes,No,Yes,I don't know,Somewhat difficult,Physical health,2018
92,45,Male,United States of America,Illinois,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
93,27,Female,Saudi Arabia,NaN,0,Yes,0,No,More than 1000,1.0,No,No,No,No,I don't know,Difficult,Physical health,2018
94,32,F,Germany,NaN,0,No,0,No,26-100,0.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2018
95,28,Male,United States of America,Oregon,0,I don't know,1,Yes,500-1000,0.0,Yes,Yes,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2018
96,31,male,United States of America,Oregon,0,Yes,1,Yes,100-500,1.0,Yes,No,No,Yes,Yes,Somewhat easy,Physical health,2018
97,28,Male,United States of America,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
98,24,f,Nigeria,NaN,0,No,0,No,More than 1000,0.0,No,No,No,No,No,Difficult,Physical health,2018
99,27,Female,United States of America,Texas,0,Yes,0,No,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,I don't know,Physical health,2018
100,36,f,Ireland,NaN,0,No,0,No,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2018
101,37,Male,United States of America,California,0,Yes,1,No,More than 1000,1.0,No,Yes,No,No,No,Difficult,Physical health,2018
102,27,Female,Kenya,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
103,53,Female,United States of America,Oregon,0,Yes,1,No,100-500,1.0,Yes,Yes,No,I don't know,Yes,Very easy,Same level of comfort for each,2018
104,32,Male,France,NaN,0,No,0,Maybe,100-500,1.0,Not eligible for coverage / NA,NaN,No,No,I don't know,Very easy,Physical health,2018
105,25,I identify as female,United States of America,New York,0,Yes,1,No,1-5,1.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2018
106,29,*shrug emoji* (F),United States of America,Wisconsin,0,Yes,1,Maybe,6-25,1.0,Not eligible for coverage / NA,NaN,No,I don't know,I don't know,Difficult,Physical health,2018
107,47,Male,United States of America,Tennessee,0,I don't know,0,Yes,26-100,1.0,Yes,No,No,Yes,Yes,Somewhat difficult,Same level of comfort for each,2018
108,36,Male,United States of America,Tennessee,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
109,61,Male,United States of America,Massachusetts,0,Yes,1,Maybe,More than 1000,0.0,Yes,No,No,I don't know,I don't know,Somewhat difficult,Physical health,2018
110,28,male,United States of America,Kentucky,0,No,0,Maybe,6-25,1.0,Yes,No,No,I don't know,Yes,I don't know,Physical health,2018
111,31,Male,United States of America,Illinois,0,Yes,1,Yes,500-1000,0.0,Yes,Yes,Yes,No,Yes,I don't know,Same level of comfort for each,2018
112,35,Male,Uruguay,NaN,0,I don't know,1,Maybe,6-25,1.0,No,NaN,No,No,I don't know,Somewhat easy,Physical health,2018
113,40,Male,United States of America,Georgia,0,Yes,1,Yes,26-100,1.0,I don't know,No,No,I don't know,I don't know,Somewhat easy,Physical health,2018
114,32,Male,United States of America,Colorado,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
115,41,Male,United States of America,Texas,0,No,0,Yes,26-100,1.0,Yes,No,No,I don't know,Yes,Somewhat easy,Same level of comfort for each,2018
116,34,M,United States of America,Minnesota,0,No,1,Maybe,6-25,1.0,Yes,Yes,No,Yes,I don't know,Difficult,Physical health,2018
117,31,Female,United States of America,Illinois,0,Yes,1,Maybe,6-25,1.0,I don't know,No,No,No,I don't know,Neither easy nor difficult,Physical health,2018
118,35,Female,United States of America,Maryland,0,I don't know,1,Yes,More than 1000,0.0,Yes,Yes,No,I don't know,Yes,Very easy,Same level of comfort for each,2018
119,27,Female,United States of America,California,0,Yes,1,Maybe,500-1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2018
120,42,Female,United States of America,Texas,0,Yes,1,Yes,100-500,1.0,Yes,No,No,Yes,Yes,Somewhat easy,Physical health,2018
121,67,Female,United States of America,Tennessee,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
122,56,male,United States of America,California,0,Yes,1,No,More than 1000,0.0,Yes,Yes,No,No,Yes,Somewhat easy,Physical health,2018
123,27,Female,United States of America,Indiana,0,Yes,1,Maybe,6-25,1.0,Yes,No,No,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2018
124,37,Female,United Kingdom,NaN,0,Yes,1,Yes,More than 1000,1.0,Yes,No,No,I don't know,Yes,Somewhat difficult,Physical health,2018
125,40,Male,Serbia,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
126,30,Female,United Kingdom,NaN,0,I don't know,0,No,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2018
127,39,Male,United States of America,Nebraska,0,Yes,0,Yes,More than 1000,1.0,Yes,No,I don't know,I don't know,Yes,Somewhat difficult,Physical health,2018
128,30,Female,United States of America,Ohio,0,Yes,1,Maybe,6-25,1.0,Not eligible for coverage / NA,NaN,No,No,I don't know,I don't know,Same level of comfort for each,2018
129,31,male,Netherlands,NaN,0,No,0,Yes,6-25,1.0,I don't know,No,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2018
130,36,Male,Italy,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
131,46,Male,United Kingdom,NaN,0,Yes,1,No,6-25,1.0,Yes,Yes,No,No,I don't know,I don't know,Physical health,2018
132,45,Female,United States of America,Illinois,0,Yes,1,Maybe,500-1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,Physical health,2018
133,25,male,Bangladesh,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
134,38,f,United States of America,Illinois,0,Yes,1,Maybe,More than 1000,0.0,Not eligible for coverage / NA,NaN,No,No,I don't know,I don't know,Same level of comfort for each,2018
135,41,m,United States of America,Illinois,0,No,0,Yes,26-100,1.0,Yes,Yes,Yes,I don't know,I don't know,Very easy,Same level of comfort for each,2018
136,37,Male,United States of America,New Jersey,0,Yes,1,Maybe,100-500,1.0,Yes,Yes,I don't know,Yes,Yes,Somewhat easy,Physical health,2018
137,33,female,United States of America,Illinois,0,No,0,No,26-100,1.0,I don't know,No,No,No,Yes,Very easy,Physical health,2018
138,28,Nonbinary,United States of America,Illinois,0,Yes,1,Yes,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2018
139,34,female,United States of America,Illinois,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
140,29,f,Canada,NaN,0,Yes,1,Yes,26-100,1.0,Yes,Yes,No,No,I don't know,I don't know,Physical health,2018
141,28,female,United States of America,Massachusetts,0,Yes,1,Yes,500-1000,0.0,Yes,Yes,No,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2018
142,41,Male,Australia,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
143,38,Male,United States of America,Illinois,0,Yes,1,Maybe,More than 1000,1.0,Yes,No,Yes,Yes,I don't know,I don't know,Physical health,2018
144,37,"Male (or female, or both)",Netherlands,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
145,42,Male,United States of America,California,0,No,1,No,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2018
146,28,Female,United States of America,California,0,Yes,0,Maybe,100-500,1.0,Yes,No,Yes,No,I don't know,Somewhat easy,Same level of comfort for each,2018
147,30,male,United States of America,California,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,I don't know,Physical health,2018
148,25,Female,United Kingdom,NaN,0,No,1,Yes,6-25,1.0,Yes,Yes,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2018
149,54,Male,United Kingdom,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
150,24,male,United Kingdom,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
151,32,male,United Kingdom,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018
152,44,Male,United States of America,California,0,Yes,1,No,More than 1000,1.0,Yes,Yes,No,Yes,I don't know,Difficult,Same level of comfort for each,2018
153,28,Trans man,United States of America,Ohio,0,Yes,1,Yes,500-1000,0.0,Yes,No,No,No,I don't know,I don't know,Physical health,2018

In [23]:
df_2019_cleaned

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_vs_physical,survey_year
0,25,Male,United States of America,Nebraska,False,No,False,Yes,26-100,True,I don't know,No,Yes,Yes,I don't know,Very easy,Physical health,2019
1,51,male,United States of America,Nebraska,False,Yes,False,Maybe,26-100,True,Yes,No,No,Yes,Yes,I don't know,Physical health,2019
2,27,Male,United States of America,Illinois,False,I don't know,False,No,26-100,True,I don't know,No,No,I don't know,I don't know,Somewhat difficult,Same level of comfort for each,2019
3,37,male,United States of America,Nebraska,False,Yes,False,Yes,100-500,True,I don't know,No,Yes,Yes,Yes,Very easy,Physical health,2019
4,46,m,United States of America,Nebraska,False,No,False,No,26-100,True,I don't know,No,I don't know,I don't know,I don't know,I don't know,Physical health,2019
5,36,female,United States of America,Nebraska,False,Yes,True,No,100-500,True,Yes,No,No,No,I don't know,Somewhat difficult,Physical health,2019
6,39,Female,United States of America,Nebraska,False,Yes,True,Maybe,26-100,True,Yes,Yes,No,I don't know,Yes,Somewhat easy,Physical health,2019
7,35,Male,United States of America,Wisconsin,True,Yes,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
8,49,NaN,United Kingdom,NaN,False,No,False,Yes,26-100,True,Yes,No,Yes,Yes,Yes,Very easy,Same level of comfort for each,2019
9,45,Male,United Kingdom,NaN,False,I don't know,True,Yes,6-25,True,I don't know,NaN,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2019
10,40,M,United Kingdom,NaN,False,No,True,Yes,100-500,True,Yes,Yes,No,I don't know,Yes,Very easy,Same level of comfort for each,2019
11,37,male,Netherlands,NaN,True,No,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
12,31,Male,United States of America,Connecticut,False,Yes,True,Yes,More than 1000,True,I don't know,No,No,No,Yes,Somewhat easy,Physical health,2019
13,37,Male,United States of America,Georgia,False,Yes,True,Yes,500-1000,True,Yes,Yes,Yes,I don't know,I don't know,Somewhat difficult,Same level of comfort for each,2019
14,26,female,United States of America,Pennsylvania,False,No,True,No,100-500,True,Yes,Yes,Yes,I don't know,I don't know,Somewhat difficult,Physical health,2019
15,43,M,Canada,NaN,False,No,False,Maybe,100-500,False,Yes,Yes,No,Yes,Yes,Neither easy nor difficult,Physical health,2019
16,35,Male,United States of America,North Carolina,False,Yes,True,Yes,100-500,True,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2019
17,31,male,Turkey,NaN,True,Yes,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
18,32,F,United States of America,New York,False,Yes,False,Yes,100-500,True,Yes,No,Yes,I don't know,Yes,Very easy,Same level of comfort for each,2019
19,37,Male,United States of America,Wisconsin,False,I don't know,True,Maybe,More than 1000,True,Yes,Yes,Yes,Yes,I don't know,I don't know,Physical health,2019
20,41,Male,United States of America,Tennessee,False,I don't know,False,Maybe,6-25,True,I don't know,No,No,No,I don't know,Somewhat easy,Physical health,2019
21,40,f,United States of America,New York,False,Yes,True,Yes,100-500,True,Yes,Yes,Yes,Yes,I don't know,I don't know,Physical health,2019
22,37,male,United States of America,New York,False,I don't know,True,Yes,500-1000,True,I don't know,No,No,No,Yes,Neither easy nor difficult,Same level of comfort for each,2019
23,53,"Let's keep it simple and say ""male""",United States of America,Oregon,False,Yes,True,Maybe,100-500,True,Yes,Yes,Yes,Yes,I don't know,Neither easy nor difficult,Physical health,2019
24,29,male,United States of America,Tennessee,False,Yes,True,No,6-25,True,I don't know,No,No,No,I don't know,Very easy,Physical health,2019
25,37,Male,United States of America,New York,False,Yes,True,Yes,500-1000,True,I don't know,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2019
26,45,female,United States of America,Wisconsin,False,Yes,True,No,100-500,False,I don't know,No,No,I don't know,I don't know,Somewhat easy,Physical health,2019
27,26,Male,Netherlands,NaN,False,No,False,Yes,6-25,True,I don't know,No,No,I don't know,I don't know,Very easy,Same level of comfort for each,2019
28,28,Male,United States of America,Colorado,False,Yes,True,Yes,100-500,True,Yes,Yes,Yes,Yes,I don't know,Very easy,Physical health,2019
29,24,Female,United States of America,Massachusetts,False,I don't know,True,Yes,100-500,True,Yes,Yes,Yes,No,I don't know,I don't know,Physical health,2019
30,27,Male,United States of America,Tennessee,False,Yes,False,Maybe,100-500,True,Yes,Yes,No,I don't know,I don't know,Very easy,Physical health,2019
31,42,Male,United States of America,Florida,False,No,True,Yes,100-500,False,Yes,No,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2019
32,53,Female,United States of America,Minnesota,True,No,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
33,34,Male,United Kingdom,NaN,False,No,False,Yes,100-500,False,Not eligible for coverage / NA,NaN,Yes,No,I don't know,Very easy,Physical health,2019
34,23,Non-binary,United Kingdom,NaN,False,I don't know,True,Yes,500-1000,False,Yes,Yes,Yes,I don't know,I don't know,Somewhat easy,Physical health,2019
35,34,M,United States of America,Tennessee,False,I don't know,False,Maybe,More than 1000,False,I don't know,No,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2019
36,27,Male,United States of America,Tennessee,False,Yes,False,Yes,6-25,True,I don't know,No,No,No,Yes,Very easy,Same level of comfort for each,2019
37,31,Male,United States of America,New York,False,I don't know,True,No,100-500,True,Yes,Yes,No,I don't know,I don't know,Somewhat easy,Physical health,2019
38,30,Male,Belgium,NaN,True,No,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
39,58,Male,United States of America,Illinois,True,No,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
40,50,Male,United States of America,Tennessee,False,No,False,Yes,More than 1000,False,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,Physical health,2019
41,41,Male,United States of America,California,False,Yes,True,Yes,100-500,True,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2019
42,40,male,Croatia,NaN,False,No,False,No,26-100,True,I don't know,No,No,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2019
43,28,Male,Belgium,NaN,True,I don't know,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
44,49,Identify as male,United Kingdom,NaN,False,No,False,Maybe,1-5,True,Yes,Yes,No,Yes,Yes,Somewhat difficult,Physical health,2019
45,37,Male,United States of America,New York,False,Yes,True,Yes,More than 1000,False,I don't know,No,No,I don't know,I don't know,Very easy,Same level of comfort for each,2019
46,36,m,United States of America,Illinois,True,I don't know,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
47,52,Male,United States of America,Tennessee,False,No,True,Yes,6-25,False,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2019
48,33,NaN,Canada,NaN,False,I don't know,False,Yes,More than 1000,False,Yes,Yes,Yes,Yes,I don't know,Very easy,Physical health,2019
49,54,Female,Canada,NaN,True,I don't know,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
50,38,Male,United Kingdom,NaN,True,No,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
51,64,Male,United Kingdom,NaN,True,No,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
52,40,Male,United Kingdom,NaN,True,No,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
53,37,Male,United States of America,Michigan,False,I don't know,False,No,26-100,True,Yes,Yes,No,I don't know,I don't know,I don't know,Physical health,2019
54,53,Female,United States of America,Wyoming,False,No,True,Yes,More than 1000,False,I don't know,No,I don't know,Yes,I don't know,Somewhat difficult,Same level of comfort for each,2019
55,55,male,United Kingdom,NaN,False,I don't know,False,Maybe,6-25,True,No,NaN,No,No,I don't know,Somewhat easy,Same level of comfort for each,2019
56,30,Male,United States of America,Utah,False,Yes,True,Maybe,6-25,True,I don't know,Yes,Yes,No,Yes,Somewhat difficult,Physical health,2019
57,35,Male,United States of America,California,False,Yes,True,No,500-1000,False,Yes,No,No,No,I don't know,Somewhat easy,Physical health,2019
58,60,Male,Canada,NaN,False,Yes,False,Maybe,More than 1000,False,Yes,Yes,I don't know,I don't know,Yes,Somewhat difficult,Physical health,2019
59,34,female,United States of America,Colorado,False,No,False,Maybe,100-500,False,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2019
60,35,Male,United States of America,Colorado,False,Yes,True,No,More than 1000,False,No,No,No,No,I don't know,Difficult,Physical health,2019
61,34,Male,United States of America,Tennessee,False,Yes,True,No,More than 1000,False,Yes,No,No,No,I don't know,Somewhat difficult,Physical health,2019
62,28,Male,United States of America,Colorado,False,Yes,False,Yes,26-100,True,I don't know,No,No,No,Yes,Very easy,Physical health,2019
63,28,Woman,United States of America,Colorado,False,Yes,True,Maybe,26-100,True,I don't know,No,No,No,I don't know,Neither easy nor difficult,Physical health,2019
64,36,NaN,United Kingdom,NaN,False,No,False,Maybe,26-100,True,I don't know,Yes,No,No,Yes,Somewhat difficult,Same level of comfort for each,2019
65,24,Male,Ghana,NaN,False,I don't know,False,Yes,6-25,True,No,No,No,No,No,Somewhat difficult,Same level of comfort for each,2019
66,50,Male,United States of America,Colorado,True,I don't know,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
67,55,Male,United States of America,Colorado,False,I don't know,True,No,More than 1000,True,Yes,No,No,Yes,I don't know,I don't know,Physical health,2019
68,32,Male,Norway,NaN,False,No,True,Yes,26-100,True,Yes,Yes,No,I don't know,Yes,Neither easy nor difficult,Same level of comfort for each,2019
69,33,Male,United States of America,California,False,I don't know,True,Yes,500-1000,True,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,Same level of comfort for each,2019
70,30,Female,Portugal,NaN,False,Yes,True,Maybe,500-1000,True,Yes,Yes,No,No,I don't know,I don't know,Physical health,2019
71,30,Male,Portugal,NaN,False,Yes,False,Yes,500-1000,True,Yes,No,No,I don't know,Yes,Very easy,Same level of comfort for each,2019
72,34,Male,Portugal,NaN,False,I don't know,False,Maybe,100-500,True,Yes,Yes,Yes,No,I don't know,I don't know,Physical health,2019
73,36,Female,Portugal,NaN,False,Yes,True,Yes,100-500,True,No,No,No,No,I don't know,Very easy,Physical health,2019
74,30,Male,Portugal,NaN,False,Yes,True,Maybe,100-500,True,No,NaN,No,No,I don't know,Somewhat easy,Physical health,2019
75,29,Male,Portugal,NaN,False,No,False,No,1-5,True,No,NaN,Yes,No,No,I don't know,Physical health,2019
76,34,M,Portugal,NaN,False,Yes,True,Yes,500-1000,True,No,No,No,No,No,Somewhat easy,Physical health,2019
77,40,M,Portugal,NaN,False,No,True,Yes,100-500,True,No,Yes,No,No,No,Very easy,Same level of comfort for each,2019
78,31,Non binary,Portugal,NaN,False,I don't know,False,No,500-1000,True,Not eligible for coverage / NA,NaN,No,No,I don't know,I don't know,Physical health,2019
79,27,Masculine,Portugal,NaN,False,Yes,False,Maybe,100-500,True,I don't know,No,No,I don't know,Yes,I don't know,Physical health,2019
80,47,M,United States of America,Alabama,False,Yes,False,Yes,More than 1000,False,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2019
81,24,Female,United States of America,Colorado,False,Yes,True,Maybe,100-500,False,Yes,Yes,No,Yes,Yes,Difficult,Physical health,2019
82,36,Male,Portugal,NaN,False,No,True,Yes,100-500,True,Yes,Yes,No,No,Yes,Somewhat easy,Physical health,2019
83,28,male,Portugal,NaN,False,I don't know,False,Maybe,100-500,True,I don't know,No,No,I don't know,I don't know,Neither easy nor difficult,Physical health,2019
84,34,Male,United Kingdom,NaN,False,No,False,Maybe,500-1000,True,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2019
85,28,Male,Portugal,NaN,False,No,False,Yes,100-500,True,I don't know,No,No,No,I don't know,Somewhat easy,Physical health,2019
86,36,M,Portugal,NaN,False,Yes,True,No,500-1000,True,Yes,Yes,No,No,I don't know,I don't know,Physical health,2019
87,24,male,Portugal,NaN,False,I don't know,False,Yes,100-500,True,Yes,Yes,I don't know,No,Yes,Somewhat easy,Physical health,2019
88,32,Cishet male,United States of America,Colorado,False,Yes,True,Maybe,6-25,True,Yes,Yes,No,No,Yes,I don't know,Physical health,2019
89,33,Male,United Kingdom,NaN,False,I don't know,True,Maybe,26-100,False,No,No,Yes,No,Yes,Very easy,Physical health,2019
90,39,Male,United States of America,California,False,I don't know,True,Maybe,100-500,True,I don't know,No,I don't know,I don't know,I don't know,Somewhat easy,Physical health,2019
91,26,female,United States of America,Colorado,False,I don't know,True,No,More than 1000,False,Yes,Yes,No,Yes,I don't know,I don't know,Physical health,2019
92,32,Female,United States of America,Michigan,False,Yes,True,Maybe,100-500,True,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2019
93,42,Male,United Kingdom,NaN,False,I don't know,True,Yes,26-100,True,Yes,No,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2019
94,41,M,United States of America,Indiana,False,I don't know,False,No,More than 1000,True,Yes,Yes,No,Yes,I don't know,I don't know,Physical health,2019
95,32,Male,Canada,NaN,False,Yes,True,No,100-500,True,Yes,Yes,Yes,No,I don't know,Somewhat difficult,Same level of comfort for each,2019
96,32,F,United States of America,North Carolina,False,Yes,True,No,More than 1000,False,No,Yes,No,Yes,I don't know,I don't know,Physical health,2019
97,31,Female,United States of America,California,False,Yes,True,Yes,100-500,True,Yes,No,I don't know,Yes,I don't know,Very easy,Same level of comfort for each,2019
98,34,Non-binary,Switzerland,NaN,False,Yes,True,Maybe,100-500,True,Not eligible for coverage / NA,NaN,No,No,I don't know,Somewhat easy,Physical health,2019
99,36,NaN,United Kingdom,NaN,False,Yes,False,No,More than 1000,True,Yes,No,Yes,Yes,I don't know,Difficult,Physical health,2019
100,33,male,Switzerland,NaN,False,No,False,Yes,100-500,True,I don't know,No,Yes,I don't know,Yes,Very easy,Physical health,2019
101,30,male,United States of America,Tennessee,False,Yes,True,Maybe,26-100,True,I don't know,No,No,I don't know,Yes,Somewhat easy,Physical health,2019
102,45,Female,United States of America,Vermont,False,Yes,True,Maybe,26-100,True,I don't know,Yes,No,No,I don't know,Difficult,Physical health,2019
103,30,Male,United States of America,Minnesota,False,No,False,Yes,More than 1000,True,Yes,No,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2019
104,48,Male,United Kingdom,NaN,True,Yes,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
105,29,Male,Portugal,NaN,False,I don't know,False,No,100-500,True,Yes,No,No,No,I don't know,Somewhat difficult,Physical health,2019
106,35,Female-identified,Canada,NaN,True,I don't know,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
107,41,Male,United States of America,Indiana,False,I don't know,True,No,100-500,True,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,2019
108,27,F,United States of America,Indiana,False,Yes,False,Maybe,26-100,False,Yes,Yes,No,No,Yes,Neither easy nor difficult,Same level of comfort for each,2019
109,42,Male,United States of America,Nebraska,False,I don't know,True,Yes,6-25,True,Yes,Yes,No,Yes,Yes,Very easy,Same level of comfort for each,2019
110,32,male,United States of America,Kansas,False,Yes,True,Yes,100-500,True,I don't know,No,No,No,I don't know,I don't know,Physical health,2019
111,32,Male,United States of America,Nebraska,False,No,False,Yes,100-500,True,I don't know,No,I don't know,I don't know,I don't know,Very easy,Physical health,2019
112,20,Woman,United States of America,Nebraska,False,Yes,True,No,1-5,True,Yes,Yes,No,No,Yes,Very easy,Same level of comfort for each,2019
113,24,woman,United States of America,Georgia,True,Yes,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019
114,0,male,United States of America,Nebraska,False,No,False,Yes,500-1000,False,I don't know,No,Yes,I don't know,I don't know,Very easy,Same level of comfort for each,2019
115,38,Male,United States of America,Nebraska,False,No,False,Yes,26-100,True,I don't know,No,No,No,I don't know,Very easy,Physical health,2019
116,31,Male,United States of America,Nebraska,False,I don't know,True,Maybe,6-25,True,I don't know,Yes,No,No,I don't know,Neither easy nor difficult,Physical health,2019
117,26,M,United States of America,Alaska,False,Yes,True,No,26-100,True,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,Mental health,2019
118,40,Male,United States of America,Missouri,False,Yes,True,Yes,26-100,True,Yes,No,No,No,Yes,Somewhat easy,Physical health,2019
119,30,male,United States of America,Nebraska,False,Yes,True,Maybe,6-25,False,Yes,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2019
120,38,Male,United States of America,Nebraska,False,No,True,Maybe,26-100,False,Yes,Yes,No,I don't know,I don't know,Very easy,Physical health,2019
121,28,male,United States of America,Virginia,False,No,True,Yes,More than 1000,True,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Same level of comfort for each,2019
122,28,Female,Pakistan,NaN,False,No,False,No,More than 1000,False,Not eligible for coverage / NA,No,No,No,I don't know,Somewhat difficult,Physical health,2019
123,30,Male,United States of America,Washington,False,Yes,True,No,More than 1000,True,Yes,No,No,Yes,I don't know,I don't know,Physical health,2019
124,23,Nonbinary,United States of America,Minnesota,False,Yes,True,Yes,More than 1000,False,Yes,Yes,Yes,Yes,I don't know,Neither easy nor difficult,Same level of comfort for each,2019
125,30,male,United States of America,Georgia,False,I don't know,False,Yes,More than 1000,True,I don't know,No,No,No,I don't know,I don't know,Same level of comfort for each,2019
126,33,female,United States of America,Oregon,False,Yes,True,Yes,More than 1000,False,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Same level of comfort for each,2019
127,53,Female,United States of America,Washington,False,Yes,True,No,500-1000,False,Yes,Yes,No,No,Yes,Somewhat difficult,Same level of comfort for each,2019
128,38,Male,United States of America,Washington,False,I don't know,True,Maybe,More than 1000,False,Yes,Yes,Yes,I don't know,Yes,Neither easy nor difficult,Physical health,2019
129,34,male,Poland,NaN,False,No,False,Maybe,26-100,True,No,NaN,No,No,I don't know,Somewhat easy,Same level of comfort for each,2019
130,40,Male,United States of America,Kansas,False,I don't know,False,Yes,More than 1000,False,I don't know,No,No,I don't know,I don't know,Somewhat easy,Physical health,2019
131,42,Male,United States of America,Florida,False,Yes,False,Yes,More than 1000,True,Yes,No,No,I don't know,I don't know,I don't know,Physical health,2019
132,42,Male,United States of America,Illinois,False,I don't know,True,Yes,6-25,True,Yes,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2019
133,38,Male,Canada,NaN,False,I don't know,True,Maybe,26-100,False,Yes,Yes,No,Yes,I don't know,I don't know,Physical health,2019
134,33,agender,United States of America,Washington,False,Yes,True,Maybe,More than 1000,False,Yes,Yes,No,Yes,Yes,Somewhat easy,Physical health,2019
135,35,Male,United States of America,Ohio,False,Yes,True,Maybe,100-500,True,Yes,Yes,I don't know,I don't know,Yes,I don't know,Physical health,2019
136,27,Female,Spain,NaN,False,I don't know,False,No,100-500,True,No,NaN,No,No,I don't know,Somewhat easy,Physical health,2019
137,28,Female,Turkey,NaN,False,No,False,Yes,More than 1000,False,Not eligible for coverage / NA,Yes,Yes,No,I don't know,Somewhat easy,Same level of comfort for each,2019
138,42,Male,India,NaN,False,No,True,No,More than 1000,True,No,No,No,No,No,Somewhat easy,Mental health,2019
139,35,f,Brazil,NaN,False,I don't know,False,Maybe,More than 1000,True,I don't know,NaN,No,No,I don't know,I don't know,Same level of comfort for each,2019

In [24]:
df_2020_cleaned

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_vs_physical,survey_year
0,45,Male,United States of America,Connecticut,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
1,24,female,Russia,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
2,46,Male,India,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
3,25,Female,Canada,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
4,25,F,Canada,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
5,5,f,United States of America,Alabama,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
6,1,NaN,Japan,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
7,35,Male,United States of America,Minnesota,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
8,34,female,Ireland,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
9,23,Female,Turkey,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
10,42,female,United States of America,South Dakota,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
11,54,male,United States of America,California,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
12,40,Female,Canada,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
13,36,Female,United States of America,California,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
14,30,male,Australia,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
15,22,male,Mongolia,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
16,21,Female,United States of America,Illinois,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
17,46,male,United States of America,New York,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
18,63,Male,United Kingdom,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
19,20,Male,Cameroon,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
20,24,mail,Pakistan,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
21,44,Male,Brazil,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
22,35,male,India,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
23,30,Female,Australia,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
24,23,Female,Russia,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020
25,26,male,United States of America,Massachusetts,0,Yes,0,Yes,More than 1000,0.0,Yes,No,Yes,Yes,I don't know,Very easy,Physical health,2020
26,32,Male,India,NaN,0,No,0,Maybe,500-1000,1.0,No,No,I don't know,Yes,I don't know,Somewhat easy,Mental health,2020
27,34,Male,United States of America,Washington,0,I don't know,0,No,6-25,1.0,I don't know,No,No,No,I don't know,Very easy,Physical health,2020
28,44,female,United States of America,Florida,0,Yes,1,Yes,26-100,1.0,Yes,Yes,I don't know,I don't know,I don't know,Somewhat easy,Physical health,2020
29,33,M,India,NaN,0,No,1,No,500-1000,1.0,No,No,No,Yes,Yes,Difficult,Physical health,2020
30,38,Male,Philippines,NaN,0,I don't know,1,Maybe,More than 1000,1.0,Yes,No,Yes,Yes,Yes,Neither easy nor difficult,Physical health,2020
31,45,m,United States of America,Georgia,0,No,0,Yes,More than 1000,0.0,I don't know,No,No,No,Yes,Somewhat difficult,Mental health,2020
32,27,F,India,NaN,0,No,0,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2020
33,21,male,Sri Lanka,NaN,0,I don't know,0,Maybe,26-100,1.0,I don't know,No,I don't know,No,Yes,Somewhat easy,Same level of comfort for each,2020
34,30,Female,United States of America,Washington,0,No,0,No,More than 1000,1.0,I don't know,No,No,No,I don't know,Neither easy nor difficult,Physical health,2020
35,44,Male,India,NaN,0,No,0,Yes,More than 1000,0.0,I don't know,No,No,No,Yes,Somewhat difficult,Same level of comfort for each,2020
36,32,Male,Brazil,NaN,0,No,0,No,More than 1000,0.0,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2020
37,39,f,India,NaN,0,No,0,No,More than 1000,1.0,Yes,No,Yes,Yes,Yes,Difficult,Physical health,2020
38,27,Woman,Poland,NaN,0,I don't know,1,No,100-500,0.0,No,Yes,No,No,I don't know,I don't know,Physical health,2020
39,34,Male,United States of America,New York,0,I don't know,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2020
40,30,male,Taiwan,NaN,0,No,0,No,26-100,1.0,No,No,No,No,I don't know,I don't know,Same level of comfort for each,2020
41,24,Male,Australia,NaN,0,I don't know,1,No,26-100,1.0,No,NaN,No,No,I don't know,Difficult,Physical health,2020
42,50,Male,India,NaN,0,No,0,No,More than 1000,1.0,Not eligible for coverage / NA,No,No,I don't know,I don't know,Difficult,Mental health,2020
43,27,Male,United States of America,New Mexico,0,No,0,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2020
44,28,Male,United Kingdom,NaN,0,Yes,1,No,100-500,1.0,Yes,No,Yes,I don't know,Yes,Somewhat easy,Physical health,2020
45,27,female,India,NaN,0,No,0,No,More than 1000,1.0,I don't know,No,No,No,I don't know,Difficult,Same level of comfort for each,2020
46,34,Male,United States of America,New York,0,Yes,1,Maybe,500-1000,1.0,I don't know,No,No,No,Yes,Difficult,Physical health,2020
47,42,M,India,NaN,0,I don't know,0,No,100-500,1.0,No,No,No,No,I don't know,Neither easy nor difficult,Physical health,2020
48,22,NaN,Indonesia,NaN,0,No,0,Maybe,500-1000,1.0,Yes,Yes,Yes,Yes,No,Somewhat easy,Same level of comfort for each,2020
49,28,female,India,NaN,0,No,0,No,100-500,1.0,No,No,No,No,No,Difficult,Physical health,2020
50,36,Male,United States of America,District of Columbia,0,No,0,Yes,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2020
51,41,Male,India,NaN,0,No,0,No,More than 1000,0.0,No,Yes,Yes,No,I don't know,Somewhat easy,Physical health,2020
52,30,male,United States of America,Washington,0,Yes,1,Maybe,6-25,1.0,Yes,Yes,No,No,I don't know,Somewhat difficult,Physical health,2020
53,34,male,Australia,NaN,0,I don't know,0,Maybe,100-500,0.0,I don't know,No,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2020
54,23,female,Germany,NaN,0,No,0,No,More than 1000,0.0,I don't know,No,Yes,No,I don't know,Somewhat easy,Physical health,2020
55,29,female,Brazil,NaN,0,No,0,Maybe,More than 1000,0.0,No,NaN,No,No,I don't know,Somewhat difficult,Mental health,2020
56,58,male,United States of America,Indiana,0,No,1,No,500-1000,0.0,Yes,Yes,No,Yes,Yes,Somewhat easy,Physical health,2020
57,40,Male,Netherlands,NaN,0,No,0,Maybe,100-500,0.0,I don't know,No,No,No,I don't know,I don't know,Physical health,2020
58,32,Male,Chile,NaN,0,Yes,1,No,100-500,1.0,Not eligible for coverage / NA,No,No,No,I don't know,Difficult,Physical health,2020
59,30,Male,Portugal,NaN,0,Yes,0,Maybe,100-500,1.0,I don't know,No,I don't know,I don't know,I don't know,Neither easy nor difficult,Physical health,2020
60,33,FEMALE,United States of America,Michigan,0,Yes,1,Yes,500-1000,0.0,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Same level of comfort for each,2020
61,22,f,Netherlands,NaN,0,No,1,Yes,26-100,0.0,I don't know,No,No,Yes,Yes,Somewhat difficult,Mental health,2020
62,30,F,United States of America,Massachusetts,0,No,1,Maybe,More than 1000,1.0,Yes,No,I don't know,Yes,Yes,Very easy,Physical health,2020
63,34,Male,South Africa,NaN,0,Yes,1,No,6-25,1.0,No,NaN,No,No,No,Difficult,Same level of comfort for each,2020
64,44,Male,United States of America,Indiana,0,I don't know,1,Yes,6-25,0.0,Yes,No,Yes,Yes,I don't know,Neither easy nor difficult,Physical health,2020
65,30,Male,United States of America,Illinois,0,I don't know,1,Maybe,26-100,1.0,Yes,Yes,No,I don't know,I don't know,Very easy,Physical health,2020
66,39,Male,United States of America,New York,0,I don't know,1,No,100-500,0.0,Yes,Yes,Yes,Yes,Yes,Difficult,Physical health,2020
67,48,M,India,NaN,0,No,0,Maybe,500-1000,1.0,Yes,Yes,No,No,I don't know,Somewhat difficult,Physical health,2020
68,26,Male,United States of America,Tennessee,0,Yes,1,No,26-100,0.0,I don't know,No,No,No,I don't know,Difficult,Physical health,2020
69,28,female,Germany,NaN,0,Yes,1,Maybe,26-100,0.0,I don't know,Yes,No,Yes,Yes,Somewhat easy,Physical health,2020
70,36,Male,United States of America,Alaska,0,I don't know,1,Yes,More than 1000,1.0,Yes,No,I don't know,I don't know,Yes,Somewhat easy,Physical health,2020
71,37,Male,Canada,NaN,0,No,0,Maybe,6-25,1.0,I don't know,No,No,No,I don't know,Very easy,Physical health,2020
72,42,Male,United States of America,Washington,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat difficult,Physical health,2020
73,31,Male,Brazil,NaN,0,Yes,1,No,More than 1000,1.0,Yes,Yes,No,No,I don't know,I don't know,Physical health,2020
74,22,male,Spain,NaN,0,I don't know,0,Yes,More than 1000,0.0,I don't know,NaN,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2020
75,40,male,Spain,NaN,0,Yes,1,No,100-500,1.0,I don't know,No,No,No,No,Very easy,Same level of comfort for each,2020
76,50,M,United States of America,Florida,0,No,0,No,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Neither easy nor difficult,Physical health,2020
77,31,female,India,NaN,0,No,0,Maybe,More than 1000,1.0,I don't know,No,Yes,I don't know,I don't know,Difficult,Physical health,2020
78,29,"female, she/her",Canada,NaN,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2020
79,40,Male,India,NaN,0,No,0,No,100-500,0.0,No,No,No,No,I don't know,Somewhat difficult,Physical health,2020
80,33,female,Canada,NaN,0,No,0,Maybe,More than 1000,0.0,No,No,No,No,I don't know,Somewhat difficult,Physical health,2020
81,29,Male,Sweden,NaN,0,No,0,No,26-100,1.0,I don't know,No,I don't know,No,I don't know,Somewhat easy,Physical health,2020
82,27,female,United States of America,Massachusetts,0,No,0,Maybe,More than 1000,1.0,I don't know,No,Yes,Yes,I don't know,Very easy,Physical health,2020
83,36,Male,United States of America,Washington,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,I don't know,Yes,Somewhat easy,Same level of comfort for each,2020
84,33,Female,United States of America,Maine,0,No,0,Maybe,More than 1000,0.0,Yes,Yes,Yes,Yes,I don't know,I don't know,Physical health,2020
85,40,Male,Sweden,NaN,0,Yes,0,No,6-25,1.0,I don't know,NaN,No,No,I don't know,Somewhat easy,Physical health,2020
86,42,Male,Canada,NaN,0,Yes,0,Yes,26-100,1.0,Yes,Yes,Yes,Yes,Yes,I don't know,Same level of comfort for each,2020
87,31,Male,United Kingdom,NaN,0,Yes,1,Maybe,500-1000,1.0,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,2020
88,35,female,Mongolia,NaN,0,No,0,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Physical health,2020
89,46,male,United States of America,Florida,0,I don't know,1,Maybe,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2020
90,54,female,United States of America,Maryland,0,Yes,1,Yes,100-500,1.0,Yes,Yes,Yes,I don't know,I don't know,Somewhat easy,Physical health,2020
91,33,Male,India,NaN,0,No,0,Maybe,500-1000,0.0,I don't know,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2020
92,40,Female,India,NaN,0,I don't know,0,No,100-500,1.0,No,No,No,No,No,Difficult,Physical health,2020
93,23,Female,Serbia,NaN,0,No,0,Yes,100-500,0.0,I don't know,No,Yes,Yes,Yes,Neither easy nor difficult,Physical health,2020
94,32,Male,United States of America,Massachusetts,0,Yes,0,Maybe,500-1000,1.0,I don't know,No,No,No,I don't know,Neither easy nor difficult,Physical health,2020
95,26,Woman,United States of America,California,0,Yes,1,No,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Difficult,Physical health,2020
96,30,Male,Germany,NaN,0,No,0,Yes,More than 1000,0.0,Yes,No,Yes,No,Yes,Somewhat easy,Physical health,2020
97,30,Male,India,NaN,0,No,0,Maybe,More than 1000,1.0,No,NaN,Yes,I don't know,I don't know,Very easy,Same level of comfort for each,2020
98,44,male,United States of America,Arizona,0,No,1,Maybe,26-100,1.0,Yes,No,Yes,No,Yes,Somewhat easy,Same level of comfort for each,2020
99,37,Male,United States of America,Oregon,0,No,1,No,100-500,1.0,Not eligible for coverage / NA,No,I don't know,I don't know,I don't know,Somewhat difficult,Physical health,2020
100,37,Male,India,NaN,0,No,0,Yes,More than 1000,1.0,I don't know,No,No,No,No,Somewhat easy,Same level of comfort for each,2020
101,29,Female,Brazil,NaN,0,No,0,No,500-1000,1.0,Yes,No,Yes,No,I don't know,I don't know,Physical health,2020
102,39,male,United States of America,Texas,0,I don't know,1,Yes,26-100,1.0,Yes,No,No,No,I don't know,Very easy,Physical health,2020
103,20,Male,Spain,NaN,0,No,1,Maybe,6-25,1.0,I don't know,NaN,No,I don't know,I don't know,Very easy,Same level of comfort for each,2020
104,44,Male,United States of America,Tennessee,0,No,0,No,100-500,1.0,I don't know,No,No,I don't know,I don't know,Neither easy nor difficult,Physical health,2020
105,23,male,Egypt,NaN,0,No,0,No,26-100,1.0,No,Yes,No,No,No,I don't know,Physical health,2020
106,22,Female,United States of America,Washington,0,Yes,0,Yes,More than 1000,1.0,Yes,No,Yes,Yes,Yes,Very easy,Physical health,2020
107,31,female,United States of America,Washington,0,No,0,No,More than 1000,1.0,I don't know,No,No,Yes,I don't know,I don't know,Physical health,2020
108,59,male,United States of America,Utah,0,I don't know,1,Maybe,26-100,0.0,Yes,Yes,Yes,Yes,Yes,Neither easy nor difficult,Physical health,2020
109,30,Female,India,NaN,0,No,0,No,More than 1000,0.0,No,NaN,Yes,Yes,Yes,Somewhat difficult,Physical health,2020
110,48,F,United States of America,Indiana,0,Yes,1,Yes,26-100,0.0,Yes,Yes,Yes,No,Yes,Somewhat easy,Physical health,2020
111,30,female,India,NaN,0,No,1,No,More than 1000,1.0,I don't know,No,I don't know,I don't know,Yes,Somewhat difficult,Physical health,2020
112,23,male,Germany,NaN,0,No,0,No,More than 1000,1.0,Yes,Yes,No,No,Yes,Neither easy nor difficult,Physical health,2020
113,27,Male,United States of America,California,0,No,0,No,500-1000,0.0,Yes,No,No,No,Yes,Somewhat easy,Physical health,2020
114,53,female,United States of America,Washington,0,Yes,1,No,26-100,1.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2020
115,62,Male,United States of America,New York,0,No,0,Maybe,500-1000,0.0,I don't know,NaN,No,I don't know,I don't know,Somewhat easy,Physical health,2020
116,32,mostly male,United States of America,Vermont,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,No,I don't know,I don't know,Difficult,Physical health,2020
117,34,Male,India,NaN,0,No,1,Maybe,More than 1000,1.0,No,No,No,No,I don't know,I don't know,Physical health,2020
118,29,male,India,NaN,0,Yes,0,No,More than 1000,0.0,I don't know,No,No,No,I don't know,Somewhat easy,Physical health,2020
119,32,Female,India,NaN,0,No,0,Yes,More than 1000,0.0,I don't know,NaN,I don't know,I don't know,I don't know,Neither easy nor difficult,Physical health,2020
120,46,Male,Brazil,NaN,0,No,0,Yes,500-1000,0.0,No,No,No,No,Yes,Somewhat easy,Same level of comfort for each,2020
121,42,male,Netherlands,NaN,0,Yes,1,Yes,More than 1000,1.0,No,NaN,No,No,No,Very easy,Same level of comfort for each,2020
122,32,Male,Ukraine,NaN,0,I don't know,1,No,26-100,1.0,No,NaN,No,No,No,Somewhat difficult,Physical health,2020
123,28,male,Iceland,NaN,0,Yes,1,Yes,More than 1000,0.0,I don't know,Yes,No,I don't know,I don't know,Very easy,Same level of comfort for each,2020
124,45,Male,United States of America,Wisconsin,0,Yes,1,Yes,6-25,1.0,No,NaN,Yes,I don't know,Yes,Very easy,Physical health,2020
125,29,Female,Spain,NaN,0,No,1,Maybe,26-100,1.0,No,NaN,No,I don't know,Yes,Somewhat easy,Same level of comfort for each,2020
126,27,M,Colombia,NaN,0,No,1,No,More than 1000,0.0,Yes,Yes,Yes,No,I don't know,I don't know,Physical health,2020
127,47,male,Netherlands,NaN,0,No,1,Yes,6-25,1.0,No,NaN,No,No,I don't know,Very easy,Same level of comfort for each,2020
128,24,Female,Philippines,NaN,0,I don't know,0,Maybe,100-500,1.0,I don't know,No,Yes,Yes,I don't know,Very easy,Physical health,2020
129,32,female,United States of America,Georgia,0,Yes,1,No,More than 1000,0.0,Yes,Yes,No,Yes,I don't know,I don't know,Physical health,2020
130,26,Male,United States of America,Illinois,0,I don't know,0,No,100-500,0.0,Yes,Yes,Yes,No,I don't know,Somewhat easy,Same level of comfort for each,2020
131,34,male,Germany,NaN,0,Yes,1,Yes,100-500,0.0,No,NaN,No,No,Yes,Very easy,Physical health,2020
132,45,cisgender male,United States of America,Georgia,0,I don't know,0,Yes,26-100,1.0,Yes,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2020
133,21,Female,United States of America,Washington,0,No,0,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,I don't know,Physical health,2020
134,44,Female,India,NaN,0,No,0,No,100-500,0.0,No,No,No,No,I don't know,Difficult,Physical health,2020
135,47,male,India,NaN,0,No,0,No,More than 1000,1.0,I don't know,No,I don't know,Yes,I don't know,Neither easy nor difficult,Physical health,2020
136,40,Male,Brazil,NaN,0,Yes,0,Maybe,More than 1000,1.0,Not eligible for coverage / NA,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2020
137,25,Female,Malaysia,NaN,0,No,0,No,100-500,0.0,I don't know,No,I don't know,I don't know,I don't know,Somewhat easy,Physical health,2020
138,24,Female,United States of America,North Carolina,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,I don't know,I don't know,Difficult,Physical health,2020
139,26,female,Indonesia,NaN,0,No,0,Maybe,More than 1000,1.0,Yes,No,Yes,Yes,I don't know,I don't know,Physical health,2020
140,31,male,South Africa,NaN,0,I don't know,0,No,6-25,1.0,No,NaN,No,No,No,Difficult,Physical health,2020
141,26,female,Poland,NaN,0,No,0,No,500-1000,1.0,No,NaN,Yes,No,I don't know,Somewhat difficult,Physical health,2020
142,32,Male,India,NaN,0,No,0,No,More than 1000,0.0,I don't know,No,Yes,Yes,Yes,Neither easy nor difficult,Physical health,2020
143,33,Female,India,NaN,0,No,0,No,More than 1000,0.0,I don't know,No,Yes,Yes,I don't know,Somewhat difficult,Physical health,2020
144,42,F,United States of America,Minnesota,0,Yes,1,Maybe,500-1000,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2020
145,46,Male,United Kingdom,NaN,0,Yes,1,Yes,100-500,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2020
146,30,m,United States of America,New York,0,No,1,Maybe,More than 1000,1.0,Yes,No,Yes,No,I don't know,I don't know,Same level of comfort for each,2020
147,24,Male,India,NaN,0,I don't know,1,No,More than 1000,1.0,No,No,Yes,Yes,I don't know,Neither easy nor difficult,Same level of comfort for each,2020
148,42,m,India,NaN,0,No,0,Maybe,26-100,0.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2020
149,28,male,India,NaN,0,No,0,No,More than 1000,0.0,I don't know,No,No,I don't know,I don't know,Neither easy nor difficult,Physical health,2020
150,27,Female,United States of America,Georgia,0,No,0,No,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2020
151,62,Male,United States of America,Washington,0,No,0,Yes,More than 1000,0.0,Yes,No,Yes,Yes,Yes,Very easy,Physical health,2020
152,34,male,Turkey,NaN,0,No,1,No,More than 1000,0.0,No,No,No,No,I don't know,Difficult,Physical health,2020
153,38,Male,Spain,NaN,0,No,1,Yes,500-1000,1.0,I don't know,No,Yes,No,Yes,Very easy,Physical health,2020
154,42,Male,Spain,NaN,0,Yes,1,Yes,26-100,1.0,Not eligible for coverage / NA,NaN,Yes,Yes,Yes,Very easy,Physical health,2020
155,35,male,United States of America,Massachusetts,0,No,0,Maybe,More than 1000,1.0,I don't know,No,Yes,Yes,Yes,Very easy,Same level of comfort for each,2020
156,32,Male,United Kingdom,NaN,0,No,1,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2020
157,32,Female,United States of America,Texas,0,No,0,No,26-100,1.0,No,No,No,No,I don't know,Somewhat difficult,Physical health,2020
158,25,female,Sri Lanka,NaN,0,No,0,Yes,26-100,1.0,No,No,No,No,No,Somewhat easy,Physical health,2020
159,52,Male,Australia,NaN,0,No,0,Yes,More than 1000,0.0,No,NaN,Yes,I don't know,I don't know,Very easy,Same level of comfort for each,2020
160,24,F,France,NaN,0,I don't know,0,Yes,More than 1000,0.0,No,No,No,No,No,Difficult,Physical health,2020

In [25]:
df_2021_cleaned

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_vs_physical,survey_year
0,28,Female,United States of America,Alaska,0,I don't know,0,Maybe,26-100,1.0,I don't know,No,No,I don't know,I don't know,Very easy,Physical health,2021
1,41,male,Brazil,NaN,0,No,0,No,500-1000,1.0,Yes,No,Yes,Yes,Yes,I don't know,Physical health,2021
2,35,Male,Brazil,NaN,0,No,0,Maybe,100-500,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2021
3,20,male,Italy,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
4,35,female,Canada,NaN,0,No,1,No,More than 1000,0.0,Yes,No,Yes,Yes,I don't know,Difficult,Physical health,2021
5,30,Female,United States of America,New York,0,No,0,No,6-25,1.0,No,No,No,No,No,Difficult,Same level of comfort for each,2021
6,34,female,United States of America,Maryland,0,No,0,Yes,More than 1000,1.0,No,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2021
7,23,female,Germany,NaN,0,I don't know,0,Maybe,More than 1000,0.0,Yes,Yes,No,No,I don't know,Very easy,Physical health,2021
8,19,Female,India,NaN,0,No,0,No,More than 1000,1.0,No,No,Yes,No,No,Somewhat difficult,Same level of comfort for each,2021
9,34,f,Belarus,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
10,25,Male,Germany,NaN,0,No,1,Maybe,More than 1000,0.0,Yes,No,Yes,Yes,Yes,Very easy,Physical health,2021
11,29,Male,India,NaN,0,No,0,No,26-100,1.0,No,NaN,No,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2021
12,40,F,Germany,NaN,0,No,0,No,26-100,0.0,No,No,No,No,No,Somewhat difficult,Physical health,2021
13,26,female,Macedonia,NaN,0,No,0,Yes,100-500,1.0,No,Yes,No,No,I don't know,Very easy,Same level of comfort for each,2021
14,25,Male,Macedonia,NaN,0,Yes,0,No,100-500,1.0,No,No,No,No,I don't know,Somewhat difficult,Physical health,2021
15,24,Female,Macedonia,NaN,0,No,0,No,26-100,1.0,Yes,NaN,I don't know,I don't know,Yes,Very easy,Physical health,2021
16,25,f,Slovenia,NaN,0,No,0,No,100-500,0.0,I don't know,No,No,Yes,Yes,Somewhat easy,Physical health,2021
17,22,Male,Albania,NaN,0,No,0,Maybe,26-100,1.0,No,No,No,No,No,Somewhat easy,Same level of comfort for each,2021
18,27,male,Macedonia,NaN,0,No,0,Maybe,26-100,1.0,I don't know,No,I don't know,I don't know,I don't know,Neither easy nor difficult,Physical health,2021
19,25,female,Slovenia,NaN,0,No,0,Yes,6-25,0.0,I don't know,No,I don't know,Yes,I don't know,Somewhat easy,Physical health,2021
20,25,Female,Slovenia,NaN,0,No,0,No,500-1000,1.0,Not eligible for coverage / NA,No,No,I don't know,I don't know,Difficult,Same level of comfort for each,2021
21,23,Male,Slovenia,NaN,0,No,0,Yes,1-5,1.0,No,No,Yes,No,Yes,Somewhat easy,Same level of comfort for each,2021
22,27,Female,Slovenia,NaN,0,No,0,Yes,More than 1000,0.0,I don't know,No,No,No,I don't know,I don't know,Same level of comfort for each,2021
23,33,Male,United States of America,Texas,0,Yes,1,Yes,More than 1000,0.0,I don't know,No,No,Yes,Yes,Difficult,Mental health,2021
24,22,Male,India,NaN,0,No,0,No,More than 1000,1.0,Yes,No,No,No,Yes,Somewhat difficult,Physical health,2021
25,45,woman,Austria,NaN,0,Yes,1,Yes,26-100,1.0,Yes,No,No,Yes,Yes,Very easy,Physical health,2021
26,25,Female,Macedonia,NaN,0,No,0,Yes,More than 1000,1.0,I don't know,No,No,No,I don't know,Very easy,Physical health,2021
27,22,Female,India,NaN,0,No,1,No,More than 1000,1.0,I don't know,No,Yes,Yes,Yes,Somewhat difficult,Physical health,2021
28,36,Female,United States of America,Colorado,0,Yes,1,No,500-1000,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat difficult,Physical health,2021
29,42,afab non-binary,United States of America,Texas,0,Yes,1,Yes,100-500,1.0,Yes,Yes,No,No,I don't know,Very easy,Mental health,2021
30,39,Male,India,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
31,51,Female,United States of America,Kansas,0,Yes,1,No,100-500,0.0,Yes,Yes,No,No,Yes,Difficult,Physical health,2021
32,27,Female,United States of America,Oklahoma,0,Yes,1,Maybe,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2021
33,19,Male,United States of America,Maryland,0,No,0,Maybe,100-500,0.0,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,2021
34,11,male,India,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
35,25,male,Kenya,NaN,0,No,0,Yes,6-25,0.0,Yes,Yes,I don't know,Yes,Yes,Neither easy nor difficult,Same level of comfort for each,2021
36,39,male,United States of America,Michigan,0,Yes,1,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,I don't know,Neither easy nor difficult,Physical health,2021
37,47,MALE,Australia,NaN,0,No,1,No,1-5,1.0,No,No,No,No,Yes,Somewhat difficult,Physical health,2021
38,223,NaN,United States of America,Alabama,0,Yes,1,Yes,1-5,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2021
39,36,Female,United States of America,Wisconsin,0,I don't know,1,No,More than 1000,0.0,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,Physical health,2021
40,57,Masculine,Brazil,NaN,0,I don't know,0,No,26-100,1.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2021
41,34,male,Brazil,NaN,0,I don't know,1,No,100-500,1.0,No,No,I don't know,No,I don't know,Very easy,Physical health,2021
42,26,Male,Brazil,NaN,0,Yes,1,Yes,More than 1000,1.0,No,No,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2021
43,24,Female,United States of America,Washington,0,Yes,1,Maybe,6-25,0.0,Yes,Yes,No,No,Yes,Somewhat easy,Same level of comfort for each,2021
44,26,Female (cis),United States of America,New York,0,I don't know,1,Yes,500-1000,0.0,Yes,Yes,Yes,Yes,Yes,I don't know,Physical health,2021
45,21,b,Sao Tome and Principe,NaN,0,I don't know,0,Maybe,100-500,1.0,I don't know,NaN,No,I don't know,I don't know,I don't know,Same level of comfort for each,2021
46,32,Female,India,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
47,25,female,Brazil,NaN,0,I don't know,1,No,500-1000,0.0,No,No,Yes,I don't know,I don't know,Very easy,Physical health,2021
48,31,Male,Brazil,NaN,0,No,1,Yes,100-500,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2021
49,28,Male,India,NaN,0,No,0,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2021
50,27,Female,United States of America,California,0,Yes,1,Maybe,More than 1000,1.0,I don't know,Yes,No,Yes,Yes,I don't know,Physical health,2021
51,36,Male,United States of America,Pennsylvania,0,I don't know,1,No,26-100,1.0,No,Yes,Yes,No,Yes,Somewhat easy,Same level of comfort for each,2021
52,40,female,United States of America,Ohio,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Somewhat easy,Same level of comfort for each,2021
53,27,Male,United States of America,California,0,Yes,0,No,500-1000,1.0,I don't know,No,No,I don't know,I don't know,Very easy,Same level of comfort for each,2021
54,25,female,Vietnam,NaN,0,Yes,0,Maybe,6-25,1.0,No,No,No,No,No,Neither easy nor difficult,Physical health,2021
55,31,Male,United States of America,California,0,No,1,No,100-500,1.0,Yes,Yes,Yes,Yes,Yes,Difficult,Physical health,2021
56,35,female,India,NaN,0,No,1,Yes,100-500,1.0,No,No,No,No,No,Somewhat easy,Same level of comfort for each,2021
57,22,m,India,NaN,0,No,0,No,100-500,1.0,Yes,No,Yes,No,I don't know,Very easy,Physical health,2021
58,42,male/he/him,United States of America,Maryland,0,Yes,1,Yes,More than 1000,1.0,Yes,No,No,No,I don't know,Difficult,Same level of comfort for each,2021
59,38,Male,India,NaN,0,No,0,No,More than 1000,1.0,No,No,I don't know,No,Yes,Somewhat easy,Same level of comfort for each,2021
60,38,female,United States of America,California,0,Yes,1,No,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2021
61,31,homem cis,Brazil,NaN,0,Yes,1,Yes,6-25,1.0,I don't know,No,No,No,I don't know,I don't know,Same level of comfort for each,2021
62,29,male,Germany,NaN,0,Yes,1,Maybe,More than 1000,0.0,Yes,NaN,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2021
63,44,Female,United States of America,New York,0,Yes,1,Maybe,26-100,1.0,Not eligible for coverage / NA,NaN,No,No,I don't know,Neither easy nor difficult,Physical health,2021
64,21,Male,Indonesia,NaN,0,No,1,No,6-25,1.0,I don't know,No,No,Yes,Yes,Neither easy nor difficult,Mental health,2021
65,63,male,India,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
66,30,woman,Switzerland,NaN,0,I don't know,0,Yes,More than 1000,0.0,No,No,Yes,Yes,Yes,Somewhat easy,Physical health,2021
67,33,male,United States of America,Virginia,0,Yes,0,Maybe,500-1000,0.0,Yes,Yes,Yes,Yes,I don't know,Neither easy nor difficult,Physical health,2021
68,43,Male,United States of America,California,0,I don't know,1,No,More than 1000,0.0,Yes,Yes,No,Yes,Yes,Somewhat difficult,Physical health,2021
69,20,m,Indonesia,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
70,21,male,Finland,NaN,0,Yes,1,No,100-500,1.0,No,No,No,No,I don't know,Somewhat difficult,Physical health,2021
71,22,male,United States of America,Alabama,0,I don't know,1,Maybe,26-100,0.0,Yes,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2021
72,23,female,India,NaN,0,No,0,Maybe,More than 1000,1.0,Yes,No,No,Yes,Yes,Somewhat difficult,Physical health,2021
73,34,Male,United States of America,Colorado,0,No,0,No,More than 1000,1.0,No,NaN,Yes,I don't know,I don't know,Difficult,Physical health,2021
74,27,woman,Turkey,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
75,25,Female,Poland,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
76,21,Female,United Kingdom,NaN,0,No,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,Physical health,2021
77,49,Male,United States of America,California,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2021
78,22,FEMALE,Nigeria,NaN,0,No,0,No,100-500,0.0,I don't know,NaN,I don't know,No,I don't know,Neither easy nor difficult,Physical health,2021
79,35,Female,United States of America,Washington,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,I don't know,I don't know,I don't know,Physical health,2021
80,25,female,Bulgaria,NaN,0,No,0,Yes,1-5,0.0,No,NaN,No,No,I don't know,Very easy,Same level of comfort for each,2021
81,38,Male,India,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
82,38,male,Estonia,NaN,0,No,0,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2021
83,30,M,India,NaN,0,No,0,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Neither easy nor difficult,Same level of comfort for each,2021
84,41,cis-het male,United States of America,California,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,I don't know,Physical health,2021
85,36,cis male,Colombia,NaN,0,I don't know,1,Maybe,26-100,1.0,Yes,No,No,No,I don't know,Somewhat difficult,Physical health,2021
86,23,Female,United States of America,Nebraska,0,I don't know,1,No,26-100,0.0,Yes,Yes,No,No,I don't know,Difficult,Same level of comfort for each,2021
87,21,male,United States of America,Iowa,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
88,25,Male,Netherlands,NaN,0,No,1,Maybe,6-25,0.0,I don't know,No,No,I don't know,Yes,Neither easy nor difficult,Physical health,2021
89,32,Male,Israel,NaN,0,No,0,No,6-25,1.0,No,No,No,No,I don't know,Somewhat easy,Physical health,2021
90,41,male,Israel,NaN,0,Yes,1,No,26-100,1.0,Not eligible for coverage / NA,NaN,No,No,I don't know,Somewhat difficult,Physical health,2021
91,23,Female,United States of America,Illinois,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
92,45,male,Canada,NaN,0,Yes,0,No,100-500,0.0,No,No,No,No,No,Neither easy nor difficult,Physical health,2021
93,23,Male,Bangladesh,NaN,0,No,0,No,More than 1000,1.0,No,No,No,No,Yes,Somewhat difficult,Physical health,2021
94,21,m,India,NaN,0,No,0,No,26-100,1.0,No,No,No,No,No,Somewhat difficult,Physical health,2021
95,51,Male,United States of America,New Mexico,0,Yes,1,No,More than 1000,0.0,Yes,No,Yes,Yes,I don't know,Somewhat difficult,Physical health,2021
96,21,Female,India,NaN,0,No,0,Maybe,More than 1000,1.0,I don't know,No,Yes,I don't know,I don't know,Very easy,Same level of comfort for each,2021
97,38,Male,United States of America,Georgia,0,Yes,1,No,100-500,1.0,Yes,Yes,No,No,Yes,Very easy,Physical health,2021
98,31,Female,United States of America,Oklahoma,0,No,1,Maybe,26-100,0.0,Yes,Yes,No,No,I don't know,Somewhat difficult,Same level of comfort for each,2021
99,24,Female,United Kingdom,NaN,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2021
100,29,M,United States of America,Alabama,0,Yes,1,Yes,100-500,1.0,Yes,Yes,Yes,I don't know,Yes,Neither easy nor difficult,Physical health,2021
101,27,Female,India,NaN,0,I don't know,1,No,500-1000,1.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2021
102,25,Female,United States of America,Virginia,0,I don't know,1,No,500-1000,1.0,I don't know,No,No,I don't know,Yes,I don't know,Same level of comfort for each,2021
103,47,woman,United States of America,North Carolina,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2021
104,30,Female,United States of America,North Carolina,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,I don't know,Same level of comfort for each,2021
105,33,female,United States of America,New Hampshire,0,Yes,1,Yes,More than 1000,1.0,I don't know,No,Yes,I don't know,Yes,I don't know,Physical health,2021
106,23,Non-binary,Australia,NaN,0,Yes,1,No,More than 1000,1.0,Yes,No,Yes,No,I don't know,Somewhat easy,Physical health,2021
107,37,Male,United States of America,Oregon,0,I don't know,1,Maybe,More than 1000,1.0,Yes,Yes,I don't know,Yes,Yes,I don't know,Physical health,2021
108,30,Female,United States of America,North Carolina,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2021
109,36,Non-binary/Agender,United States of America,North Carolina,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,I don't know,Same level of comfort for each,2021
110,42,Male,Greece,NaN,0,Yes,0,Maybe,100-500,1.0,No,No,No,No,Yes,Neither easy nor difficult,Physical health,2021
111,40,F,United States of America,California,0,No,0,Maybe,26-100,1.0,Yes,Yes,No,Yes,I don't know,I don't know,Physical health,2021
112,23,female,China,NaN,0,No,0,Maybe,More than 1000,1.0,I don't know,Yes,I don't know,No,I don't know,Neither easy nor difficult,Physical health,2021
113,45,Male,United States of America,New York,0,Yes,0,Maybe,100-500,1.0,I don't know,No,No,No,I don't know,Difficult,Physical health,2021
114,30,Male,India,NaN,0,No,0,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2021
115,34,female,Germany,NaN,0,Yes,0,No,More than 1000,0.0,I don't know,No,Yes,I don't know,I don't know,Very easy,Physical health,2021
116,45,Male,United States of America,Florida,0,Yes,0,Maybe,26-100,0.0,I don't know,No,No,No,No,Difficult,Physical health,2021
117,30,Female,United States of America,New York,0,Yes,1,Yes,100-500,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2021
118,22,F,India,NaN,0,Yes,0,No,More than 1000,0.0,I don't know,No,No,Yes,I don't know,Somewhat easy,Same level of comfort for each,2021
119,28,male,Italy,NaN,0,No,0,Yes,6-25,1.0,No,NaN,No,No,I don't know,Very easy,Same level of comfort for each,2021
120,37,Male,Italy,NaN,0,Yes,0,No,More than 1000,1.0,No,No,No,No,I don't know,Somewhat easy,Physical health,2021
121,23,Male,South Africa,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
122,35,Male,United States of America,Utah,0,I don't know,1,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2021
123,34,Male,Netherlands,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
124,46,Male,United States of America,Indiana,0,No,0,Yes,6-25,1.0,Yes,Yes,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2021
125,33,Male,Germany,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
126,33,Male,Germany,NaN,0,I don't know,1,Yes,26-100,1.0,No,No,No,No,I don't know,Somewhat easy,Physical health,2021
127,49,Male,Portugal,NaN,0,Yes,0,Maybe,100-500,1.0,No,NaN,I don't know,No,I don't know,Somewhat easy,Physical health,2021
128,28,NaN,Pakistan,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
129,26,Male,India,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021
130,38,male,Slovenia,NaN,0,No,1,Maybe,26-100,1.0,I don't know,No,No,No,No,Somewhat difficult,Physical health,2021

In [26]:
df_2022_cleaned

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_vs_physical,survey_year
0,23,female,Russia,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
1,43,Male,Netherlands,NaN,0,Yes,1,Yes,26-100,1.0,I don't know,No,No,No,I don't know,Very easy,Physical health,2022
2,38,male,Sweden,NaN,0,Yes,1,Yes,26-100,1.0,No,Yes,I don't know,I don't know,Yes,Somewhat easy,Physical health,2022
3,35,Female,United States of America,Oregon,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,I don't know,I don't know,Physical health,2022
4,33,Female,United Kingdom,NaN,0,Yes,1,Yes,26-100,1.0,Yes,No,Yes,Yes,Yes,Very easy,Same level of comfort for each,2022
5,26,female,Argentina,NaN,0,Yes,1,Yes,26-100,1.0,No,Yes,No,No,No,Very easy,Same level of comfort for each,2022
6,29,Male,United States of America,California,0,No,0,No,26-100,1.0,I don't know,No,No,No,I don't know,Neither easy nor difficult,Physical health,2022
7,45,F,Austria,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
8,34,F,France,NaN,0,No,1,No,100-500,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2022
9,35,Female,Canada,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
10,20,Cis male,United Kingdom,NaN,0,Yes,1,No,26-100,1.0,Yes,Yes,Yes,Yes,I don't know,Difficult,Same level of comfort for each,2022
11,34,male,Bosnia and Herzegovina,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
12,32,Male,United States of America,California,0,I don't know,1,Yes,26-100,1.0,Yes,No,No,No,I don't know,Very easy,Same level of comfort for each,2022
13,48,male,United States of America,Massachusetts,0,I don't know,1,No,More than 1000,0.0,Yes,Yes,Yes,Yes,I don't know,Difficult,Physical health,2022
14,32,"Female, cis-gendered",United States of America,North Carolina,0,Yes,1,Maybe,500-1000,1.0,Yes,Yes,Yes,Yes,Yes,Neither easy nor difficult,Physical health,2022
15,36,Male,United States of America,Massachusetts,0,I don't know,1,Maybe,26-100,1.0,Yes,Yes,Yes,Yes,I don't know,I don't know,Same level of comfort for each,2022
16,50,f,Jordan,NaN,0,No,1,No,100-500,0.0,No,NaN,No,Yes,Yes,Difficult,Physical health,2022
17,23,Female,United States of America,Texas,0,I don't know,1,No,100-500,0.0,Yes,Yes,Yes,Yes,Yes,Neither easy nor difficult,Mental health,2022
18,25,Male,India,NaN,0,Yes,1,No,100-500,1.0,Yes,No,Yes,No,No,Somewhat difficult,Physical health,2022
19,23,male,Spain,NaN,0,I don't know,0,Maybe,26-100,0.0,No,No,No,No,I don't know,Neither easy nor difficult,Physical health,2022
20,43,Male,Australia,NaN,0,No,1,Yes,More than 1000,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2022
21,53,male,Australia,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
22,27,M,Germany,NaN,0,I don't know,0,No,100-500,1.0,Yes,Yes,Yes,I don't know,I don't know,Difficult,Same level of comfort for each,2022
23,45,NaN,United States of America,Texas,0,Yes,1,No,More than 1000,1.0,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,2022
24,44,female,United States of America,Texas,0,I don't know,0,No,More than 1000,1.0,Yes,Yes,No,I don't know,I don't know,I don't know,Physical health,2022
25,39,male,United Kingdom,NaN,0,Yes,1,No,More than 1000,1.0,Yes,No,I don't know,I don't know,Yes,Very easy,Physical health,2022
26,23,Cis Male,Brazil,NaN,0,No,0,Yes,26-100,1.0,No,No,Yes,No,Yes,Somewhat easy,Same level of comfort for each,2022
27,34,Male,United States of America,Wisconsin,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
28,29,Male,India,NaN,0,No,1,Maybe,More than 1000,1.0,Yes,No,Yes,No,I don't know,Very easy,Same level of comfort for each,2022
29,22,female,India,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
30,30,Male,Canada,NaN,0,I don't know,1,Maybe,500-1000,0.0,Not eligible for coverage / NA,No,No,Yes,I don't know,Somewhat difficult,Physical health,2022
31,45,dude,United States of America,California,0,Yes,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Neither easy nor difficult,Same level of comfort for each,2022
32,33,Male,Vietnam,NaN,0,I don't know,0,Yes,500-1000,1.0,I don't know,NaN,Yes,Yes,I don't know,Somewhat easy,Same level of comfort for each,2022
33,44,Male,Germany,NaN,0,No,0,No,100-500,1.0,No,No,No,I don't know,I don't know,Difficult,Physical health,2022
34,50,F,United States of America,Washington,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2022
35,22,female,Russia,NaN,0,No,0,Maybe,100-500,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2022
36,30,non-binary,United States of America,California,0,Yes,1,No,More than 1000,0.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2022
37,30,female,United States of America,New York,0,I don't know,1,No,26-100,1.0,Yes,No,No,No,I don't know,I don't know,Physical health,2022
38,34,Male,United States of America,New York,0,I don't know,1,Maybe,More than 1000,1.0,Yes,Yes,Yes,I don't know,I don't know,Very easy,Physical health,2022
39,2,f,United States of America,California,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
40,48,Male,United States of America,Minnesota,0,No,0,Maybe,26-100,1.0,Yes,No,No,No,Yes,Somewhat easy,Physical health,2022
41,22,female,India,NaN,0,No,0,No,1-5,1.0,Not eligible for coverage / NA,No,No,No,No,Somewhat difficult,Same level of comfort for each,2022
42,38,man,Ukraine,NaN,0,No,0,No,6-25,1.0,No,No,No,No,Yes,Very easy,Same level of comfort for each,2022
43,45,male,Germany,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
44,36,Male,United States of America,California,0,Yes,1,Yes,26-100,0.0,No,No,No,No,I don't know,Very easy,Same level of comfort for each,2022
45,65,M,Belgium,NaN,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
46,35,m,Germany,NaN,0,No,0,Yes,100-500,0.0,No,No,No,No,I don't know,Somewhat difficult,Physical health,2022
47,41,male,Germany,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
48,46,Male,United States of America,Wisconsin,0,Yes,1,Yes,More than 1000,0.0,Yes,Yes,No,Yes,I don't know,Somewhat easy,Same level of comfort for each,2022
49,45,f,Lithuania,NaN,0,No,0,Maybe,26-100,1.0,No,No,I don't know,I don't know,No,Difficult,Same level of comfort for each,2022
50,36,Male,United Kingdom,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
51,29,Male,India,NaN,0,I don't know,0,No,6-25,0.0,No,Yes,No,No,No,Difficult,Mental health,2022
52,30,Male,India,NaN,0,No,0,Maybe,26-100,1.0,Yes,Yes,No,No,Yes,Very easy,Same level of comfort for each,2022
53,29,Male,Bangladesh,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
54,39,male,Slovenia,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
55,22,female,India,NaN,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
56,47,Female,United States of America,Minnesota,0,Yes,1,Maybe,More than 1000,0.0,Yes,Yes,No,Yes,I don't know,I don't know,Physical health,2022
57,26,Female,South Africa,NaN,0,No,1,No,100-500,1.0,Yes,No,Yes,No,I don't know,Difficult,Physical health,2022
58,38,Male,Somalia,NaN,0,No,0,Yes,26-100,0.0,No,No,No,No,I don't know,I don't know,Same level of comfort for each,2022
59,49,Queer,United States of America,Illinois,0,Yes,1,Yes,More than 1000,0.0,Yes,Yes,I don't know,Yes,I don't know,Neither easy nor difficult,Physical health,2022
60,37,Male,Romania,NaN,0,No,0,Yes,More than 1000,0.0,No,No,No,No,I don't know,Very easy,Physical health,2022
61,34,Male,Netherlands,NaN,0,No,0,Yes,6-25,0.0,I don't know,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2022
62,43,Male,United States of America,Arizona,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
63,47,Male,France,NaN,0,I don't know,0,Maybe,100-500,1.0,Yes,Yes,Yes,No,I don't know,Very easy,Physical health,2022
64,33,varón,Peru,NaN,0,No,0,Yes,500-1000,0.0,No,No,No,No,I don't know,Somewhat difficult,Physical health,2022
65,21,female,Germany,NaN,0,No,0,Yes,More than 1000,1.0,Not eligible for coverage / NA,NaN,Yes,Yes,Yes,Somewhat easy,Physical health,2022
66,59,female,United States of America,Indiana,0,Yes,1,Maybe,500-1000,1.0,Yes,No,Yes,I don't know,I don't know,I don't know,Physical health,2022
67,51,Male,United States of America,Wisconsin,0,No,0,Yes,6-25,0.0,Yes,No,No,No,Yes,Somewhat easy,Physical health,2022
68,60,Male,United States of America,Georgia,0,Yes,0,Maybe,More than 1000,1.0,Yes,No,No,Yes,I don't know,I don't know,Physical health,2022
69,47,male,Australia,NaN,0,I don't know,0,Yes,1-5,1.0,Not eligible for coverage / NA,NaN,No,No,No,Neither easy nor difficult,Same level of comfort for each,2022
70,56,Male,Canada,NaN,0,No,1,No,More than 1000,1.0,Yes,Yes,I don't know,Yes,I don't know,Somewhat difficult,Physical health,2022
71,40,m,United States of America,Arizona,0,No,0,Maybe,500-1000,0.0,I don't know,No,I don't know,Yes,I don't know,Somewhat easy,Physical health,2022
72,38,Male,Spain,NaN,0,Yes,0,Maybe,6-25,1.0,I don't know,No,No,No,Yes,Somewhat easy,Physical health,2022
73,50,Male,United States of America,Florida,0,Yes,0,Maybe,More than 1000,0.0,Yes,No,Yes,I don't know,Yes,Very easy,Physical health,2022
74,20,female,United Kingdom,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
75,35,M,France,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
76,29,Male,Taiwan,NaN,0,I don't know,0,Yes,More than 1000,1.0,Yes,Yes,No,No,Yes,Neither easy nor difficult,Physical health,2022
77,39,man,Canada,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
78,49,male,New Zealand,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
79,45,M,United States of America,Virginia,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
80,50,male,Serbia,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
81,44,NaN,Canada,NaN,0,I don't know,0,Yes,100-500,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Same level of comfort for each,2022
82,59,Male,Panama,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
83,43,male,United Kingdom,NaN,0,No,0,Maybe,26-100,1.0,No,NaN,Yes,Yes,I don't know,Neither easy nor difficult,Physical health,2022
84,42,Male,United States of America,Pennsylvania,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
85,41,male,United States of America,Massachusetts,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
86,38,Male,United States of America,Connecticut,0,Yes,1,Yes,100-500,0.0,Yes,Yes,No,No,I don't know,Somewhat difficult,Physical health,2022
87,33,Male,United States of America,California,0,No,0,Maybe,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2022
88,50,M,United States of America,Illinois,0,Yes,1,Maybe,More than 1000,0.0,Yes,No,Yes,I don't know,Yes,Somewhat easy,Physical health,2022
89,28,Female,United States of America,California,0,Yes,1,No,26-100,0.0,Yes,Yes,Yes,Yes,Yes,I don't know,Physical health,2022
90,40,Male,United States of America,Maryland,0,No,0,No,6-25,1.0,No,No,No,No,I don't know,Difficult,Physical health,2022
91,58,Male,United Kingdom,NaN,0,No,0,Yes,500-1000,1.0,Yes,No,Yes,Yes,Yes,Very easy,Same level of comfort for each,2022
92,65,M,United States of America,Wisconsin,0,No,0,Maybe,26-100,1.0,No,Yes,No,Yes,I don't know,Neither easy nor difficult,Physical health,2022
93,36,Male,Indonesia,NaN,0,No,0,Maybe,6-25,0.0,I don't know,NaN,I don't know,I don't know,I don't know,I don't know,Physical health,2022
94,35,Male,Poland,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
95,61,Male,United States of America,Ohio,1,I don't know,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
96,50,Male,United States of America,Texas,0,No,0,Maybe,26-100,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2022
97,40,Male,Uruguay,NaN,0,I don't know,1,Yes,500-1000,0.0,I don't know,No,Yes,No,I don't know,Somewhat easy,Physical health,2022
98,37,male,Italy,NaN,0,No,0,Yes,26-100,0.0,No,No,No,No,I don't know,Very easy,Physical health,2022
99,32,male,Colombia,NaN,0,No,0,Yes,100-500,1.0,No,No,No,No,No,Neither easy nor difficult,Same level of comfort for each,2022
100,46,female,Italy,NaN,0,I don't know,1,Yes,500-1000,1.0,No,NaN,No,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2022
101,36,Male,Italy,NaN,0,No,0,Yes,More than 1000,1.0,No,No,No,No,Yes,Neither easy nor difficult,Physical health,2022
102,23,Male,United States of America,Virginia,0,No,0,No,26-100,1.0,Yes,NaN,No,Yes,Yes,Somewhat difficult,Physical health,2022
103,39,male,United States of America,Michigan,0,Yes,0,Yes,6-25,1.0,Yes,Yes,No,No,Yes,Very easy,Same level of comfort for each,2022
104,28,female,United States of America,New York,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2022
105,44,male,United States of America,Colorado,0,No,1,No,100-500,0.0,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,2022
106,36,Male,Canada,NaN,0,No,0,Yes,100-500,1.0,I don't know,Yes,Yes,Yes,Yes,Very easy,Physical health,2022
107,32,Male,Netherlands,NaN,0,No,1,Yes,26-100,1.0,I don't know,Yes,No,No,I don't know,Very easy,Physical health,2022
108,55,Male,United States of America,Oregon,0,I don't know,1,Yes,100-500,1.0,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,Physical health,2022
109,42,Male,Canada,NaN,0,No,1,Yes,6-25,1.0,Yes,Yes,No,No,Yes,Very easy,Same level of comfort for each,2022
110,26,Male,United States of America,Tennessee,0,No,0,Maybe,100-500,0.0,Yes,No,Yes,Yes,I don't know,Somewhat easy,Physical health,2022
111,61,Male,United States of America,Utah,0,I don't know,0,Yes,26-100,0.0,Yes,No,No,No,Yes,Somewhat easy,Same level of comfort for each,2022
112,56,male,Canada,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
113,63,Male,United States of America,New Mexico,0,No,0,Yes,100-500,0.0,Yes,No,Yes,Yes,I don't know,Somewhat easy,Physical health,2022
114,60,male,United States of America,Florida,0,No,0,Yes,1-5,1.0,No,No,No,No,I don't know,Neither easy nor difficult,Physical health,2022
115,46,Male,Germany,NaN,0,No,0,No,100-500,1.0,No,No,No,No,I don't know,Somewhat easy,Same level of comfort for each,2022
116,43,Male,Netherlands,NaN,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
117,39,Male,Belgium,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
118,44,female,United States of America,North Carolina,0,Yes,1,Yes,26-100,1.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2022
119,32,Male,United Kingdom,NaN,0,I don't know,1,Yes,100-500,0.0,Yes,NaN,No,I don't know,Yes,Somewhat easy,Same level of comfort for each,2022
120,35,Male,Indonesia,NaN,0,No,0,Maybe,More than 1000,0.0,No,No,I don't know,I don't know,I don't know,I don't know,Same level of comfort for each,2022
121,48,Male,Spain,NaN,0,Yes,1,Yes,More than 1000,0.0,No,No,No,No,Yes,Neither easy nor difficult,Same level of comfort for each,2022
122,45,Male,Canada,NaN,0,No,1,Yes,6-25,1.0,Not eligible for coverage / NA,No,No,No,No,Somewhat easy,Physical health,2022
123,46,Male,Mexico,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
124,31,Female,United States of America,Virginia,0,Yes,1,Maybe,100-500,1.0,Yes,Yes,Yes,Yes,I don't know,Somewhat difficult,Physical health,2022
125,41,Male,United States of America,Illinois,0,No,1,Maybe,6-25,1.0,Yes,Yes,No,I don't know,Yes,Very easy,Physical health,2022
126,38,Male,South Africa,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
127,39,Male,Aruba,NaN,1,I don't know,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
128,51,Male,United States of America,Oklahoma,0,Yes,0,Maybe,100-500,0.0,I don't know,No,No,No,I don't know,Somewhat difficult,Physical health,2022
129,43,Male,United Kingdom,NaN,0,No,1,Yes,6-25,1.0,No,NaN,No,No,I don't know,Very easy,Physical health,2022
130,35,male,Netherlands,NaN,0,No,0,Yes,More than 1000,0.0,I don't know,No,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2022
131,37,male,Serbia,NaN,0,No,0,Maybe,26-100,1.0,No,No,No,No,I don't know,Very easy,Physical health,2022
132,31,Female,United States of America,Wisconsin,0,No,1,No,6-25,1.0,Yes,Yes,No,No,Yes,Somewhat easy,Physical health,2022
133,39,Male,Canada,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
134,37,Male,Indonesia,NaN,0,No,0,Maybe,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2022
135,37,Male,United States of America,Idaho,0,Yes,1,Yes,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2022
136,76,M,United States of America,Florida,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
137,47,Male,Israel,NaN,0,I don't know,1,Maybe,500-1000,1.0,I don't know,No,Yes,Yes,I don't know,Somewhat easy,Same level of comfort for each,2022
138,41,Male,Canada,NaN,0,Yes,1,No,100-500,0.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2022
139,58,Male,United Kingdom,NaN,0,No,0,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2022
140,46,Male,United States of America,Illinois,0,No,1,Yes,6-25,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2022
141,53,Male,United States of America,New Jersey,0,No,0,Maybe,26-100,0.0,I don't know,No,I don't know,I don't know,I don't know,Somewhat easy,Physical health,2022
142,30,Female,United States of America,Maryland,0,Yes,1,No,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Same level of comfort for each,2022
143,55,male,United Kingdom,NaN,0,No,0,No,100-500,0.0,I don't know,Yes,I don't know,No,I don't know,Neither easy nor difficult,Physical health,2022
144,36,Male,United States of America,Pennsylvania,0,No,1,Maybe,More than 1000,0.0,Yes,No,I don't know,I don't know,I don't know,Somewhat difficult,Physical health,2022
145,44,Male,United Kingdom,NaN,0,No,0,Maybe,500-1000,1.0,I don't know,No,Yes,No,I don't know,Difficult,Physical health,2022
146,58,Male,United Kingdom,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
147,45,m,United Kingdom,NaN,0,No,0,Maybe,26-100,1.0,Yes,Yes,Yes,I don't know,Yes,Neither easy nor difficult,Physical health,2022
148,46,male,Argentina,NaN,0,No,0,Maybe,6-25,0.0,I don't know,Yes,No,No,Yes,I don't know,Same level of comfort for each,2022
149,33,male,Austria,NaN,0,I don't know,0,Maybe,26-100,1.0,No,Yes,No,No,Yes,Very easy,Physical health,2022
150,61,F,United States of America,California,0,No,0,Maybe,6-25,1.0,Yes,Yes,No,I don't know,I don't know,Somewhat easy,Same level of comfort for each,2022
151,24,male,Poland,NaN,0,No,0,Maybe,26-100,1.0,Yes,Yes,No,No,Yes,Somewhat easy,Same level of comfort for each,2022
152,46,male,Denmark,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
153,33,Male,United Kingdom,NaN,0,No,1,Yes,26-100,1.0,Yes,Yes,Yes,Yes,I don't know,Very easy,Same level of comfort for each,2022
154,57,Male,United States of America,California,0,No,1,Yes,6-25,1.0,Yes,Yes,Yes,No,I don't know,Somewhat easy,Mental health,2022
155,31,male,United States of America,Georgia,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
156,40,Female,Canada,NaN,1,No,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
157,38,Male,United States of America,North Carolina,0,No,0,Yes,100-500,1.0,Yes,Yes,Yes,Yes,Yes,Somewhat easy,Physical health,2022
158,38,Male,United States of America,California,0,Yes,1,Yes,More than 1000,1.0,Yes,Yes,Yes,Yes,Yes,Neither easy nor difficult,Same level of comfort for each,2022
159,31,female,Poland,NaN,0,No,1,Maybe,More than 1000,1.0,I don't know,Yes,Yes,Yes,I don't know,Somewhat difficult,Physical health,2022
160,40,M,Australia,NaN,0,No,0,No,26-100,1.0,Yes,Yes,Yes,Yes,Yes,Very easy,Physical health,2022
161,23,NaN,United States of America,Alabama,0,Yes,1,Yes,26-100,1.0,I don't know,Yes,Yes,Yes,Yes,Very easy,Physical health,2022
162,21,Female,Kazakhstan,NaN,1,Yes,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022
163,32,female,Russia,NaN,0,No,1,No,6-25,1.0,No,NaN,No,No,No,Difficult,Physical health,2022

In [27]:
df_2023_cleaned

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_vs_physical,survey_year
0,40,Female,United States of America,Colorado,0,I don't know,1,Maybe,26-100,1.0,No,No,No,No,Yes,Somewhat easy,Mental health,2023
1,36,Male,United States of America,Indiana,0,No,1,No,6-25,1.0,I don't know,No,No,I don't know,I don't know,I don't know,Physical health,2023
2,44,male,United States of America,Maryland,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
3,53,Female,United States of America,Indiana,0,Yes,1,Maybe,500-1000,0.0,Yes,Yes,Yes,No,I don't know,Neither easy nor difficult,Same level of comfort for each,2023
4,62,male,United States of America,Ohio,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
5,39,Male,Canada,NaN,0,Yes,1,No,More than 1000,1.0,I don't know,No,Yes,I don't know,Yes,Somewhat easy,Mental health,2023

In [28]:
print(df_2014_cleaned.shape)
print(df_2016_cleaned.shape)
print(df_2017_cleaned.shape)
print(df_2018_cleaned.shape)
print(df_2019_cleaned.shape)
print(df_2020_cleaned.shape)
print(df_2021_cleaned.shape)
print(df_2022_cleaned.shape)
print(df_2023_cleaned.shape)

(1259, 25)
(1433, 18)
(756, 17)
(417, 18)
(352, 18)
(180, 18)
(131, 18)
(164, 18)
(6, 18)

In [29]:
for i, df in zip([2014, 2016, 2017, 2018, 2019,2020, 2021, 2022, 2023],
                 [df_2014_cleaned, df_2016_cleaned, df_2017_cleaned, df_2018_cleaned, df_2019_cleaned, df_2020_cleaned, df_2021_cleaned, df_2022_cleaned, df_2023_cleaned]):
    missing = set(target_columns) - set(df.columns)
    print(f"Year {i} missing columns: {missing}")

Year 2014 missing columns: set()
Year 2016 missing columns: {'supervisor', 'mental_vs_physical', 'obs_consequence', 'coworkers', 'comments', 'mental_health_consequence', 'phys_health_consequence'}
Year 2017 missing columns: {'supervisor', 'benefits', 'obs_consequence', 'remote_work', 'coworkers', 'comments', 'mental_health_consequence', 'phys_health_consequence'}
Year 2018 missing columns: {'supervisor', 'obs_consequence', 'remote_work', 'coworkers', 'comments', 'mental_health_consequence', 'phys_health_consequence'}
Year 2019 missing columns: {'supervisor', 'obs_consequence', 'remote_work', 'coworkers', 'comments', 'mental_health_consequence', 'phys_health_consequence'}
Year 2020 missing columns: {'supervisor', 'obs_consequence', 'remote_work', 'coworkers', 'comments', 'mental_health_consequence', 'phys_health_consequence'}
Year 2021 missing columns: {'supervisor', 'obs_consequence', 'remote_work', 'coworkers', 'comments', 'mental_health_consequence', 'phys_health_consequence'}
Year 2022 missing columns: {'supervisor', 'obs_consequence', 'remote_work', 'coworkers', 'comments', 'mental_health_consequence', 'phys_health_consequence'}
Year 2023 missing columns: {'supervisor', 'obs_consequence', 'remote_work', 'coworkers', 'comments', 'mental_health_consequence', 'phys_health_consequence'}

In [30]:
merged_df_all_years = pd.concat([
    df_2014_cleaned,
    df_2016_cleaned,
    df_2017_cleaned,
    df_2018_cleaned,
    df_2019_cleaned,
    df_2020_cleaned,
    df_2021_cleaned,
    df_2022_cleaned,
    df_2023_cleaned
    ], ignore_index=True)


print("Final merged shape:", merged_df_all_years.shape)
merged_df_all_years.tail()

Final merged shape: (4698, 25)

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_vs_physical,obs_consequence,comments,survey_year
4693,36.0,Male,United States of America,Indiana,0,No,1,No,6-25,NaN,1.0,I don't know,No,No,I don't know,I don't know,I don't know,NaN,NaN,NaN,NaN,Physical health,NaN,NaN,2023
4694,44.0,male,United States of America,Maryland,1,Yes,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
4695,53.0,Female,United States of America,Indiana,0,Yes,1,Maybe,500-1000,NaN,0.0,Yes,Yes,Yes,No,I don't know,Neither easy nor difficult,NaN,NaN,NaN,NaN,Same level of comfort for each,NaN,NaN,2023
4696,62.0,male,United States of America,Ohio,1,No,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023
4697,39.0,Male,Canada,NaN,0,Yes,1,No,More than 1000,NaN,1.0,I don't know,No,Yes,I don't know,Yes,Somewhat easy,NaN,NaN,NaN,NaN,Mental health,NaN,NaN,2023

In [31]:
round(merged_df_all_years.describe(include='all'),2)

,age,gender,country,state,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_vs_physical,obs_consequence,comments,survey_year
count,4.696000e+03,4664,4696,2779,4680.0,4698,4698.0,4133,4110,2692,4110.0,3467,3803,4110,4110,4110,4110,1259,1259,1259,1259,2964,1259,164,4698.00
unique,NaN,187,95,93,4.0,3,4.0,8,6,5,4.0,6,4,4,4,4,8,3,3,3,3,6,2,160,NaN
top,NaN,Male,United States of America,California,0.0,Yes,1.0,Sometimes,More than 1000,No,1.0,Yes,No,No,No,I don't know,Somewhat easy,No,No,Some of them,Yes,Physical health,No,* Small family business - YMMV.,NaN
freq,NaN,2052,2044,267,2851.0,2026,2004.0,828,1064,883,2115.0,1571,1671,2663,1905,1756,1004,490,925,774,516,1148,1075,5,NaN
mean,2.129475e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.54
std,1.459271e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.15
min,-1.726000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.00
25%,2.800000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.00
50%,3.300000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.00
75%,3.900000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018.00
max,1.000000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.00

##### Age has negative values, values over 1000
##### Gender has too many categories (187 unique)

In [32]:
merged_df_all_years.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4698 entries, 0 to 4697
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   age                        4696 non-null   float64
 1   gender                     4664 non-null   object
 2   country                    4696 non-null   object
 3   state                      2779 non-null   object
 4   self_employed              4680 non-null   object
 5   family_history             4698 non-null   object
 6   treatment                  4698 non-null   object
 7   work_interfere             4133 non-null   object
 8   no_employees               4110 non-null   object
 9   remote_work                2692 non-null   object
 10  tech_company               4110 non-null   object
 11  benefits                   3467 non-null   object
 12  care_options               3803 non-null   object
 13  wellness_program           4110 non-null   object
 14  seek_help                  4110 non-null   object
 15  anonymity                  4110 non-null   object
 16  leave                      4110 non-null   object
 17  mental_health_consequence  1259 non-null   object
 18  phys_health_consequence    1259 non-null   object
 19  coworkers                  1259 non-null   object
 20  supervisor                 1259 non-null   object
 21  mental_vs_physical         2964 non-null   object
 22  obs_consequence            1259 non-null   object
 23  comments                   164 non-null    object
 24  survey_year                4698 non-null   int64
dtypes: float64(1), int64(1), object(23)
memory usage: 917.7+ KB

In [33]:
merged_df_all_years.dtypes

age                          float64
gender                        object
country                       object
state                         object
self_employed                 object
family_history                object
treatment                     object
work_interfere                object
no_employees                  object
remote_work                   object
tech_company                  object
benefits                      object
care_options                  object
wellness_program              object
seek_help                     object
anonymity                     object
leave                         object
mental_health_consequence     object
phys_health_consequence       object
coworkers                     object
supervisor                    object
mental_vs_physical            object
obs_consequence               object
comments                      object
survey_year                    int64
dtype: object

In [34]:
merged_df_all_years.isna().sum().sort_values(ascending=False).reset_index()

                        index     0
0                    comments  4534
1                   coworkers  3439
2                  supervisor  3439
3     phys_health_consequence  3439
4             obs_consequence  3439
5   mental_health_consequence  3439
6                 remote_work  2006
7                       state  1919
8          mental_vs_physical  1734
9                    benefits  1231
10               care_options   895
11               no_employees   588
12           wellness_program   588
13                  seek_help   588
14                  anonymity   588
15                      leave   588
16               tech_company   588
17             work_interfere   565
18                     gender    34
19              self_employed    18
20                        age     2
21                    country     2
22                  treatment     0
23             family_history     0
24                survey_year     0

In [35]:
x=round((merged_df_all_years.isna().sum()/merged_df_all_years.shape[0])*100,2)
x = pd.DataFrame(x)
x = x.sort_values(by=x.columns[0], ascending=False).reset_index()
x

                        index      0
0                    comments  96.51
1                   coworkers  73.20
2                  supervisor  73.20
3     phys_health_consequence  73.20
4             obs_consequence  73.20
5   mental_health_consequence  73.20
6                 remote_work  42.70
7                       state  40.85
8          mental_vs_physical  36.91
9                    benefits  26.20
10               care_options  19.05
11               no_employees  12.52
12           wellness_program  12.52
13                  seek_help  12.52
14                  anonymity  12.52
15                      leave  12.52
16               tech_company  12.52
17             work_interfere  12.03
18                     gender   0.72
19              self_employed   0.38
20                        age   0.04
21                    country   0.04
22                  treatment   0.00
23             family_history   0.00
24                survey_year   0.00

##### Comments column has almost 96% null values; it is not a mandatory question in the survey. Can be dropped.
> ##### May keep for sentiment analysis later. TBD, but holding in for now
##### Work_interfere and self_employed will need to be treated
##### Null values are observed. Most come from the State column which does not contribute to the research and can be dropped.

In [36]:
merged_df_all_years['state'].unique()

array(['IL', 'IN', nan, 'TX', 'TN', 'MI', 'OH', 'CA', 'CT', 'MD', 'NY',
       'NC', 'MA', 'IA', 'PA', 'WA', 'WI', 'UT', 'NM', 'OR', 'FL', 'MN',
       'MO', 'AZ', 'CO', 'GA', 'DC', 'NE', 'WV', 'OK', 'KS', 'VA', 'NH',
       'KY', 'AL', 'NV', 'NJ', 'SC', 'VT', 'SD', 'ID', 'MS', 'RI', 'WY',
       'LA', 'ME', 'Illinois', 'Tennessee', 'Virginia', 'California',
       'Kentucky', 'Oregon', 'Pennsylvania', 'New Jersey', 'Georgia',
       'Washington', 'New York', 'Indiana', 'Minnesota', 'West Virginia',
       'Florida', 'Massachusetts', 'North Dakota', 'Texas', 'Maryland',
       'Wisconsin', 'Michigan', 'Vermont', 'North Carolina', 'Kansas',
       'District of Columbia', 'Nevada', 'Utah', 'Connecticut',
       'Colorado', 'Ohio', 'Iowa', 'South Dakota', 'Nebraska', 'Maine',
       'Missouri', 'Arizona', 'Oklahoma', 'Idaho', 'Rhode Island',
       'Alabama', 'Louisiana', 'South Carolina', 'New Hampshire',
       'New Mexico', 'Montana', 'Alaska', 'Delaware', 'Wyoming'],
      dtype=object)

In [37]:
merged_df_all_years['country'].value_counts()

country
United States of America    2044
United States                751
United Kingdom               507
Canada                       225
Germany                      154
Netherlands                  110
India                        110
Australia                     83
France                        54
Brazil                        52
Ireland                       52
Spain                         35
Sweden                        32
Switzerland                   29
Portugal                      26
Poland                        26
Italy                         25
New Zealand                   25
South Africa                  21
Russia                        21
Belgium                       17
Mexico                        14
Finland                       14
Bulgaria                      14
Austria                       14
Norway                        12
Israel                        12
Denmark                       10
Indonesia                     10
Romania                       10
Japan                          9
Pakistan                       9
Colombia                       9
Turkey                         8
Slovenia                       8
Serbia                         7
Greece                         7
Estonia                        6
Bangladesh                     6
Macedonia                      6
Ukraine                        5
Singapore                      5
Czech Republic                 5
Argentina                      5
Chile                          4
Philippines                    4
Croatia                        4
Bosnia and Herzegovina         4
China                          3
Uruguay                        3
Iceland                        3
Hungary                        3
Taiwan                         3
Afghanistan                    3
Nigeria                        3
Lithuania                      3
Vietnam                        3
Kenya                          2
Mongolia                       2
Latvia                         2
Sri Lanka                      2
Georgia                        2
Jordan                         2
Algeria                        2
Costa Rica                     2
Other                          2
Slovakia                       2
Hong Kong                      2
Malaysia                       1
Peru                           1
Panama                         1
Somalia                        1
Aruba                          1
Belarus                        1
Egypt                          1
Albania                        1
Cameroon                       1
Sao Tome and Principe          1
Ghana                          1
Eritrea                        1
Ethiopia                       1
Saudi Arabia                   1
Mauritius                      1
Luxembourg                     1
Zimbabwe                       1
Swaziland                      1
Guatemala                      1
Ecuador                        1
Iran                           1
Brunei                         1
Thailand                       1
Bahamas, The                   1
Venezuela                      1
Moldova                        1
Kazakhstan                     1
Name: count, dtype: int64

##### Nearly 60% of responses are from the US
##### The other 40% is spread out across several countries

In [38]:
merged_df_all_years = merged_df_all_years.drop(['state'], axis=1)

In [39]:
# Function to observe unique categorical values for each variable.
def see_unique_categories(df):
    """
    Prints the unique categories of each categorical variable in the DataFrame.
    """
    for col in merged_df_all_years.select_dtypes(include=['object', 'category']).columns:
        print(f"--- {col} ---")
        print(merged_df_all_years[col].unique())
        print()
        print("------------------------------------------------------------------------------")

In [40]:
see_unique_categories(merged_df_all_years)

--- gender ---
['Female' 'M' 'Male' 'male' 'female' 'm' 'Male-ish' 'maile' 'Trans-female'
 'Cis Female' 'F' 'something kinda male?' 'Cis Male' 'Woman' 'f' 'Mal'
 'Male (CIS)' 'queer/she/they' 'non-binary' 'Femake' 'woman' 'Make' 'Nah'
 'All' 'Enby' 'fluid' 'Genderqueer' 'Female ' 'Androgyne' 'Agender'
 'cis-female/femme' 'Guy (-ish) ^_^' 'male leaning androgynous' 'Male '
 'Man' 'Trans woman' 'msle' 'Neuter' 'Female (trans)' 'queer'
 'Female (cis)' 'Mail' 'cis male' 'A little about you' 'Malr' 'p' 'femail'
 'Cis Man' 'ostensibly male, unsure what that really means'
 'I identify as female.' 'female ' 'Bigender' 'Female assigned at birth '
 'man' 'fm' 'Cis female ' 'Transitioned, M2F' 'Genderfluid (born female)'
 'Other/Transfeminine' 'Female or Multi-Gender Femme' 'female/woman'
 'Cis male' 'Male.' 'Androgynous' 'male 9:1 female, roughly' nan
 'Male (cis)' 'Other' 'nb masculine' 'Cisgender Female' 'Sex is male'
 'none of your business' 'genderqueer' 'Human' 'Genderfluid'
 'genderqueer woman' 'mtf' 'Queer' 'Dude' 'Fluid'
 "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? "
 'mail' 'M|' 'Male/genderqueer' 'fem' 'Nonbinary' 'male ' 'human'
 'Female (props for making this a freeform field, though)' ' Female'
 'Unicorn' 'Male (trans, FtM)' 'Cis-woman' 'cisdude'
 'Genderflux demi-girl' 'female-bodied; no feelings about gender'
 'cis man' 'AFAB' 'Transgender woman' 'MALE' 'cis-male'
 'male/androgynous ' 'cis hetero male' 'femalw'
 'uhhhhhhhhh fem genderqueer?'
 "male (hey this is the tech industry you're talking about)"
 'female (cis)' 'God King of the Valajar' 'My sex is female.' 'Cis-male'
 'Non-binary' 'Male, cis' 'cis male ' 'Agender/genderfluid' 'sometimes'
 'female (cisgender)' 'Female (cis) ' 'Woman-identified' 'Contextual'
 'Non binary' 'Genderqueer demigirl' 'Genderqueer/non-binary' 'cis-Female'
 'cis female' 'nonbinary' 'F, cisgender' 'Female-ish' '\\-' 'trans woman'
 'Transfeminine' 'dude' 'Ostensibly Male' 'male, born with xy chromosoms'
 'Malel' 'I identify as female' '*shrug emoji* (F)'
 'Male (or female, or both)' 'Trans man' 'transgender' 'non binary'
 'Female/gender non-binary.' 'Cis woman' 'Female (cisgender)' 'Cis-Female'
 'Cisgendered woman' 'genderfluid' 'Demiguy' 'none' 'Trans female'
 'Cisgender male' 'She/her/they/them' 'SWM' 'cisgender female' 'NB'
 'Nonbinary/femme' 'gender non-conforming woman'
 'Let\'s keep it simple and say "male"' 'Identify as male' 'Masculine'
 'Cishet male' 'Female-identified' 'agender' 'Questioning'
 'I have a penis' 'rr' 'cis woman' 'Agender trans woman' 'femmina' '43'
 'masculino' 'I am a Wookie' 'Trans non-binary/genderfluid' 'CIS Male'
 'Non-binary and gender fluid' 'Femile' 'FEMALE' 'female, she/her'
 'mostly male' 'cisgender male' 'MAle' 'afab non-binary' 'b' 'male/he/him'
 'homem cis' 'cis-het male' 'Non-binary/Agender' 'Female, cis-gendered'
 'varón']

------------------------------------------------------------------------------
--- country ---
['United States' 'Canada' 'United Kingdom' 'Bulgaria' 'France' 'Portugal'
 'Netherlands' 'Switzerland' 'Poland' 'Australia' 'Germany' 'Russia'
 'Mexico' 'Brazil' 'Slovenia' 'Costa Rica' 'Austria' 'Ireland' 'India'
 'South Africa' 'Italy' 'Sweden' 'Colombia' 'Latvia' 'Romania' 'Belgium'
 'New Zealand' 'Zimbabwe' 'Spain' 'Finland' 'Uruguay' 'Israel'
 'Bosnia and Herzegovina' 'Hungary' 'Singapore' 'Japan' 'Nigeria'
 'Croatia' 'Norway' 'Thailand' 'Denmark' 'Bahamas, The' 'Greece' 'Moldova'
 'Georgia' 'China' 'Czech Republic' 'Philippines'
 'United States of America' 'Lithuania' 'Venezuela' 'Argentina' 'Vietnam'
 'Slovakia' 'Bangladesh' 'Algeria' 'Pakistan' 'Afghanistan' 'Other'
 'Brunei' 'Iran' 'Ecuador' 'Chile' 'Guatemala' 'Taiwan' 'Serbia' 'Estonia'
 'Iceland' 'Indonesia' 'Jordan' 'Eritrea' 'Swaziland' 'Ukraine'
 'Luxembourg' 'Turkey' nan 'Mauritius' 'Saudi Arabia' 'Kenya' 'Ethiopia'
 'Macedonia' 'Hong Kong' 'Ghana' 'Mongolia' 'Cameroon' 'Sri Lanka' 'Egypt'
 'Malaysia' 'Belarus' 'Albania' 'Sao Tome and Principe' 'Somalia' 'Peru'
 'Panama' 'Aruba' 'Kazakhstan']

------------------------------------------------------------------------------
--- self_employed ---
[nan 'Yes' 'No' 0 1]

------------------------------------------------------------------------------
--- family_history ---
['No' 'Yes' "I don't know"]

------------------------------------------------------------------------------
--- treatment ---
['Yes' 'No' 0 1]

------------------------------------------------------------------------------
--- work_interfere ---
['Often' 'Rarely' 'Never' 'Sometimes' nan 'Not applicable to me' 'Yes'
 'Maybe' 'No']

------------------------------------------------------------------------------
--- no_employees ---
['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000' nan]

------------------------------------------------------------------------------
--- remote_work ---
['No' 'Yes' 'Sometimes' 'Never' 'Always' nan]

------------------------------------------------------------------------------
--- tech_company ---
['Yes' 'No' 1.0 nan 0.0]

------------------------------------------------------------------------------
--- benefits ---
['Yes' "Don't know" 'No' 'Not eligible for coverage / N/A' nan
 "I don't know" 'Not eligible for coverage / NA']

------------------------------------------------------------------------------
--- care_options ---
['Not sure' 'No' 'Yes' nan 'I am not sure']

------------------------------------------------------------------------------
--- wellness_program ---
['No' "Don't know" 'Yes' nan "I don't know"]

------------------------------------------------------------------------------
--- seek_help ---
['Yes' "Don't know" 'No' nan "I don't know"]

------------------------------------------------------------------------------
--- anonymity ---
['Yes' "Don't know" 'No' "I don't know" nan]

------------------------------------------------------------------------------
--- leave ---
['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy' 'Neither easy nor difficult' nan "I don't know" 'Difficult']

------------------------------------------------------------------------------
--- mental_health_consequence ---
['No' 'Maybe' 'Yes' nan]

------------------------------------------------------------------------------
--- phys_health_consequence ---
['No' 'Yes' 'Maybe' nan]

------------------------------------------------------------------------------
--- coworkers ---
['Some of them' 'No' 'Yes' nan]

------------------------------------------------------------------------------
--- supervisor ---
['Yes' 'No' 'Some of them' nan]

------------------------------------------------------------------------------
--- mental_vs_physical ---
['Yes' "Don't know" 'No' nan 'Same level of comfort for each'
 'Physical health' 'Mental health']

------------------------------------------------------------------------------
--- obs_consequence ---
['No' 'Yes' nan]

------------------------------------------------------------------------------
--- comments ---
[nan
 "I'm not on my company's health insurance which could be part of the reason I answered Don't know to so many questions."
 'I have chronic low-level neurological issues that have mental health side effects. One of my supervisors has also experienced similar neurological problems so I feel more comfortable being open about my issues than I would with someone without that experience. '
 "My company does provide healthcare but not to me as I'm on a fixed-term contract. The mental healthcare I use is provided entirely outside of my work."
 'Relatively new job. Ask again later'
 'Sometimes I think  about using drugs for my mental health issues. If i use drugs I feel better'
 'I selected my current employer based on its policies about self care and the quality of their overall health and wellness benefits. I still have residual caution from previous employers who ranged from ambivalent to indifferent to actively hostile regarding mental health concerns.'
 "Our health plan has covered my psychotherapy and my antidepressant medication. My manager has been aware but discreet throughout. I did get negative reviews when my depression was trashing my delivery but y'know I wasn't delivering."
 "I just started a new job last week hence a lot of don't know's"
 "In addition to my own mental health issues I've known several coworkers that may be suffering and I don't know how to tell them I empathize and that I want to help."
 'Thanks for doing this research.'
 "In Russia we have mandatory medical insurance. Every employer must pay 3.6% of every employee's salary to the insurance fund like a tax. Everyone gets free healthcare at public clinics and hospitals. Some types of healthcare including mental health are still funded from the government budget but that doesn't matter it's still FREE!However this is Russia :D I don't know much about what actually happens in mental hospitals here except that a lot of young people with male in their passports use these to avoid military draft and doctors seem to help them."
 "In my previous workplace which had mental health protections policies and access to counsellors my Director went so far as to say to me in somewhat casual conversation A woman was murdered across the street. At best though she was bipolar and at worst - who knowsI have bipolar disorder. I have zero faith that an organization with policies in place could appropriately handle mental health. I have even less faith that a workplace without the policies in place could appropriately handle mental health. I can only imagine it's worse in full tech environments."
 "I've seen negative consequences towards mental health conditions in previous workplaces.Working remote is empowering in this way."
 "I'm not a permanent employee so do not get they benefits they get.My client is extremely supportive of permanent staff with mental health issues."
 "I'd be more worried about coworkers and workplace culture than the employer--they're probably legally obligated to do some things but reputation among people I work with is something else. For instance I've heard people make snide remarks about men taking paternity leave I don't want to know what they'd say about mental health leave."
 "Had a co-worker disappear from work for a few weeks and then come back to let everyone know he was bipolar. His responsibilities and schedule were adjusted to accommodate but he got worse didn't show up didn't work etc and was eventually let go.It was tough because on the one hand he was struggling with some mental health issues but on the other hand he went through a period of months where he wasn't performing."
 "Family history of depression.  Currently dealing with depression and anxiety as well as drug addition.Employer provides & pays premiums on insurance which covers therapy and prescriptions.  Employer allows work-from-home and unlimited PTO which makes episodes easier to control.I don't speak of my problems to anyone at work except for the people that I consider friends and even then I don't go into great detail.I would never bring up a mental health issue during an interview for fear of discrimination and rejection (and therefore greater depression).  One co-worker had serious anxiety problems and would not inform his team of episodes and was eventually let go for being unresponsive."
 'I feel that my employer and colleagues have created my mental health issue. Additionally I have contributed to this by staying in the same job with the same employer for 10+ years.'
 "Many of these questions become irrelevant once 'Yes' is selected for 'Are you self-employed'.  It would be preferable for there to be a 'Not Relevant' option on these."
 "as a UK-based company we don't have any medical provisions as it's all provided on the National Health Service (for now!) However if we do need to take days off for any kind of health problems everyone is understanding :)"
 'My employer employs 17k people worldwide and my previous employer only 140 globally both have been very supportive and accommodating with my moderate depression and intense anxiety.'
 "I am not sure about my company's healthcare because I've opted out of it and I'm covered under another policy.I currently work at a great company though in past jobs I don't think I would have felt comfortable talking about mental health at all."
 'In small startups it is very hard to keep mental health issues truly private no matter what management does.'
 'A close family member of mine struggles with mental health so I try not to stigmatize it. My employers/coworkers also seem compassionate toward any kind of health or family needs.'
 "Too many people even especially IT considered mental health issues as a choice or something people can freely act about. You are depressed: take vacation. You feel weird: admit it is physical (otherwise it is not serious) go and see a doctor (and if you are on sick leave too many days you will get fired). You don't feel good today: take a holiday but don't work from home. In startup there is what I call the tyranny of happiness: you have to look happy to be accepted and to be worked with. At some point playing a role can definitely make the mental health issue worse and it is also a threat to diversity :(I don't like to call mental health issues an issue but actually when it comes to company field it too often becomes an issue and this is sad because working is sometimes better than medication. It is a vicious circle: people are scared of speaking about it so they don't inform their coworkers about what mental health is for real and so coworkers are so scared on a regular basis that the people with mental health issues keep it for themselves. "
 "My seniority at the company and rapport with the owners has helped me gain support for seeking help regarding my mental health as well as being able to take time off or work from home when an episode starts.However I don't feel that the company's stance on mental health is as clear as say something like vision or dental.  There's very much a stigma."
 "When you are an introvert people don't notice if you are depressed. Its a vicious cycle of sorts."
 "I've answered 'Yes' on remote working but 50% is the maximum time we're allowed.The branch of the company I work for doesn't offer any medical benefits. It's not as common in the UK as we have the NHS for the moment. There are international branches that may so I've answered 'Don't know'."
 'Many of these questions were difficult to answer as a self-employed person; I did my best with the available options.'
 "I tried to answer as good as possible but I am CEO of a company so many questions don't fit very well.Also many of the questions are very US-centric in most systems healthcare is not your employers business."
 "One of my coworkers has mental health issues and she's open about them (eg: my enjoyment of this project may be due to my recent change in meds). I believe the response has been generally supportive. We're a very small tight-knit company."
 'A strong mind goes a long way. Stay strong. Take some time off to help. Its all in your head. '
 'Would you bring up a mental health issue with a potential employer in an interview?Poignant.'
 'I found it difficult to answer all of the questions effectively as many of them would depend on the nature of the mental health issues as some seem more socially accepted than others. For some people telling your current supervisor that you have a history of bi-polar disorder might be easier than telling a potential employer that you have a history of compulsive gambling. They might both be bits of irrelevant information (past behavior and not indicators of future behavior). However western culture pushes us to appear as capable as possible to our supervisors in pursuit of excellence in our work. Providing information that could create a negative bias seems like a more genuine and yet more risky approach to the discussion.'
 'I have only discussed my mental illness with close family members. I feel completely uncomfortable discussing with anyone at my place of employment as I am concerned it would have negative consequences.'
 'No benefits at this organization but my employer/direct supervisor has had positive and constructive conversations with me about physical and mental health. Supervisor offered solutions advice time/energy to get help if I ever felt that needed it. (though it would have to be at my own expense). I feel safe sharing personal info with this particular person/company but this environment is the exception rather than the norm in my 15+ years as a tech worker. I would never feel safe enough to reveal info about any mental health concerns with any previous employers in the tech industry for fear of  negative perceptions job loss performance dings etc. '
 'I think I am very lucky in my workplace. Our CEO has a degree in psychology.'
 "Some of these questions were difficult to answer as being self-employed they didn't all apply to me."
 "It's a small startup in a small city in a small country."
 "Hi Ed it's Paul Dragoonis. I have Aspergers/High Functioning Autism :-)"
 'The form of mental health problem that I suffer is anxiety.'
 'The thought of going through my employer directly to get help is fucking scary.Getting help is the hardest part of getting help.'
 "Don't know because I haven't checked not because it's difficult to find out. If you didn't have the don't know option I would've looked up the answer."
 "I think there might be some bugs in my thought but I haven't sought treatment because they're not worse than annoying and I worry about having the label."
 "I think a lot of our policy is based on a situation that occurred in the past 5 years. A very public mental illness happened with a coworker that unfortunately ended negatively. It was definitely a catalyst to talking about our options but the overall sentiment of it being OK to take time off talk with your supervisors etc. has always been there. It's a great company."
 "Regardless of a stated lack of negative consequences for discussing mental health issues with coworkers/superiors unconscious bias is a very real thing - as long as I don't *need* to inform my co-workers my mental health issues do not need to be public knowledge."
 'YOU MAY WANT TO THROW OUT MY ENTRY.I answered all of these questions with the assumption that Attention Deficit Disorder is considered a mental illness and with ADD in mind.'
 'In Belgium we have all medical care so perhaps some question are not relevant'
 "A co-worker recently had mental health issues and my employer was very reasonable with them I don't know the full story but I do know that he was given ample time off and eased back in to the work place."
 'My refer to the mental health issue of depression.  I might answer differently if I was talking about a more serious issue like schizophrenia'
 'My employer does what they can providing a wellness program and pointing it out after particularly stressful times. But the interaction between the wellness program and the medical insurance is unpleasant and finding a long-term therapist / psychiatrist covered by insurance is amazingly difficult. My current lack of active treatment is due to insurance friction more than workplace friction.'
 'I work for a university.'
 "Being in Canada there are several health options that are available to Canadian citizens/perm residents for free so employers may not provide resources because they are available elsewhere. Otherwise good quiz. I hope this benefits everyone who's dealt with mental health issues in the past!"
 "I'm troubled by the way that our hiring process tends to filter out non-neurotypicals of all stripes. Competent people who act a little funny can be hard to hire."

In [41]:
merged_df_all_years['gender'].value_counts().reset_index()

                                                gender  count
0                                                 Male   2052
1                                                 male    747
2                                               Female    572
3                                               female    319
4                                                    M    276
5                                                    m    166
6                                                    F    124
7                                                    f     69
8                                                Male      25
9                                              Female      21
10                                               Woman     19
11                                               woman     14
12                                                 Man     10
13                                           Nonbinary      8
14                                                 man      7
15                                            Cis Male      7
16                                            cis male      7
17                                          non-binary      7
18                                                Make      5
19                                          Non-binary      4
20                                             Agender      4
21                                         Genderqueer      4
22                                             female       3
23                                            Cis male      3
24                                        Female (cis)      3
25                                          Male (cis)      3
26                                                MALE      3
27                                         Genderfluid      3
28                                            Cis-male      3
29                                              FEMALE      2
30                                               Other      2
31                                         Cis female       2
32                                             agender      2
33                                           Masculine      2
34                                               male       2
35                                          Non binary      2
36                                              femail      2
37                                                Malr      2
38                                                Mail      2
39                                            Male-ish      2
40                                                dude      2
41                                      Female (trans)      2
42                                               Queer      2
43                                                Enby      2
44                                         Trans woman      2
45                                           Trans man      2
46                                                mail      2
47                                  Female (cisgender)      1
48                                          non binary      1
49                           Female/gender non-binary.      1
50                                          Contextual      1
51                                          Cis-Female      1
52                                   Cisgendered woman      1
53                                           Cis woman      1
54                                         transgender      1
55                                         genderfluid      1
56                                    Woman-identified      1
57                                   *shrug emoji* (F)      1
58                           Male (or female, or both)      1
59                                        F, cisgender      1
60                                I identify as female      1
61                                               Malel      1
62                       male, born with xy chromosoms      1
63                                Genderqueer demigirl      1
64                                     Ostensibly Male      1
65                              Genderqueer/non-binary      1
66                                          cis-Female      1
67                                             Demiguy      1
68                                         trans woman      1
69                                          cis female      1
70                                           nonbinary      1
71                                                  \-      1
72                                          Female-ish      1
73                                       Transfeminine      1
74                                   Female-identified      1
75                                                none      1
76                                      cisgender male      1
77                                       I am a Wookie      1
78                        Trans non-binary/genderfluid      1
79                                            CIS Male      1
80                         Non-binary and gender fluid      1
81                                              Femile      1
82                                     female, she/her      1
83                                         mostly male      1
84                                                MAle      1
85                                        Trans female      1
86                                     afab non-binary      1
87                                                   b      1
88                                         male/he/him      1
89                                           homem cis      1
90                                        cis-het male      1
91                                  Non-binary/Agender      1
92                                Female, cis-gendered      1
93                                           masculino      1
94                                                  43      1
95                                             femmina      1
96                                 Agender trans woman      1
97                                      Cisgender male      1
98                                   She/her/they/them      1
99                                                 SWM      1
100                                   cisgender female      1
101                                                 NB      1
102                                    Nonbinary/femme      1
103                        gender non-conforming woman      1
104                Let's keep it simple and say "male"      1
105                                   Identify as male      1
106                                        Cishet male      1
107                                 female (cisgender)      1
108                                        Questioning      1
109                                     I have a penis      1
110                                                 rr      1
111                                          cis woman      1
112                                      Female (cis)       1
113                               Genderflux demi-girl      1
114                                          sometimes      1
115                                       nb masculine      1
116                                 A little about you      1
117                                                  p      1
118                                            Cis Man      1
119     ostensibly male, unsure what that really means      1
120                              I identify as female.      1
121                                           Bigender      1
122                          Female assigned at birth       1
123                                                 fm      1
124                                  Transitioned, M2F      1
125                          Genderfluid (born female)      1
126                                Other/Transfeminine      1
127                       Female or Multi-Gender Femme      1
128                                       female/woman      1
129                                              Male.      1
130                                        Androgynous      1
131                                              queer      1
132                                             Neuter      1
133                                               msle      1
134                                     queer/she/they      1
135                                              maile      1
136                                       Trans-female      1
137                                         Cis Female      1
138                              something kinda male?      1
139                                                Mal      1
140                                         Male (CIS)      1
141                                             Femake      1
142                           male leaning androgynous      1
143                                                Nah      1
144                                                All      1
145                                              fluid      1
146                                          Androgyne      1
147                                   cis-female/femme      1
148                                     Guy (-ish) ^_^      1
149                           male 9:1 female, roughly      1
150                                   Cisgender Female      1
151                                Agender/genderfluid      1
152                                        Sex is male      1
153            female-bodied; no feelings about gender      1
154                                            cis man      1
155                                               AFAB      1
156                                  Transgender woman      1
157                                           cis-male      1
158                                  male/androgynous       1
159                                    cis hetero male      1
160                                             femalw      1
161                        uhhhhhhhhh fem genderqueer?      1
162  male (hey this is the tech industry you're tal...      1
163                                       female (cis)      1
164                            God King of the Valajar      1
165                                  My sex is female.      1
166                                          Male, cis      1
167                                          cis male       1
168                                            cisdude      1
169                                          Cis-woman      1
170                                  Male (trans, FtM)      1
171                                              Fluid      1
172                              none of your business      1
173                                        genderqueer      1
174                                              Human      1
175                                  genderqueer woman      1
176                                                mtf      1
177                                               Dude      1
178  I'm a man why didn't you make this a drop down...      1
179                                            Unicorn      1
180                                                 M|      1
181                                   Male/genderqueer      1
182                                                fem      1
183                                              human      1
184  Female (props for making this a freeform field...      1
185                                             Female      1
186                                              varón      1

In [42]:
male_keywords = ['mostly male', 'cisgender male','MAle', 'male/he/him','CIS Male','Cisgender male','Let\'s keep it simple and say "male"',
                 'Identify as male', 'Malel', 'dude', 'Ostensibly Male', 'male, born with xy chromosoms','Male, cis' ,'cis male ','Cis-male',
                 "male (hey this is the tech industry you're talking about)",'cis hetero male' ,'cis man' ,'MALE' ,'cis-male','mail', 'M|','male ' ,
                 "I'm a man why didn't you make this a drop down question. You should of asked sex? And I would of answered yes please. Seriously how much text can this take? ",
                 'Dude' ,'Male (cis)', 'Sex is male', 'Cis male', 'Male.', 'man', 'ostensibly male','Cis Man' ,'Malr', 'cis male', 'Mail', 
                 'Man','Make','Male (CIS)','Mal','Cis Male','Male','male', 'Male-ish', 'maile', 'm','M', 'man', 'cis male', 'cis man', 'male ',
                 'msle', 'malr', 'mal','maile', 'mail', 'make', 'guy', 'male leaning androgynous']

female_keywords = ['Femile' ,'FEMALE' ,'female, she/her','Female-identified' ,'cis woman','femmina','cisgender female' ,'Cisgendered woman',
                   'Female,cis-gendered','Female/gender non-binary.' ,'Cis woman', 'Female (cisgender)', 'Cis-Female','I identify as female' ,
                   '*shrug emoji* (F)', 'cis female' , 'F, cisgender' ,'Female-ish' ,'female (cisgender)' ,'Female (cis) ', 'Woman-identified',
                   'cis-Female','female (cis)','My sex is female.','femalw','Cis-woman' ,'Female (props for making this a freeform field, though)' ,
                   ' Female','fem','Cisgender Female','female/woman', 'fm' ,'Cis female ','I identify as female.','female ','Female assigned at birth ',
                   'femail', 'Female (cis)','Femake','Woman','Cis Female' ,'F','Female','female', 'f', 'woman', 'femake', 'femail', 'cis female',
                   'cis-female', 'female ', 'cis female/femme', 'female (cis)']

In [43]:
def general_classifier(value):
   
    val_norm = str(value).strip().lower()
    
    if any(kw in val_norm for kw in female_keywords):
        return 'Female'
    elif any(kw in val_norm for kw in male_keywords):
        return 'Male'
    else:
        return 'Other'

In [44]:
merged_df_all_years['gender'] = merged_df_all_years['gender'].apply(general_classifier)

In [45]:
merged_df_all_years['gender'].value_counts().reset_index()

   gender  count
0    Male   3375
1  Female   1225
2   Other     98

##### Gender consolidated to 2 values for simplicity
##### A dropdown in further surveys would make this cleaner and allow for broader inclusivity

In [46]:
see_unique_categories(merged_df_all_years)

--- gender ---
['Female' 'Male' 'Other']

------------------------------------------------------------------------------
--- country ---
['United States' 'Canada' 'United Kingdom' 'Bulgaria' 'France' 'Portugal'
 'Netherlands' 'Switzerland' 'Poland' 'Australia' 'Germany' 'Russia'
 'Mexico' 'Brazil' 'Slovenia' 'Costa Rica' 'Austria' 'Ireland' 'India'
 'South Africa' 'Italy' 'Sweden' 'Colombia' 'Latvia' 'Romania' 'Belgium'
 'New Zealand' 'Zimbabwe' 'Spain' 'Finland' 'Uruguay' 'Israel'
 'Bosnia and Herzegovina' 'Hungary' 'Singapore' 'Japan' 'Nigeria'
 'Croatia' 'Norway' 'Thailand' 'Denmark' 'Bahamas, The' 'Greece' 'Moldova'
 'Georgia' 'China' 'Czech Republic' 'Philippines'
 'United States of America' 'Lithuania' 'Venezuela' 'Argentina' 'Vietnam'
 'Slovakia' 'Bangladesh' 'Algeria' 'Pakistan' 'Afghanistan' 'Other'
 'Brunei' 'Iran' 'Ecuador' 'Chile' 'Guatemala' 'Taiwan' 'Serbia' 'Estonia'
 'Iceland' 'Indonesia' 'Jordan' 'Eritrea' 'Swaziland' 'Ukraine'
 'Luxembourg' 'Turkey' nan 'Mauritius' 'Saudi Arabia' 'Kenya' 'Ethiopia'
 'Macedonia' 'Hong Kong' 'Ghana' 'Mongolia' 'Cameroon' 'Sri Lanka' 'Egypt'
 'Malaysia' 'Belarus' 'Albania' 'Sao Tome and Principe' 'Somalia' 'Peru'
 'Panama' 'Aruba' 'Kazakhstan']

------------------------------------------------------------------------------
--- self_employed ---
[nan 'Yes' 'No' 0 1]

------------------------------------------------------------------------------
--- family_history ---
['No' 'Yes' "I don't know"]

------------------------------------------------------------------------------
--- treatment ---
['Yes' 'No' 0 1]

------------------------------------------------------------------------------
--- work_interfere ---
['Often' 'Rarely' 'Never' 'Sometimes' nan 'Not applicable to me' 'Yes'
 'Maybe' 'No']

------------------------------------------------------------------------------
--- no_employees ---
['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000' nan]

------------------------------------------------------------------------------
--- remote_work ---
['No' 'Yes' 'Sometimes' 'Never' 'Always' nan]

------------------------------------------------------------------------------
--- tech_company ---
['Yes' 'No' 1.0 nan 0.0]

------------------------------------------------------------------------------
--- benefits ---
['Yes' "Don't know" 'No' 'Not eligible for coverage / N/A' nan
 "I don't know" 'Not eligible for coverage / NA']

------------------------------------------------------------------------------
--- care_options ---
['Not sure' 'No' 'Yes' nan 'I am not sure']

------------------------------------------------------------------------------
--- wellness_program ---
['No' "Don't know" 'Yes' nan "I don't know"]

------------------------------------------------------------------------------
--- seek_help ---
['Yes' "Don't know" 'No' nan "I don't know"]

------------------------------------------------------------------------------
--- anonymity ---
['Yes' "Don't know" 'No' "I don't know" nan]

------------------------------------------------------------------------------
--- leave ---
['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy' 'Neither easy nor difficult' nan "I don't know" 'Difficult']

------------------------------------------------------------------------------
--- mental_health_consequence ---
['No' 'Maybe' 'Yes' nan]

------------------------------------------------------------------------------
--- phys_health_consequence ---
['No' 'Yes' 'Maybe' nan]

------------------------------------------------------------------------------
--- coworkers ---
['Some of them' 'No' 'Yes' nan]

------------------------------------------------------------------------------
--- supervisor ---
['Yes' 'No' 'Some of them' nan]

------------------------------------------------------------------------------
--- mental_vs_physical ---
['Yes' "Don't know" 'No' nan 'Same level of comfort for each'
 'Physical health' 'Mental health']

------------------------------------------------------------------------------
--- obs_consequence ---
['No' 'Yes' nan]

------------------------------------------------------------------------------
--- comments ---
[nan
 "I'm not on my company's health insurance which could be part of the reason I answered Don't know to so many questions."
 'I have chronic low-level neurological issues that have mental health side effects. One of my supervisors has also experienced similar neurological problems so I feel more comfortable being open about my issues than I would with someone without that experience. '
 "My company does provide healthcare but not to me as I'm on a fixed-term contract. The mental healthcare I use is provided entirely outside of my work."
 'Relatively new job. Ask again later'
 'Sometimes I think  about using drugs for my mental health issues. If i use drugs I feel better'
 'I selected my current employer based on its policies about self care and the quality of their overall health and wellness benefits. I still have residual caution from previous employers who ranged from ambivalent to indifferent to actively hostile regarding mental health concerns.'
 "Our health plan has covered my psychotherapy and my antidepressant medication. My manager has been aware but discreet throughout. I did get negative reviews when my depression was trashing my delivery but y'know I wasn't delivering."
 "I just started a new job last week hence a lot of don't know's"
 "In addition to my own mental health issues I've known several coworkers that may be suffering and I don't know how to tell them I empathize and that I want to help."
 'Thanks for doing this research.'
 "In Russia we have mandatory medical insurance. Every employer must pay 3.6% of every employee's salary to the insurance fund like a tax. Everyone gets free healthcare at public clinics and hospitals. Some types of healthcare including mental health are still funded from the government budget but that doesn't matter it's still FREE!However this is Russia :D I don't know much about what actually happens in mental hospitals here except that a lot of young people with male in their passports use these to avoid military draft and doctors seem to help them."
 "In my previous workplace which had mental health protections policies and access to counsellors my Director went so far as to say to me in somewhat casual conversation A woman was murdered across the street. At best though she was bipolar and at worst - who knowsI have bipolar disorder. I have zero faith that an organization with policies in place could appropriately handle mental health. I have even less faith that a workplace without the policies in place could appropriately handle mental health. I can only imagine it's worse in full tech environments."
 "I've seen negative consequences towards mental health conditions in previous workplaces.Working remote is empowering in this way."
 "I'm not a permanent employee so do not get they benefits they get.My client is extremely supportive of permanent staff with mental health issues."
 "I'd be more worried about coworkers and workplace culture than the employer--they're probably legally obligated to do some things but reputation among people I work with is something else. For instance I've heard people make snide remarks about men taking paternity leave I don't want to know what they'd say about mental health leave."
 "Had a co-worker disappear from work for a few weeks and then come back to let everyone know he was bipolar. His responsibilities and schedule were adjusted to accommodate but he got worse didn't show up didn't work etc and was eventually let go.It was tough because on the one hand he was struggling with some mental health issues but on the other hand he went through a period of months where he wasn't performing."
 "Family history of depression.  Currently dealing with depression and anxiety as well as drug addition.Employer provides & pays premiums on insurance which covers therapy and prescriptions.  Employer allows work-from-home and unlimited PTO which makes episodes easier to control.I don't speak of my problems to anyone at work except for the people that I consider friends and even then I don't go into great detail.I would never bring up a mental health issue during an interview for fear of discrimination and rejection (and therefore greater depression).  One co-worker had serious anxiety problems and would not inform his team of episodes and was eventually let go for being unresponsive."
 'I feel that my employer and colleagues have created my mental health issue. Additionally I have contributed to this by staying in the same job with the same employer for 10+ years.'
 "Many of these questions become irrelevant once 'Yes' is selected for 'Are you self-employed'.  It would be preferable for there to be a 'Not Relevant' option on these."
 "as a UK-based company we don't have any medical provisions as it's all provided on the National Health Service (for now!) However if we do need to take days off for any kind of health problems everyone is understanding :)"
 'My employer employs 17k people worldwide and my previous employer only 140 globally both have been very supportive and accommodating with my moderate depression and intense anxiety.'
 "I am not sure about my company's healthcare because I've opted out of it and I'm covered under another policy.I currently work at a great company though in past jobs I don't think I would have felt comfortable talking about mental health at all."
 'In small startups it is very hard to keep mental health issues truly private no matter what management does.'
 'A close family member of mine struggles with mental health so I try not to stigmatize it. My employers/coworkers also seem compassionate toward any kind of health or family needs.'
 "Too many people even especially IT considered mental health issues as a choice or something people can freely act about. You are depressed: take vacation. You feel weird: admit it is physical (otherwise it is not serious) go and see a doctor (and if you are on sick leave too many days you will get fired). You don't feel good today: take a holiday but don't work from home. In startup there is what I call the tyranny of happiness: you have to look happy to be accepted and to be worked with. At some point playing a role can definitely make the mental health issue worse and it is also a threat to diversity :(I don't like to call mental health issues an issue but actually when it comes to company field it too often becomes an issue and this is sad because working is sometimes better than medication. It is a vicious circle: people are scared of speaking about it so they don't inform their coworkers about what mental health is for real and so coworkers are so scared on a regular basis that the people with mental health issues keep it for themselves. "
 "My seniority at the company and rapport with the owners has helped me gain support for seeking help regarding my mental health as well as being able to take time off or work from home when an episode starts.However I don't feel that the company's stance on mental health is as clear as say something like vision or dental.  There's very much a stigma."
 "When you are an introvert people don't notice if you are depressed. Its a vicious cycle of sorts."
 "I've answered 'Yes' on remote working but 50% is the maximum time we're allowed.The branch of the company I work for doesn't offer any medical benefits. It's not as common in the UK as we have the NHS for the moment. There are international branches that may so I've answered 'Don't know'."
 'Many of these questions were difficult to answer as a self-employed person; I did my best with the available options.'
 "I tried to answer as good as possible but I am CEO of a company so many questions don't fit very well.Also many of the questions are very US-centric in most systems healthcare is not your employers business."
 "One of my coworkers has mental health issues and she's open about them (eg: my enjoyment of this project may be due to my recent change in meds). I believe the response has been generally supportive. We're a very small tight-knit company."
 'A strong mind goes a long way. Stay strong. Take some time off to help. Its all in your head. '
 'Would you bring up a mental health issue with a potential employer in an interview?Poignant.'
 'I found it difficult to answer all of the questions effectively as many of them would depend on the nature of the mental health issues as some seem more socially accepted than others. For some people telling your current supervisor that you have a history of bi-polar disorder might be easier than telling a potential employer that you have a history of compulsive gambling. They might both be bits of irrelevant information (past behavior and not indicators of future behavior). However western culture pushes us to appear as capable as possible to our supervisors in pursuit of excellence in our work. Providing information that could create a negative bias seems like a more genuine and yet more risky approach to the discussion.'
 'I have only discussed my mental illness with close family members. I feel completely uncomfortable discussing with anyone at my place of employment as I am concerned it would have negative consequences.'
 'No benefits at this organization but my employer/direct supervisor has had positive and constructive conversations with me about physical and mental health. Supervisor offered solutions advice time/energy to get help if I ever felt that needed it. (though it would have to be at my own expense). I feel safe sharing personal info with this particular person/company but this environment is the exception rather than the norm in my 15+ years as a tech worker. I would never feel safe enough to reveal info about any mental health concerns with any previous employers in the tech industry for fear of  negative perceptions job loss performance dings etc. '
 'I think I am very lucky in my workplace. Our CEO has a degree in psychology.'
 "Some of these questions were difficult to answer as being self-employed they didn't all apply to me."
 "It's a small startup in a small city in a small country."
 "Hi Ed it's Paul Dragoonis. I have Aspergers/High Functioning Autism :-)"
 'The form of mental health problem that I suffer is anxiety.'
 'The thought of going through my employer directly to get help is fucking scary.Getting help is the hardest part of getting help.'
 "Don't know because I haven't checked not because it's difficult to find out. If you didn't have the don't know option I would've looked up the answer."
 "I think there might be some bugs in my thought but I haven't sought treatment because they're not worse than annoying and I worry about having the label."
 "I think a lot of our policy is based on a situation that occurred in the past 5 years. A very public mental illness happened with a coworker that unfortunately ended negatively. It was definitely a catalyst to talking about our options but the overall sentiment of it being OK to take time off talk with your supervisors etc. has always been there. It's a great company."
 "Regardless of a stated lack of negative consequences for discussing mental health issues with coworkers/superiors unconscious bias is a very real thing - as long as I don't *need* to inform my co-workers my mental health issues do not need to be public knowledge."
 'YOU MAY WANT TO THROW OUT MY ENTRY.I answered all of these questions with the assumption that Attention Deficit Disorder is considered a mental illness and with ADD in mind.'
 'In Belgium we have all medical care so perhaps some question are not relevant'
 "A co-worker recently had mental health issues and my employer was very reasonable with them I don't know the full story but I do know that he was given ample time off and eased back in to the work place."
 'My refer to the mental health issue of depression.  I might answer differently if I was talking about a more serious issue like schizophrenia'
 'My employer does what they can providing a wellness program and pointing it out after particularly stressful times. But the interaction between the wellness program and the medical insurance is unpleasant and finding a long-term therapist / psychiatrist covered by insurance is amazingly difficult. My current lack of active treatment is due to insurance friction more than workplace friction.'
 'I work for a university.'
 "Being in Canada there are several health options that are available to Canadian citizens/perm residents for free so employers may not provide resources because they are available elsewhere. Otherwise good quiz. I hope this benefits everyone who's dealt with mental health issues in the past!"
 "I'm troubled by the way that our hiring process tends to filter out non-neurotypicals of all stripes. Competent people who act a little funny can be hard to hire."
 "In Germany your employer doesn't really provide mental health benefits. There's a standard and I get that but I would get the same at any other company in Germany."
 "fwiw I am a co founder of this company and the would you X in an interview questions shouldn't reflect how I would treat anyone addressing their own phys/mental health issue to me in such a situation. "
 "I talked to a psychiatrist once about taking medical leave for mental health issues with his referral. He was willing to help but warned me that I may not want to as he's seen that sort of thing follow people throughout their tech careers (word gets out even if it's confidential at work). I've been terrified of bringing mental health up anywhere that coworkers or potential employers could see ever since."
 'So much depends upon the organization. '
 "Now at starutp.  Previously worked at big tech company which was actually quite good at supporting mental health issues.  Still wouldn't share with bosses/other employees though as there remains a strong negative stigma."
 'Nice job on the text field for gender :-)'
 "I currently have the best managers I've ever worked with. I don't have any issues but one of my coworkers recently did and it was handled extremely well. "
 'you rock for doing this!' "I don't have a job :D"
 "Israel has public health insurance for everyone. Everyone has free mental health coverage and it's quite good. So that explains some of my answers."
 "Stigma is the worst. People first language is a small step but we can't get that right."
 '-'
 'I work for an extremely supportive company and we are amazingly open about mental health issues. Employees often share their struggles with the whole team and receive a high level of support in return.'
 'I bring up my depression in interviews solely because I have a large gap on my CV due to mental health issues which could be mistaken for a gap taken to say have children which I feel would harm my chances much more. I have other MH issues I would never bring up with employers or peers.'
 "I'm not aware of anyone with mental health issues at work it's definitely not something that's discussed publicly. There's also a lot of other personal info I don't know about my coworkers so it may just be that we tend not to talk about personal issues."
 'I suffer from mild depression and anxiety.'
 "The family history question needs a don't know option."
 "I'm afraid I haven't seen mental health issues arise at work yet. They are very accommodating with maternity leave but I don't know how that translates to anything else."
 'Mental health issue I have dealt with: acute depression'
 'Thanks for doing this. It will help end the stigma!'
 'For clarity I work at a casino.'
 'Most employers / coworkers and even immediate family is not all the time supportive to discuss depression and other problems. ie. My wife thinks she should be able to make sure that I am not depressed  which is funny because sometimes depression state has nothing to do with her. '

In [47]:
merged_df_all_years['age'].value_counts().reset_index()

             age  count
0   3.000000e+01    275
1   3.200000e+01    247
2   2.900000e+01    243
3   3.100000e+01    237
4   2.800000e+01    232
5   3.400000e+01    224
6   3.300000e+01    218
7   3.500000e+01    217
8   2.700000e+01    213
9   2.600000e+01    207
10  3.700000e+01    195
11  3.800000e+01    176
12  2.500000e+01    167
13  3.600000e+01    164
14  3.900000e+01    152
15  2.400000e+01    141
16  4.000000e+01    139
17  2.300000e+01    129
18  4.200000e+01    113
19  4.100000e+01     95
20  4.500000e+01     90
21  2.200000e+01     90
22  4.300000e+01     90
23  4.400000e+01     83
24  4.600000e+01     71
25  2.100000e+01     52
26  4.700000e+01     46
27  4.900000e+01     40
28  5.000000e+01     38
29  4.800000e+01     35
30  5.100000e+01     26
31  2.000000e+01     24
32  5.500000e+01     24
33  1.900000e+01     22
34  5.300000e+01     20
35  5.400000e+01     19
36  5.200000e+01     18
37  5.700000e+01     16
38  5.600000e+01     15
39  6.100000e+01     10
40  1.800000e+01      9
41  5.900000e+01      9
42  5.800000e+01      9
43  6.300000e+01      8
44  6.000000e+01      7
45  6.200000e+01      6
46  6.500000e+01      5
47  6.400000e+01      3
48  5.000000e+00      2
49  6.600000e+01      2
50  6.700000e+01      2
51  1.100000e+01      2
52  1.000000e+00      1
53  0.000000e+00      1
54  2.000000e+00      1
55  7.000000e+01      1
56  2.230000e+02      1
57  7.400000e+01      1
58  1.500000e+01      1
59  1.000000e+11      1
60  3.000000e+00      1
61  3.230000e+02      1
62  9.900000e+01      1
63  1.700000e+01      1
64  7.200000e+01      1
65 -1.000000e+00      1
66  8.000000e+00      1
67 -1.726000e+03      1
68  3.290000e+02      1
69 -2.900000e+01      1
70  7.600000e+01      1

In [48]:
merged_df_all_years = merged_df_all_years[(merged_df_all_years['age'] >= 18) & (merged_df_all_years['age'] <= 80)]

In [49]:
merged_df_all_years['age'].value_counts().reset_index()

     age  count
0   30.0    275
1   32.0    247
2   29.0    243
3   31.0    237
4   28.0    232
5   34.0    224
6   33.0    218
7   35.0    217
8   27.0    213
9   26.0    207
10  37.0    195
11  38.0    176
12  25.0    167
13  36.0    164
14  39.0    152
15  24.0    141
16  40.0    139
17  23.0    129
18  42.0    113
19  41.0     95
20  22.0     90
21  45.0     90
22  43.0     90
23  44.0     83
24  46.0     71
25  21.0     52
26  47.0     46
27  49.0     40
28  50.0     38
29  48.0     35
30  51.0     26
31  55.0     24
32  20.0     24
33  19.0     22
34  53.0     20
35  54.0     19
36  52.0     18
37  57.0     16
38  56.0     15
39  61.0     10
40  18.0      9
41  59.0      9
42  58.0      9
43  63.0      8
44  60.0      7
45  62.0      6
46  65.0      5
47  64.0      3
48  66.0      2
49  67.0      2
50  72.0      1
51  74.0      1
52  70.0      1
53  76.0      1

##### Outliers for the age variable are removed (negative ages and exaggeratedly high values).
> ##### Outliers occur in only two observations and dropping will not greatly impact the data
> ##### Since the Age variable was improperly answered, its possible other fields are similarly unreliable. Dropping may increase robustness of the data

### Feature Engineering

##### Creating `support_score` based on support-related columns
##### Binning age into age groups

In [50]:
bins = [18, 25, 35, 45, 55, 65, 80]
labels = ['18-24', '25-34', '35-44', '45-54', '55-64', '65+']
merged_df_all_years['age_group'] = pd.cut(merged_df_all_years['age'], bins=bins, labels=labels, right=False)

In [51]:
merged_df_all_years['age_group'].value_counts().reset_index()

  age_group  count
0     25-34   2263
1     35-44   1424
2     18-24    467
3     45-54    403
4     55-64    107
5       65+     13

In [52]:
for col in merged_df_all_years.select_dtypes(include=['object', 'category','float64', 'int64']).columns:
    print(f"--- {col} ---")
    print(merged_df_all_years[col].unique())
    print()
    print("------------------------------------------------------------------------------")

--- age ---
[37. 44. 32. 31. 33. 35. 39. 42. 23. 29. 36. 27. 46. 41. 34. 30. 40. 38.
 50. 24. 18. 28. 26. 22. 19. 25. 45. 21. 43. 56. 60. 54. 55. 48. 20. 57.
 58. 47. 62. 51. 65. 49. 53. 61. 72. 52. 63. 66. 59. 74. 70. 64. 67. 76.]

------------------------------------------------------------------------------
--- gender ---
['Female' 'Male' 'Other']

------------------------------------------------------------------------------
--- country ---
['United States' 'Canada' 'United Kingdom' 'Bulgaria' 'France' 'Portugal'
 'Netherlands' 'Switzerland' 'Poland' 'Australia' 'Germany' 'Russia'
 'Mexico' 'Brazil' 'Slovenia' 'Costa Rica' 'Austria' 'Ireland' 'India'
 'South Africa' 'Italy' 'Sweden' 'Colombia' 'Latvia' 'Romania' 'Belgium'
 'New Zealand' 'Spain' 'Finland' 'Uruguay' 'Israel'
 'Bosnia and Herzegovina' 'Hungary' 'Singapore' 'Japan' 'Nigeria'
 'Croatia' 'Norway' 'Thailand' 'Denmark' 'Greece' 'Moldova' 'Georgia'
 'China' 'Czech Republic' 'Philippines' 'United States of America'
 'Lithuania' 'Venezuela' 'Argentina' 'Vietnam' 'Slovakia' 'Bangladesh'
 'Algeria' 'Pakistan' 'Afghanistan' 'Other' 'Brunei' 'Iran' 'Ecuador'
 'Chile' 'Guatemala' 'Taiwan' 'Serbia' 'Estonia' 'Iceland' 'Indonesia'
 'Jordan' 'Eritrea' 'Swaziland' 'Ukraine' 'Luxembourg' 'Turkey'
 'Mauritius' 'Saudi Arabia' 'Kenya' 'Ethiopia' 'Macedonia' 'Hong Kong'
 'Ghana' 'Mongolia' 'Cameroon' 'Sri Lanka' 'Egypt' 'Malaysia' 'Belarus'
 'Albania' 'Sao Tome and Principe' 'Somalia' 'Peru' 'Panama' 'Aruba'
 'Kazakhstan']

------------------------------------------------------------------------------
--- self_employed ---
[nan 'Yes' 'No' 0 1]

------------------------------------------------------------------------------
--- family_history ---
['No' 'Yes' "I don't know"]

------------------------------------------------------------------------------
--- treatment ---
['Yes' 'No' 0 1]

------------------------------------------------------------------------------
--- work_interfere ---
['Often' 'Rarely' 'Never' 'Sometimes' nan 'Not applicable to me' 'Yes'
 'Maybe' 'No']

------------------------------------------------------------------------------
--- no_employees ---
['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000' nan]

------------------------------------------------------------------------------
--- remote_work ---
['No' 'Yes' 'Sometimes' 'Never' 'Always' nan]

------------------------------------------------------------------------------
--- tech_company ---
['Yes' 'No' 1.0 nan 0.0]

------------------------------------------------------------------------------
--- benefits ---
['Yes' "Don't know" 'No' 'Not eligible for coverage / N/A' nan
 "I don't know" 'Not eligible for coverage / NA']

------------------------------------------------------------------------------
--- care_options ---
['Not sure' 'No' 'Yes' nan 'I am not sure']

------------------------------------------------------------------------------
--- wellness_program ---
['No' "Don't know" 'Yes' nan "I don't know"]

------------------------------------------------------------------------------
--- seek_help ---
['Yes' "Don't know" 'No' nan "I don't know"]

------------------------------------------------------------------------------
--- anonymity ---
['Yes' "Don't know" 'No' "I don't know" nan]

------------------------------------------------------------------------------
--- leave ---
['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy' 'Neither easy nor difficult' nan "I don't know" 'Difficult']

------------------------------------------------------------------------------
--- mental_health_consequence ---
['No' 'Maybe' 'Yes' nan]

------------------------------------------------------------------------------
--- phys_health_consequence ---
['No' 'Yes' 'Maybe' nan]

------------------------------------------------------------------------------
--- coworkers ---
['Some of them' 'No' 'Yes' nan]

------------------------------------------------------------------------------
--- supervisor ---
['Yes' 'No' 'Some of them' nan]

------------------------------------------------------------------------------
--- mental_vs_physical ---
['Yes' "Don't know" 'No' nan 'Same level of comfort for each'
 'Physical health' 'Mental health']

------------------------------------------------------------------------------
--- obs_consequence ---
['No' 'Yes' nan]

------------------------------------------------------------------------------
--- comments ---
[nan
 "I'm not on my company's health insurance which could be part of the reason I answered Don't know to so many questions."
 'I have chronic low-level neurological issues that have mental health side effects. One of my supervisors has also experienced similar neurological problems so I feel more comfortable being open about my issues than I would with someone without that experience. '
 "My company does provide healthcare but not to me as I'm on a fixed-term contract. The mental healthcare I use is provided entirely outside of my work."
 'Relatively new job. Ask again later'
 'Sometimes I think  about using drugs for my mental health issues. If i use drugs I feel better'
 'I selected my current employer based on its policies about self care and the quality of their overall health and wellness benefits. I still have residual caution from previous employers who ranged from ambivalent to indifferent to actively hostile regarding mental health concerns.'
 "Our health plan has covered my psychotherapy and my antidepressant medication. My manager has been aware but discreet throughout. I did get negative reviews when my depression was trashing my delivery but y'know I wasn't delivering."
 "I just started a new job last week hence a lot of don't know's"
 "In addition to my own mental health issues I've known several coworkers that may be suffering and I don't know how to tell them I empathize and that I want to help."
 'Thanks for doing this research.'
 "In Russia we have mandatory medical insurance. Every employer must pay 3.6% of every employee's salary to the insurance fund like a tax. Everyone gets free healthcare at public clinics and hospitals. Some types of healthcare including mental health are still funded from the government budget but that doesn't matter it's still FREE!However this is Russia :D I don't know much about what actually happens in mental hospitals here except that a lot of young people with male in their passports use these to avoid military draft and doctors seem to help them."
 "In my previous workplace which had mental health protections policies and access to counsellors my Director went so far as to say to me in somewhat casual conversation A woman was murdered across the street. At best though she was bipolar and at worst - who knowsI have bipolar disorder. I have zero faith that an organization with policies in place could appropriately handle mental health. I have even less faith that a workplace without the policies in place could appropriately handle mental health. I can only imagine it's worse in full tech environments."
 "I've seen negative consequences towards mental health conditions in previous workplaces.Working remote is empowering in this way."
 "I'm not a permanent employee so do not get they benefits they get.My client is extremely supportive of permanent staff with mental health issues."
 "I'd be more worried about coworkers and workplace culture than the employer--they're probably legally obligated to do some things but reputation among people I work with is something else. For instance I've heard people make snide remarks about men taking paternity leave I don't want to know what they'd say about mental health leave."
 "Had a co-worker disappear from work for a few weeks and then come back to let everyone know he was bipolar. His responsibilities and schedule were adjusted to accommodate but he got worse didn't show up didn't work etc and was eventually let go.It was tough because on the one hand he was struggling with some mental health issues but on the other hand he went through a period of months where he wasn't performing."
 "Family history of depression.  Currently dealing with depression and anxiety as well as drug addition.Employer provides & pays premiums on insurance which covers therapy and prescriptions.  Employer allows work-from-home and unlimited PTO which makes episodes easier to control.I don't speak of my problems to anyone at work except for the people that I consider friends and even then I don't go into great detail.I would never bring up a mental health issue during an interview for fear of discrimination and rejection (and therefore greater depression).  One co-worker had serious anxiety problems and would not inform his team of episodes and was eventually let go for being unresponsive."
 'I feel that my employer and colleagues have created my mental health issue. Additionally I have contributed to this by staying in the same job with the same employer for 10+ years.'
 "Many of these questions become irrelevant once 'Yes' is selected for 'Are you self-employed'.  It would be preferable for there to be a 'Not Relevant' option on these."
 "as a UK-based company we don't have any medical provisions as it's all provided on the National Health Service (for now!) However if we do need to take days off for any kind of health problems everyone is understanding :)"
 'My employer employs 17k people worldwide and my previous employer only 140 globally both have been very supportive and accommodating with my moderate depression and intense anxiety.'
 "I am not sure about my company's healthcare because I've opted out of it and I'm covered under another policy.I currently work at a great company though in past jobs I don't think I would have felt comfortable talking about mental health at all."
 'In small startups it is very hard to keep mental health issues truly private no matter what management does.'
 'A close family member of mine struggles with mental health so I try not to stigmatize it. My employers/coworkers also seem compassionate toward any kind of health or family needs.'
 "Too many people even especially IT considered mental health issues as a choice or something people can freely act about. You are depressed: take vacation. You feel weird: admit it is physical (otherwise it is not serious) go and see a doctor (and if you are on sick leave too many days you will get fired). You don't feel good today: take a holiday but don't work from home. In startup there is what I call the tyranny of happiness: you have to look happy to be accepted and to be worked with. At some point playing a role can definitely make the mental health issue worse and it is also a threat to diversity :(I don't like to call mental health issues an issue but actually when it comes to company field it too often becomes an issue and this is sad because working is sometimes better than medication. It is a vicious circle: people are scared of speaking about it so they don't inform their coworkers about what mental health is for real and so coworkers are so scared on a regular basis that the people with mental health issues keep it for themselves. "
 "My seniority at the company and rapport with the owners has helped me gain support for seeking help regarding my mental health as well as being able to take time off or work from home when an episode starts.However I don't feel that the company's stance on mental health is as clear as say something like vision or dental.  There's very much a stigma."
 "When you are an introvert people don't notice if you are depressed. Its a vicious cycle of sorts."
 "I've answered 'Yes' on remote working but 50% is the maximum time we're allowed.The branch of the company I work for doesn't offer any medical benefits. It's not as common in the UK as we have the NHS for the moment. There are international branches that may so I've answered 'Don't know'."
 'Many of these questions were difficult to answer as a self-employed person; I did my best with the available options.'
 "I tried to answer as good as possible but I am CEO of a company so many questions don't fit very well.Also many of the questions are very US-centric in most systems healthcare is not your employers business."
 "One of my coworkers has mental health issues and she's open about them (eg: my enjoyment of this project may be due to my recent change in meds). I believe the response has been generally supportive. We're a very small tight-knit company."
 'A strong mind goes a long way. Stay strong. Take some time off to help. Its all in your head. '
 'Would you bring up a mental health issue with a potential employer in an interview?Poignant.'
 'I found it difficult to answer all of the questions effectively as many of them would depend on the nature of the mental health issues as some seem more socially accepted than others. For some people telling your current supervisor that you have a history of bi-polar disorder might be easier than telling a potential employer that you have a history of compulsive gambling. They might both be bits of irrelevant information (past behavior and not indicators of future behavior). However western culture pushes us to appear as capable as possible to our supervisors in pursuit of excellence in our work. Providing information that could create a negative bias seems like a more genuine and yet more risky approach to the discussion.'
 'I have only discussed my mental illness with close family members. I feel completely uncomfortable discussing with anyone at my place of employment as I am concerned it would have negative consequences.'
 'No benefits at this organization but my employer/direct supervisor has had positive and constructive conversations with me about physical and mental health. Supervisor offered solutions advice time/energy to get help if I ever felt that needed it. (though it would have to be at my own expense). I feel safe sharing personal info with this particular person/company but this environment is the exception rather than the norm in my 15+ years as a tech worker. I would never feel safe enough to reveal info about any mental health concerns with any previous employers in the tech industry for fear of  negative perceptions job loss performance dings etc. '
 'I think I am very lucky in my workplace. Our CEO has a degree in psychology.'
 "Some of these questions were difficult to answer as being self-employed they didn't all apply to me."
 "It's a small startup in a small city in a small country."
 "Hi Ed it's Paul Dragoonis. I have Aspergers/High Functioning Autism :-)"
 'The form of mental health problem that I suffer is anxiety.'
 'The thought of going through my employer directly to get help is fucking scary.Getting help is the hardest part of getting help.'
 "Don't know because I haven't checked not because it's difficult to find out. If you didn't have the don't know option I would've looked up the answer."
 "I think there might be some bugs in my thought but I haven't sought treatment because they're not worse than annoying and I worry about having the label."
 "I think a lot of our policy is based on a situation that occurred in the past 5 years. A very public mental illness happened with a coworker that unfortunately ended negatively. It was definitely a catalyst to talking about our options but the overall sentiment of it being OK to take time off talk with your supervisors etc. has always been there. It's a great company."
 "Regardless of a stated lack of negative consequences for discussing mental health issues with coworkers/superiors unconscious bias is a very real thing - as long as I don't *need* to inform my co-workers my mental health issues do not need to be public knowledge."
 'YOU MAY WANT TO THROW OUT MY ENTRY.I answered all of these questions with the assumption that Attention Deficit Disorder is considered a mental illness and with ADD in mind.'
 'In Belgium we have all medical care so perhaps some question are not relevant'
 "A co-worker recently had mental health issues and my employer was very reasonable with them I don't know the full story but I do know that he was given ample time off and eased back in to the work place."
 'My refer to the mental health issue of depression.  I might answer differently if I was talking about a more serious issue like schizophrenia'
 'My employer does what they can providing a wellness program and pointing it out after particularly stressful times. But the interaction between the wellness program and the medical insurance is unpleasant and finding a long-term therapist / psychiatrist covered by insurance is amazingly difficult. My current lack of active treatment is due to insurance friction more than workplace friction.'
 'I work for a university.'
 "Being in Canada there are several health options that are available to Canadian citizens/perm residents for free so employers may not provide resources because they are available elsewhere. Otherwise good quiz. I hope this benefits everyone who's dealt with mental health issues in the past!"
 "I'm troubled by the way that our hiring process tends to filter out non-neurotypicals of all stripes. Competent people who act a little funny can be hard to hire."
 "In Germany your employer doesn't really provide mental health benefits. There's a standard and I get that but I would get the same at any other company in Germany."
 "fwiw I am a co founder of this company and the would you X in an interview questions shouldn't reflect how I would treat anyone addressing their own phys/mental health issue to me in such a situation. "
 "I talked to a psychiatrist once about taking medical leave for mental health issues with his referral. He was willing to help but warned me that I may not want to as he's seen that sort of thing follow people throughout their tech careers (word gets out even if it's confidential at work). I've been terrified of bringing mental health up anywhere that coworkers or potential employers could see ever since."
 'So much depends upon the organization. '
 "Now at starutp.  Previously worked at big tech company which was actually quite good at supporting mental health issues.  Still wouldn't share with bosses/other employees though as there remains a strong negative stigma."
 'Nice job on the text field for gender :-)'
 "I currently have the best managers I've ever worked with. I don't have any issues but one of my coworkers recently did and it was handled extremely well. "
 'you rock for doing this!' "I don't have a job :D"
 "Israel has public health insurance for everyone. Everyone has free mental health coverage and it's quite good. So that explains some of my answers."
 "Stigma is the worst. People first language is a small step but we can't get that right."
 '-'
 'I work for an extremely supportive company and we are amazingly open about mental health issues. Employees often share their struggles with the whole team and receive a high level of support in return.'
 'I bring up my depression in interviews solely because I have a large gap on my CV due to mental health issues which could be mistaken for a gap taken to say have children which I feel would harm my chances much more. I have other MH issues I would never bring up with employers or peers.'
 "I'm not aware of anyone with mental health issues at work it's definitely not something that's discussed publicly. There's also a lot of other personal info I don't know about my coworkers so it may just be that we tend not to talk about personal issues."
 'I suffer from mild depression and anxiety.'
 "The family history question needs a don't know option."
 "I'm afraid I haven't seen mental health issues arise at work yet. They are very accommodating with maternity leave but I don't know how that translates to anything else."
 'Mental health issue I have dealt with: acute depression'
 'Thanks for doing this. It will help end the stigma!'
 'For clarity I work at a casino.'

##### Encoding responses

In [53]:
merged_df_all_years.isna().sum().sort_values(ascending=False).reset_index()

                        index     0
0                    comments  4516
1                   coworkers  3426
2     phys_health_consequence  3426
3   mental_health_consequence  3426
4             obs_consequence  3426
5                  supervisor  3426
6                 remote_work  1998
7          mental_vs_physical  1723
8                    benefits  1224
9                care_options   887
10                  seek_help   581
11                      leave   581
12                  anonymity   581
13           wellness_program   581
14               no_employees   581
15               tech_company   581
16             work_interfere   557
17              self_employed    18
18                survey_year     0
19                        age     0
20                     gender     0
21                  treatment     0
22             family_history     0
23                    country     0
24                  age_group     0

In [54]:
# Helper functions

def map_binary(value):
    """Map binary-like values to 0/1. Handles Yes/No, True/False, 1/0."""
    if pd.isna(value):
        return np.nan
    val = str(value).strip().lower()
    if val in ['yes','y','1','1.0','true','t']:
        return 1
    elif val in ['no','n','0','0.0','false','f']:
        return 0
    else:
        return np.nan

def map_ternary(value):
    """Map ternary values: Yes=1, No=0, Don't know / Not sure / Not eligible = 2"""
    if pd.isna(value):
        return np.nan
    val = str(value).strip().lower()
    if val in ['yes','y','1','1.0','true','t']:
        return 1
    elif val in ['no','n','0','0.0','false','f']:
        return 0
    else:
        return 2

def normalize_binary_column(col):
    """Normalize a column to canonical 0/1/NaN"""
    return col.map(map_binary)

In [55]:
# Main Encoding Function

def encode_survey_clean_final(
    df,
    ordinal_mappings=None,
    binary_candidates=None,
    nominal_onehot=None,
    exclude_columns=None,
    verbose=True
):
    """
    Fully robust survey encoding:
    - Binary candidates normalized to 0/1 (_enc column added)
    - Ordinals mapped according to provided mapping
    - Ternary detected automatically (Yes/No/Don't know)
    - Nominal one-hot encoding for multi-category variables
    - Preserves original columns
    - Excludes free-text columns
    """

    df_encoded = df.copy()
    binary_candidates = binary_candidates or []
    nominal_onehot = nominal_onehot or []
    exclude_columns = exclude_columns or []

    # ---------------- Step 1: Normalize binary candidates ----------------
    for col in binary_candidates:
        if col in df_encoded.columns:
            df_encoded[col] = normalize_binary_column(df_encoded[col])
            df_encoded[f"{col}_enc"] = df_encoded[col]  # Add _enc column
            if verbose:
                print(f"Binary candidate normalized and encoded → {col} → {col}_enc")

    # ---------------- Step 2: Encode remaining columns ----------------
    for col in df_encoded.columns:
        if col in exclude_columns:
            if verbose:
                print(f"Excluded → {col}")
            continue

        # Skip numeric columns (binary candidates already handled)
        if pd.api.types.is_numeric_dtype(df_encoded[col]):
            continue

        new_col = f"{col}_enc"

        # Normalize strings for detection
        col_str = df_encoded[col].astype(str).str.strip().str.lower()
        unique_vals = col_str.replace('nan', np.nan).dropna().unique()
        sample_vals = [str(v) for v in unique_vals]

        # ----- Ordinal mapping -----
        if ordinal_mappings and col in ordinal_mappings:
            df_encoded[new_col] = df_encoded[col].map(ordinal_mappings[col])
            if verbose:
                print(f"Ordinal → {col} mapped to {new_col}")
            continue

        # ----- Nominal one-hot override -----
        if col in nominal_onehot:
            dummies = pd.get_dummies(df_encoded[col], prefix=new_col, dummy_na=False)
            df_encoded = pd.concat([df_encoded, dummies], axis=1)
            if verbose:
                print(f"Nominal one-hot → {col} expanded to {list(dummies.columns)}")
            continue

        # ----- Ternary detection (Yes/No/Don't know) -----
        # Only trigger if column is not already binary candidate
        if col not in binary_candidates:
            if any(['don' in v or 'not sure' in v or 'not eligible' in v for v in sample_vals]):
                df_encoded[new_col] = col_str.map(map_ternary)
                if verbose:
                    print(f"Ternary → {col} mapped to {new_col} (0/1/2)")
                continue

        # ----- Otherwise → one-hot multi-category -----
        dummies = pd.get_dummies(df_encoded[col], prefix=new_col, dummy_na=False)
        df_encoded = pd.concat([df_encoded, dummies], axis=1)
        if verbose:
            print(f"One-hot → {col} expanded to {list(dummies.columns)}")

    return df_encoded

In [56]:
# Binary columns
binary_candidates = ['self_employed','treatment','tech_company','obs_consequence']

# Ordinal mappings
ordinal_mappings = {
    'work_interfere': {'Never':0, 'Rarely':1, 'Sometimes':2, 'Often':3},
    'leave': {'Very easy':0, 'Somewhat easy':1, 'Neither easy nor difficult':2,
              'Somewhat difficult':3, 'Difficult':3, 'Very difficult':4}
}

# Nominal one-hot columns (multi-category)
nominal_onehot = ['no_employees','remote_work','age_group',
                  'mental_health_consequence','phys_health_consequence',
                  'coworkers','supervisor']

# Columns to exclude (free-text)
exclude_columns = ['comments','country']

# Country stays as a single column
# Optionally encode separately if needed:
# df['country_enc'] = df['country']

# Encode dataset
df_clean = encode_survey_clean_final(
    merged_df_all_years,
    ordinal_mappings=ordinal_mappings,
    binary_candidates=binary_candidates,
    nominal_onehot=nominal_onehot,
    exclude_columns=exclude_columns,
    verbose=True
)

Binary candidate normalized and encoded → self_employed → self_employed_enc
Binary candidate normalized and encoded → treatment → treatment_enc
Binary candidate normalized and encoded → tech_company → tech_company_enc
Binary candidate normalized and encoded → obs_consequence → obs_consequence_enc
One-hot → gender expanded to ['gender_enc_Female', 'gender_enc_Male', 'gender_enc_Other']
Excluded → country
Ternary → family_history mapped to family_history_enc (0/1/2)
Ordinal → work_interfere mapped to work_interfere_enc
Nominal one-hot → no_employees expanded to ['no_employees_enc_1-5', 'no_employees_enc_100-500', 'no_employees_enc_26-100', 'no_employees_enc_500-1000', 'no_employees_enc_6-25', 'no_employees_enc_More than 1000']
Nominal one-hot → remote_work expanded to ['remote_work_enc_Always', 'remote_work_enc_Never', 'remote_work_enc_No', 'remote_work_enc_Sometimes', 'remote_work_enc_Yes']
Ternary → benefits mapped to benefits_enc (0/1/2)
Ternary → care_options mapped to care_options_enc (0/1/2)
Ternary → wellness_program mapped to wellness_program_enc (0/1/2)
Ternary → seek_help mapped to seek_help_enc (0/1/2)
Ternary → anonymity mapped to anonymity_enc (0/1/2)
Ordinal → leave mapped to leave_enc
Nominal one-hot → mental_health_consequence expanded to ['mental_health_consequence_enc_Maybe', 'mental_health_consequence_enc_No', 'mental_health_consequence_enc_Yes']
Nominal one-hot → phys_health_consequence expanded to ['phys_health_consequence_enc_Maybe', 'phys_health_consequence_enc_No', 'phys_health_consequence_enc_Yes']
Nominal one-hot → coworkers expanded to ['coworkers_enc_No', 'coworkers_enc_Some of them', 'coworkers_enc_Yes']
Nominal one-hot → supervisor expanded to ['supervisor_enc_No', 'supervisor_enc_Some of them', 'supervisor_enc_Yes']
Ternary → mental_vs_physical mapped to mental_vs_physical_enc (0/1/2)
Excluded → comments
Nominal one-hot → age_group expanded to ['age_group_enc_18-24', 'age_group_enc_25-34', 'age_group_enc_35-44', 'age_group_enc_45-54', 'age_group_enc_55-64', 'age_group_enc_65+']

In [57]:
# Check problematic columns
df_clean.head()

,age,gender,country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,seek_help,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_vs_physical,obs_consequence,comments,survey_year,age_group,self_employed_enc,treatment_enc,tech_company_enc,obs_consequence_enc,gender_enc_Female,gender_enc_Male,gender_enc_Other,family_history_enc,work_interfere_enc,no_employees_enc_1-5,no_employees_enc_100-500,no_employees_enc_26-100,no_employees_enc_500-1000,no_employees_enc_6-25,no_employees_enc_More than 1000,remote_work_enc_Always,remote_work_enc_Never,remote_work_enc_No,remote_work_enc_Sometimes,remote_work_enc_Yes,benefits_enc,care_options_enc,wellness_program_enc,seek_help_enc,anonymity_enc,leave_enc,mental_health_consequence_enc_Maybe,mental_health_consequence_enc_No,mental_health_consequence_enc_Yes,phys_health_consequence_enc_Maybe,phys_health_consequence_enc_No,phys_health_consequence_enc_Yes,coworkers_enc_No,coworkers_enc_Some of them,coworkers_enc_Yes,supervisor_enc_No,supervisor_enc_Some of them,supervisor_enc_Yes,mental_vs_physical_enc,age_group_enc_18-24,age_group_enc_25-34,age_group_enc_35-44,age_group_enc_45-54,age_group_enc_55-64,age_group_enc_65+
0,37.0,Female,United States,NaN,No,1,Often,6-25,No,1.0,Yes,Not sure,No,Yes,Yes,Somewhat easy,No,No,Some of them,Yes,Yes,0.0,NaN,2014,35-44,NaN,1,1.0,0.0,True,False,False,0,3.0,False,False,False,False,True,False,False,False,True,False,False,1,2,0,1,1,1.0,False,True,False,False,True,False,False,True,False,False,False,True,1,False,False,True,False,False,False
1,44.0,Male,United States,NaN,No,0,Rarely,More than 1000,No,0.0,Don't know,No,Don't know,Don't know,Don't know,Don't know,Maybe,No,No,No,Don't know,0.0,NaN,2014,35-44,NaN,0,0.0,0.0,False,True,False,0,1.0,False,False,False,False,False,True,False,False,True,False,False,2,0,2,2,2,NaN,True,False,False,False,True,False,True,False,False,True,False,False,2,False,False,True,False,False,False
2,32.0,Male,Canada,NaN,No,0,Rarely,6-25,No,1.0,No,No,No,No,Don't know,Somewhat difficult,No,No,Yes,Yes,No,0.0,NaN,2014,25-34,NaN,0,1.0,0.0,False,True,False,0,1.0,False,False,False,False,True,False,False,False,True,False,False,0,0,0,0,2,3.0,False,True,False,False,True,False,False,False,True,False,False,True,0,False,True,False,False,False,False
3,31.0,Male,United Kingdom,NaN,Yes,1,Often,26-100,No,1.0,No,Yes,No,No,No,Somewhat difficult,Yes,Yes,Some of them,No,No,1.0,NaN,2014,25-34,NaN,1,1.0,1.0,False,True,False,1,3.0,False,False,True,False,False,False,False,False,True,False,False,0,1,0,0,0,3.0,False,False,True,False,False,True,False,True,False,True,False,False,0,False,True,False,False,False,False
4,31.0,Male,United States,NaN,No,0,Never,100-500,Yes,1.0,Yes,No,Don't know,Don't know,Don't know,Don't know,No,No,Some of them,Yes,Don't know,0.0,NaN,2014,25-34,NaN,0,1.0,0.0,False,True,False,0,0.0,False,True,False,False,False,False,False,False,False,False,True,1,0,2,2,2,NaN,False,True,False,False,True,False,False,True,False,False,False,True,2,False,True,False,False,False,False

In [58]:
df_sorted = df_clean.sort_index(axis=1)
df_sorted.head()

,age,age_group,age_group_enc_18-24,age_group_enc_25-34,age_group_enc_35-44,age_group_enc_45-54,age_group_enc_55-64,age_group_enc_65+,anonymity,anonymity_enc,benefits,benefits_enc,care_options,care_options_enc,comments,country,coworkers,coworkers_enc_No,coworkers_enc_Some of them,coworkers_enc_Yes,family_history,family_history_enc,gender,gender_enc_Female,gender_enc_Male,gender_enc_Other,leave,leave_enc,mental_health_consequence,mental_health_consequence_enc_Maybe,mental_health_consequence_enc_No,mental_health_consequence_enc_Yes,mental_vs_physical,mental_vs_physical_enc,no_employees,no_employees_enc_1-5,no_employees_enc_100-500,no_employees_enc_26-100,no_employees_enc_500-1000,no_employees_enc_6-25,no_employees_enc_More than 1000,obs_consequence,obs_consequence_enc,phys_health_consequence,phys_health_consequence_enc_Maybe,phys_health_consequence_enc_No,phys_health_consequence_enc_Yes,remote_work,remote_work_enc_Always,remote_work_enc_Never,remote_work_enc_No,remote_work_enc_Sometimes,remote_work_enc_Yes,seek_help,seek_help_enc,self_employed,self_employed_enc,supervisor,supervisor_enc_No,supervisor_enc_Some of them,supervisor_enc_Yes,survey_year,tech_company,tech_company_enc,treatment,treatment_enc,wellness_program,wellness_program_enc,work_interfere,work_interfere_enc
0,37.0,35-44,False,False,True,False,False,False,Yes,1,Yes,1,Not sure,2,NaN,United States,Some of them,False,True,False,No,0,Female,True,False,False,Somewhat easy,1.0,No,False,True,False,Yes,1,6-25,False,False,False,False,True,False,0.0,0.0,No,False,True,False,No,False,False,True,False,False,Yes,1,NaN,NaN,Yes,False,False,True,2014,1.0,1.0,1,1,No,0,Often,3.0
1,44.0,35-44,False,False,True,False,False,False,Don't know,2,Don't know,2,No,0,NaN,United States,No,True,False,False,No,0,Male,False,True,False,Don't know,NaN,Maybe,True,False,False,Don't know,2,More than 1000,False,False,False,False,False,True,0.0,0.0,No,False,True,False,No,False,False,True,False,False,Don't know,2,NaN,NaN,No,True,False,False,2014,0.0,0.0,0,0,Don't know,2,Rarely,1.0
2,32.0,25-34,False,True,False,False,False,False,Don't know,2,No,0,No,0,NaN,Canada,Yes,False,False,True,No,0,Male,False,True,False,Somewhat difficult,3.0,No,False,True,False,No,0,6-25,False,False,False,False,True,False,0.0,0.0,No,False,True,False,No,False,False,True,False,False,No,0,NaN,NaN,Yes,False,False,True,2014,1.0,1.0,0,0,No,0,Rarely,1.0
3,31.0,25-34,False,True,False,False,False,False,No,0,No,0,Yes,1,NaN,United Kingdom,Some of them,False,True,False,Yes,1,Male,False,True,False,Somewhat difficult,3.0,Yes,False,False,True,No,0,26-100,False,False,True,False,False,False,1.0,1.0,Yes,False,False,True,No,False,False,True,False,False,No,0,NaN,NaN,No,True,False,False,2014,1.0,1.0,1,1,No,0,Often,3.0
4,31.0,25-34,False,True,False,False,False,False,Don't know,2,Yes,1,No,0,NaN,United States,Some of them,False,True,False,No,0,Male,False,True,False,Don't know,NaN,No,False,True,False,Don't know,2,100-500,False,True,False,False,False,False,0.0,0.0,No,False,True,False,Yes,False,False,False,False,True,Don't know,2,NaN,NaN,Yes,False,False,True,2014,1.0,1.0,0,0,Don't know,2,Never,0.0

##### Caclulating support_score

In [59]:
df_clean['support_score'] = (df_clean['benefits_enc'] == 1).astype(int) + \
                            (df_clean['care_options_enc'] == 1).astype(int) + \
                            (df_clean['wellness_program_enc'] == 1).astype(int)

In [60]:
df_clean.groupby('support_score').size()

support_score
0    2376
1    1039
2     811
3     451
dtype: int64

##### benefits, care options, and wellness programs are categorical, with (==2) meaning 'I don't know'
##### To avoid inflation and misleading results, support_score will only sum explicit yes's (==1)

In [61]:
df_clean.isna().sum().sort_values(ascending=False).reset_index()

                                  index     0
0                              comments  4516
1               phys_health_consequence  3426
2             mental_health_consequence  3426
3                   obs_consequence_enc  3426
4                       obs_consequence  3426
5                            supervisor  3426
6                             coworkers  3426
7                    work_interfere_enc  2726
8                           remote_work  1998
9                    mental_vs_physical  1723
10                            leave_enc  1570
11                             benefits  1224
12                         care_options   887
13                     wellness_program   581
14                            seek_help   581
15                            anonymity   581
16                                leave   581
17                         no_employees   581
18                     tech_company_enc   581
19                         tech_company   581
20                       work_interfere   557
21                    self_employed_enc    18
22                        self_employed    18
23     mental_health_consequence_enc_No     0
24    mental_health_consequence_enc_Yes     0
25  mental_health_consequence_enc_Maybe     0
26    phys_health_consequence_enc_Maybe     0
27                    coworkers_enc_Yes     0
28                        anonymity_enc     0
29       phys_health_consequence_enc_No     0
30      phys_health_consequence_enc_Yes     0
31                     coworkers_enc_No     0
32           coworkers_enc_Some of them     0
33                                  age     0
34                  age_group_enc_35-44     0
35                    supervisor_enc_No     0
36          supervisor_enc_Some of them     0
37                   supervisor_enc_Yes     0
38               mental_vs_physical_enc     0
39                  age_group_enc_18-24     0
40                  age_group_enc_25-34     0
41                 wellness_program_enc     0
42                  age_group_enc_45-54     0
43                  age_group_enc_55-64     0
44                    age_group_enc_65+     0
45                        seek_help_enc     0
46             no_employees_enc_100-500     0
47                     care_options_enc     0
48                         benefits_enc     0
49                              country     0
50                       family_history     0
51                            treatment     0
52                          survey_year     0
53                            age_group     0
54                        treatment_enc     0
55                    gender_enc_Female     0
56                      gender_enc_Male     0
57                     gender_enc_Other     0
58                   family_history_enc     0
59                 no_employees_enc_1-5     0
60                               gender     0
61              no_employees_enc_26-100     0
62            no_employees_enc_500-1000     0
63                no_employees_enc_6-25     0
64      no_employees_enc_More than 1000     0
65               remote_work_enc_Always     0
66                remote_work_enc_Never     0
67                   remote_work_enc_No     0
68            remote_work_enc_Sometimes     0
69                  remote_work_enc_Yes     0
70                        support_score     0

In [62]:
for col in df_clean.select_dtypes(include=['object', 'category','float64', 'int64']).columns:
    print(f"--- {col} ---")
    print(df_clean[col].unique())
    print()
    print("------------------------------------------------------------------------------")

--- age ---
[37. 44. 32. 31. 33. 35. 39. 42. 23. 29. 36. 27. 46. 41. 34. 30. 40. 38.
 50. 24. 18. 28. 26. 22. 19. 25. 45. 21. 43. 56. 60. 54. 55. 48. 20. 57.
 58. 47. 62. 51. 65. 49. 53. 61. 72. 52. 63. 66. 59. 74. 70. 64. 67. 76.]

------------------------------------------------------------------------------
--- gender ---
['Female' 'Male' 'Other']

------------------------------------------------------------------------------
--- country ---
['United States' 'Canada' 'United Kingdom' 'Bulgaria' 'France' 'Portugal'
 'Netherlands' 'Switzerland' 'Poland' 'Australia' 'Germany' 'Russia'
 'Mexico' 'Brazil' 'Slovenia' 'Costa Rica' 'Austria' 'Ireland' 'India'
 'South Africa' 'Italy' 'Sweden' 'Colombia' 'Latvia' 'Romania' 'Belgium'
 'New Zealand' 'Spain' 'Finland' 'Uruguay' 'Israel'
 'Bosnia and Herzegovina' 'Hungary' 'Singapore' 'Japan' 'Nigeria'
 'Croatia' 'Norway' 'Thailand' 'Denmark' 'Greece' 'Moldova' 'Georgia'
 'China' 'Czech Republic' 'Philippines' 'United States of America'
 'Lithuania' 'Venezuela' 'Argentina' 'Vietnam' 'Slovakia' 'Bangladesh'
 'Algeria' 'Pakistan' 'Afghanistan' 'Other' 'Brunei' 'Iran' 'Ecuador'
 'Chile' 'Guatemala' 'Taiwan' 'Serbia' 'Estonia' 'Iceland' 'Indonesia'
 'Jordan' 'Eritrea' 'Swaziland' 'Ukraine' 'Luxembourg' 'Turkey'
 'Mauritius' 'Saudi Arabia' 'Kenya' 'Ethiopia' 'Macedonia' 'Hong Kong'
 'Ghana' 'Mongolia' 'Cameroon' 'Sri Lanka' 'Egypt' 'Malaysia' 'Belarus'
 'Albania' 'Sao Tome and Principe' 'Somalia' 'Peru' 'Panama' 'Aruba'
 'Kazakhstan']

------------------------------------------------------------------------------
--- self_employed ---
[nan  1.  0.]

------------------------------------------------------------------------------
--- family_history ---
['No' 'Yes' "I don't know"]

------------------------------------------------------------------------------
--- treatment ---
[1 0]

------------------------------------------------------------------------------
--- work_interfere ---
['Often' 'Rarely' 'Never' 'Sometimes' nan 'Not applicable to me' 'Yes'
 'Maybe' 'No']

------------------------------------------------------------------------------
--- no_employees ---
['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000' nan]

------------------------------------------------------------------------------
--- remote_work ---
['No' 'Yes' 'Sometimes' 'Never' 'Always' nan]

------------------------------------------------------------------------------
--- tech_company ---
[ 1.  0. nan]

------------------------------------------------------------------------------
--- benefits ---
['Yes' "Don't know" 'No' 'Not eligible for coverage / N/A' nan
 "I don't know" 'Not eligible for coverage / NA']

------------------------------------------------------------------------------
--- care_options ---
['Not sure' 'No' 'Yes' nan 'I am not sure']

------------------------------------------------------------------------------
--- wellness_program ---
['No' "Don't know" 'Yes' nan "I don't know"]

------------------------------------------------------------------------------
--- seek_help ---
['Yes' "Don't know" 'No' nan "I don't know"]

------------------------------------------------------------------------------
--- anonymity ---
['Yes' "Don't know" 'No' "I don't know" nan]

------------------------------------------------------------------------------
--- leave ---
['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy' 'Neither easy nor difficult' nan "I don't know" 'Difficult']

------------------------------------------------------------------------------
--- mental_health_consequence ---
['No' 'Maybe' 'Yes' nan]

------------------------------------------------------------------------------
--- phys_health_consequence ---
['No' 'Yes' 'Maybe' nan]

------------------------------------------------------------------------------
--- coworkers ---
['Some of them' 'No' 'Yes' nan]

------------------------------------------------------------------------------
--- supervisor ---
['Yes' 'No' 'Some of them' nan]

------------------------------------------------------------------------------
--- mental_vs_physical ---
['Yes' "Don't know" 'No' nan 'Same level of comfort for each'
 'Physical health' 'Mental health']

------------------------------------------------------------------------------
--- obs_consequence ---
[ 0.  1. nan]

------------------------------------------------------------------------------
--- comments ---
[nan
 "I'm not on my company's health insurance which could be part of the reason I answered Don't know to so many questions."
 'I have chronic low-level neurological issues that have mental health side effects. One of my supervisors has also experienced similar neurological problems so I feel more comfortable being open about my issues than I would with someone without that experience. '
 "My company does provide healthcare but not to me as I'm on a fixed-term contract. The mental healthcare I use is provided entirely outside of my work."
 'Relatively new job. Ask again later'
 'Sometimes I think  about using drugs for my mental health issues. If i use drugs I feel better'
 'I selected my current employer based on its policies about self care and the quality of their overall health and wellness benefits. I still have residual caution from previous employers who ranged from ambivalent to indifferent to actively hostile regarding mental health concerns.'
 "Our health plan has covered my psychotherapy and my antidepressant medication. My manager has been aware but discreet throughout. I did get negative reviews when my depression was trashing my delivery but y'know I wasn't delivering."
 "I just started a new job last week hence a lot of don't know's"
 "In addition to my own mental health issues I've known several coworkers that may be suffering and I don't know how to tell them I empathize and that I want to help."
 'Thanks for doing this research.'
 "In Russia we have mandatory medical insurance. Every employer must pay 3.6% of every employee's salary to the insurance fund like a tax. Everyone gets free healthcare at public clinics and hospitals. Some types of healthcare including mental health are still funded from the government budget but that doesn't matter it's still FREE!However this is Russia :D I don't know much about what actually happens in mental hospitals here except that a lot of young people with male in their passports use these to avoid military draft and doctors seem to help them."
 "In my previous workplace which had mental health protections policies and access to counsellors my Director went so far as to say to me in somewhat casual conversation A woman was murdered across the street. At best though she was bipolar and at worst - who knowsI have bipolar disorder. I have zero faith that an organization with policies in place could appropriately handle mental health. I have even less faith that a workplace without the policies in place could appropriately handle mental health. I can only imagine it's worse in full tech environments."
 "I've seen negative consequences towards mental health conditions in previous workplaces.Working remote is empowering in this way."
 "I'm not a permanent employee so do not get they benefits they get.My client is extremely supportive of permanent staff with mental health issues."
 "I'd be more worried about coworkers and workplace culture than the employer--they're probably legally obligated to do some things but reputation among people I work with is something else. For instance I've heard people make snide remarks about men taking paternity leave I don't want to know what they'd say about mental health leave."
 "Had a co-worker disappear from work for a few weeks and then come back to let everyone know he was bipolar. His responsibilities and schedule were adjusted to accommodate but he got worse didn't show up didn't work etc and was eventually let go.It was tough because on the one hand he was struggling with some mental health issues but on the other hand he went through a period of months where he wasn't performing."
 "Family history of depression.  Currently dealing with depression and anxiety as well as drug addition.Employer provides & pays premiums on insurance which covers therapy and prescriptions.  Employer allows work-from-home and unlimited PTO which makes episodes easier to control.I don't speak of my problems to anyone at work except for the people that I consider friends and even then I don't go into great detail.I would never bring up a mental health issue during an interview for fear of discrimination and rejection (and therefore greater depression).  One co-worker had serious anxiety problems and would not inform his team of episodes and was eventually let go for being unresponsive."
 'I feel that my employer and colleagues have created my mental health issue. Additionally I have contributed to this by staying in the same job with the same employer for 10+ years.'
 "Many of these questions become irrelevant once 'Yes' is selected for 'Are you self-employed'.  It would be preferable for there to be a 'Not Relevant' option on these."
 "as a UK-based company we don't have any medical provisions as it's all provided on the National Health Service (for now!) However if we do need to take days off for any kind of health problems everyone is understanding :)"
 'My employer employs 17k people worldwide and my previous employer only 140 globally both have been very supportive and accommodating with my moderate depression and intense anxiety.'
 "I am not sure about my company's healthcare because I've opted out of it and I'm covered under another policy.I currently work at a great company though in past jobs I don't think I would have felt comfortable talking about mental health at all."
 'In small startups it is very hard to keep mental health issues truly private no matter what management does.'
 'A close family member of mine struggles with mental health so I try not to stigmatize it. My employers/coworkers also seem compassionate toward any kind of health or family needs.'
 "Too many people even especially IT considered mental health issues as a choice or something people can freely act about. You are depressed: take vacation. You feel weird: admit it is physical (otherwise it is not serious) go and see a doctor (and if you are on sick leave too many days you will get fired). You don't feel good today: take a holiday but don't work from home. In startup there is what I call the tyranny of happiness: you have to look happy to be accepted and to be worked with. At some point playing a role can definitely make the mental health issue worse and it is also a threat to diversity :(I don't like to call mental health issues an issue but actually when it comes to company field it too often becomes an issue and this is sad because working is sometimes better than medication. It is a vicious circle: people are scared of speaking about it so they don't inform their coworkers about what mental health is for real and so coworkers are so scared on a regular basis that the people with mental health issues keep it for themselves. "
 "My seniority at the company and rapport with the owners has helped me gain support for seeking help regarding my mental health as well as being able to take time off or work from home when an episode starts.However I don't feel that the company's stance on mental health is as clear as say something like vision or dental.  There's very much a stigma."
 "When you are an introvert people don't notice if you are depressed. Its a vicious cycle of sorts."
 "I've answered 'Yes' on remote working but 50% is the maximum time we're allowed.The branch of the company I work for doesn't offer any medical benefits. It's not as common in the UK as we have the NHS for the moment. There are international branches that may so I've answered 'Don't know'."
 'Many of these questions were difficult to answer as a self-employed person; I did my best with the available options.'
 "I tried to answer as good as possible but I am CEO of a company so many questions don't fit very well.Also many of the questions are very US-centric in most systems healthcare is not your employers business."
 "One of my coworkers has mental health issues and she's open about them (eg: my enjoyment of this project may be due to my recent change in meds). I believe the response has been generally supportive. We're a very small tight-knit company."
 'A strong mind goes a long way. Stay strong. Take some time off to help. Its all in your head. '
 'Would you bring up a mental health issue with a potential employer in an interview?Poignant.'
 'I found it difficult to answer all of the questions effectively as many of them would depend on the nature of the mental health issues as some seem more socially accepted than others. For some people telling your current supervisor that you have a history of bi-polar disorder might be easier than telling a potential employer that you have a history of compulsive gambling. They might both be bits of irrelevant information (past behavior and not indicators of future behavior). However western culture pushes us to appear as capable as possible to our supervisors in pursuit of excellence in our work. Providing information that could create a negative bias seems like a more genuine and yet more risky approach to the discussion.'
 'I have only discussed my mental illness with close family members. I feel completely uncomfortable discussing with anyone at my place of employment as I am concerned it would have negative consequences.'
 'No benefits at this organization but my employer/direct supervisor has had positive and constructive conversations with me about physical and mental health. Supervisor offered solutions advice time/energy to get help if I ever felt that needed it. (though it would have to be at my own expense). I feel safe sharing personal info with this particular person/company but this environment is the exception rather than the norm in my 15+ years as a tech worker. I would never feel safe enough to reveal info about any mental health concerns with any previous employers in the tech industry for fear of  negative perceptions job loss performance dings etc. '
 'I think I am very lucky in my workplace. Our CEO has a degree in psychology.'
 "Some of these questions were difficult to answer as being self-employed they didn't all apply to me."
 "It's a small startup in a small city in a small country."
 "Hi Ed it's Paul Dragoonis. I have Aspergers/High Functioning Autism :-)"
 'The form of mental health problem that I suffer is anxiety.'
 'The thought of going through my employer directly to get help is fucking scary.Getting help is the hardest part of getting help.'
 "Don't know because I haven't checked not because it's difficult to find out. If you didn't have the don't know option I would've looked up the answer."
 "I think there might be some bugs in my thought but I haven't sought treatment because they're not worse than annoying and I worry about having the label."
 "I think a lot of our policy is based on a situation that occurred in the past 5 years. A very public mental illness happened with a coworker that unfortunately ended negatively. It was definitely a catalyst to talking about our options but the overall sentiment of it being OK to take time off talk with your supervisors etc. has always been there. It's a great company."
 "Regardless of a stated lack of negative consequences for discussing mental health issues with coworkers/superiors unconscious bias is a very real thing - as long as I don't *need* to inform my co-workers my mental health issues do not need to be public knowledge."
 'YOU MAY WANT TO THROW OUT MY ENTRY.I answered all of these questions with the assumption that Attention Deficit Disorder is considered a mental illness and with ADD in mind.'
 'In Belgium we have all medical care so perhaps some question are not relevant'
 "A co-worker recently had mental health issues and my employer was very reasonable with them I don't know the full story but I do know that he was given ample time off and eased back in to the work place."
 'My refer to the mental health issue of depression.  I might answer differently if I was talking about a more serious issue like schizophrenia'
 'My employer does what they can providing a wellness program and pointing it out after particularly stressful times. But the interaction between the wellness program and the medical insurance is unpleasant and finding a long-term therapist / psychiatrist covered by insurance is amazingly difficult. My current lack of active treatment is due to insurance friction more than workplace friction.'
 'I work for a university.'
 "Being in Canada there are several health options that are available to Canadian citizens/perm residents for free so employers may not provide resources because they are available elsewhere. Otherwise good quiz. I hope this benefits everyone who's dealt with mental health issues in the past!"
 "I'm troubled by the way that our hiring process tends to filter out non-neurotypicals of all stripes. Competent people who act a little funny can be hard to hire."
 "In Germany your employer doesn't really provide mental health benefits. There's a standard and I get that but I would get the same at any other company in Germany."
 "fwiw I am a co founder of this company and the would you X in an interview questions shouldn't reflect how I would treat anyone addressing their own phys/mental health issue to me in such a situation. "
 "I talked to a psychiatrist once about taking medical leave for mental health issues with his referral. He was willing to help but warned me that I may not want to as he's seen that sort of thing follow people throughout their tech careers (word gets out even if it's confidential at work). I've been terrified of bringing mental health up anywhere that coworkers or potential employers could see ever since."
 'So much depends upon the organization. '
 "Now at starutp.  Previously worked at big tech company which was actually quite good at supporting mental health issues.  Still wouldn't share with bosses/other employees though as there remains a strong negative stigma."
 'Nice job on the text field for gender :-)'
 "I currently have the best managers I've ever worked with. I don't have any issues but one of my coworkers recently did and it was handled extremely well. "
 'you rock for doing this!' "I don't have a job :D"
 "Israel has public health insurance for everyone. Everyone has free mental health coverage and it's quite good. So that explains some of my answers."
 "Stigma is the worst. People first language is a small step but we can't get that right."
 '-'
 'I work for an extremely supportive company and we are amazingly open about mental health issues. Employees often share their struggles with the whole team and receive a high level of support in return.'
 'I bring up my depression in interviews solely because I have a large gap on my CV due to mental health issues which could be mistaken for a gap taken to say have children which I feel would harm my chances much more. I have other MH issues I would never bring up with employers or peers.'
 "I'm not aware of anyone with mental health issues at work it's definitely not something that's discussed publicly. There's also a lot of other personal info I don't know about my coworkers so it may just be that we tend not to talk about personal issues."
 'I suffer from mild depression and anxiety.'
 "The family history question needs a don't know option."
 "I'm afraid I haven't seen mental health issues arise at work yet. They are very accommodating with maternity leave but I don't know how that translates to anything else."
 'Mental health issue I have dealt with: acute depression'
 'Thanks for doing this. It will help end the stigma!'
 'For clarity I work at a casino.'

### Save data for EDA

In [63]:
df_clean.to_csv(PROCESSED_DATA / 'cleaned_data.csv', index=False)